### ISSUE TITLE
Remove favicon.ico

### ISSUE THREAD

**Issue by nclm** [ignacionelson/ProjectSend#102]
Removing the `favicon.ico` would allow:
* No confusion from clients about what is this unknown icon;
* The ability from the webmaster to define their own icon  
  (by uploading a custom `favicon.ico` for instance);
* No overwrite of the custom favicon when updating.

**Comment by lenamtl** [comment]
I don't think that during the update the ico file get overwite.
It's not recommended to use autoupdate on live project too.

I don't see a real need for this as it's a part of customization, most of the dev will do some custom code template etc...

And it will also mean to remove all Projectsend name, logo everywhere so I won't do anything about it as I'm not the author...

I would recommend you to create your own package (template) then duplicate it for your clients.
