### ISSUE TITLE
Regex Email Fails for short addresses

### ISSUE THREAD

**Issue by crashff00** [ignacionelson/ProjectSend#105]
Apparently, short emails fail the regex test.   the address I have is ab@company-name.com, and it fails until I make the name "ab" 3 characters long.. a.b a_b, etc... but it wont take "ab" at 2 characters.

I'm not sure what's going on. I tested 4 different regex algorithms with 4 different online testers, and the address passed every one of them. but when I insert the Regex's that work into the form-validation.php page with the email checking, it still fails.

**Comment by lenamtl** [comment]
Please refer to #58

**Comment by lenamtl** [comment]
is this while creating a user or client in backend or in frontend while registering?

**Comment by crashff00** [comment]
This is while creating a user through the backend as a System User and as Admin. Self registration is disabled.

**Comment by lenamtl** [comment]
ok I can see that the JS validation and PHP validation are using different regex.
The php one seem ok, so try to edit the JS to see if it's ok.

from includes/classes/form-validation.php 
  /^[^@]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$/
and it's working ok with 2 caracters prior @ 

from /includes/js/jquery.validations.js
/^([^@])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/

**Comment by crashff00** [comment]
It appears it is in the jquery validation. changing that to match your recommendation appears to have fixed that.  Although I changed the 2,4 to 2,15 due to some domains we currently email to (i.e. someone@companyname.consulting ) some of these TLD's are going to give me a migraine.

**Comment by lenamtl** [comment]
Could you provide the complete regex you are using.

You can leave second value empty.

**Comment by crashff00** [comment]
What I have in place now is this:
form-validation.php 
 /^[^@]+@[a-zA-Z0-9._-]+.[a-zA-Z]+$/\

jquery validation is now this, and working:
/^([^@])+\@([A-Za-z0-9_-.])+.([A-Za-z]{2,15})$/
