### ISSUE TITLE
Add "Edit" button to files on the Oprhaned Files list

### ISSUE THREAD

**Issue by lifeofaboat** [ignacionelson/ProjectSend#107]
Without an edit button, this list isnt particularly user-friendly.  Currently, you have to go to the Orphaned Files list, write down/remember the files that are orphaned, go find them in the Manage Files list, and then individually edit them to add to the proper groups.

**Comment by lenamtl** [comment]
The way it's working is that you have to select files by checking the checkbox then click on Continue button located at the bottom of the table to edit them. 
I agree this is not user friendly but at least this allow you to edit several file at the time.
If you select only one file and click on Continue this will do the same thing as Edit button.

We could add an Edit button to edit one file at the time on this table to make it more user friendly.

**Comment by ignacionelson** [comment]
Someone suggested that files that are not assigned should not be considered orphans and they should appear on the manage files page. Maybe a new column with an assignments count there could be the best course of action for this problem. What do you think?

**Comment by lenamtl** [comment]
Something like Assigned / Not assigned and remove orphan list?

**Comment by crashff00** [comment]
i think this would be a huge improvement if this could be implemented. being able to see all the files in one place, with an indicator for unassigned files.

**Comment by aolee** [comment]
Would it help if , when you add an edit button, upon clicking it, javascript will programatically select the checkbox of the row and call the continue button?

**Comment by ignacionelson** [comment]
Aolee I've implemented your suggestion, thanks!!

**Comment by ignacionelson** [comment]
Just changed it so that files uploaded via web are never considered orphan. Instead they appear on the manage files page and show that they have never been assigned.
So only files uploaded via FTP and not processed are orphans.
