### ISSUE TITLE
File Upload Issues

### ISSUE THREAD

**Issue by ryandbump** [ignacionelson/ProjectSend#109]
I have been trying to debug this code to figure out how to get file upload to work for me, all to no avail. This is what it does anytime I try to upload a file, regardless of size or type. 

![screen shot 2016-04-27 at 5 31 20 pm](https://cloud.githubusercontent.com/assets/17150981/14870165/196b1d12-0c9e-11e6-855e-22d371f8ef94.png)

I originally thought the issues was from running it on a server using php 5.5.9. But it did not work on a server running the php 5.4 either.

Any ideas on how I can get past this?

**Comment by lenamtl** [comment]
Hi, 
Which server are you using?
Are you using VM, Local or online server, Linux or IIS ect...
Some verification =
check folder chmod/permission, server configuration if you want to upload big files.
Use short file name.
Try different type and size of file.

**Comment by ryandbump** [comment]
I got it working thanks. I just had to get the right permissions.

**Comment by thepresident83** [comment]
Hi, I've same issue.  I'm newer to Projectsend. On which directories should I set right permissions?
