### ISSUE TITLE
Install loop

### ISSUE THREAD

**Issue by DJIronic** [ignacionelson/ProjectSend#112]
Hello, I have problem with installation.

I got a messegae saying something like "Installation succesfully done, you can log in with you credentials now!" But when I click to the link in the message, i get back to the installations fields, after re-entering the data, I get some another error. It is on WEDOS shared hosting, can you help me please?

Thanks

**Comment by lenamtl** [comment]
Hi this is a known bug, it is related to the table prefix
https://github.com/ignacionelson/ProjectSend/issues/39
Just put back the tbl_ as prefix in sys.config.php that should fix the problem.
