### ISSUE TITLE
Problem on Manage Files after migration.

### ISSUE THREAD

**Issue by marcoslaurito** [ignacionelson/ProjectSend#113]
I'm having an issue on page: Files-->File Management.
It says "Showing 2 files" and lists only 1 file. This only file that is showed, shows only the title (the other fields like size, uploader, etc are empty).
I've tried uploading new files, and it doesn't work either.
This appears after migrating from one server to another (backup all from old one, app & db, and restoring all to new). The server config is exactly as the old one which works ok. 
Was using version 582 and even tried with version 583 on this new server, but no luck.
Can't access error logs because it is a web hosting that don't allow this.
Please any help?
Sorry for my english.

**Comment by marcoslaurito** [comment]
I've tried a fresh install with latest version r583 but i have the same problem. I've tried setting to 777 permissions to folder /upload/files. 
Files upload correct, the problem appears when manage-files page have to read files attributes like size, uploader, etc. Those fields appear empty.
I'll add screenshots showing the problem soon.
Any ideas?

**Comment by lenamtl** [comment]
Check if all files are there including the downloaded files.
Check the PHP version this maybe a too newer version some users have issue with 5.5 +
use PHP 5.4 if possible

check all settings in config file to make sure everything is ok

**Comment by marcoslaurito** [comment]
**lenamtl:**
**1)Check if all files are there including the downloaded files.**
What do you mean? Check this new screenshot.
![captura](https://cloud.githubusercontent.com/assets/17474493/15751091/31974cf2-28bf-11e6-816b-cde36cd794fd.PNG)


**2)Check the PHP version this maybe a too newer version some users have issue with 5.5 +
use PHP 5.4 if possible**
I'm using php version 5.3.29 now, also tried with older versions, and newer (php 5.4.45 for example) but it doesn't work.


**3)check all settings in config file to make sure everything is ok**
I believe you talk about config file /includes/sys.config.php. In this file i've configured db credentials OK, and the other variables are by default (tables prefix 'tbl_', site_lang 'en', max_filesize 2048 and email enconding 'utf-8')

**Comment by marcoslaurito** [comment]
lenamtl
Sorry, i've missed one point:
**4) Check the database tables**
I've looked and all seem fine, can see all the files in the tbl_files for example.
What else can i check on the db tables?

**Comment by developer99** [comment]
Which OS and where are you hosting the app?

**Comment by marcoslaurito** [comment]
**developer99:
Which OS and where are you hosting the app?**
I'm sure i'ts a Linux, but i don't have more info cause it's a shared hosting. The info i have is "Linux 2.6.18-404.el5xen i686".
I'm hosting the app on shared web hosting server, on apache.
What other info can i give you?

**Comment by marcoslaurito** [comment]
**developer99:**
i don't think that the problem could be running shell_exec script, in fact, in other pages of the same system, the file size shows correctly (check this screenshot).
![captura](https://cloud.githubusercontent.com/assets/17474493/15757266/20a2d31e-28db-11e6-9c96-3b63b7a2b208.PNG)
The problem seems to be the manage-files.php specific. The rest of the system i'ts working OK.

**Comment by marcoslaurito** [comment]
I've found another problem, maybe it is related to the first one. If a try to download an uploaded file, it downloads with 0 kb. I've checked the folder /upload/files/ (through ftp) and in there the files appear with correct size.

**Comment by lenamtl** [comment]
I  mean does allthe uploaded file are in the upload/files folder.

Also check folder chmod **upload/files** and **upload/temp**

If you are trying to upload big file there could be a problem make sure php ini allow the size.

**Comment by marcoslaurito** [comment]
**lenamtl:
1)Check if all files are there including the downloaded files.
I mean does all the uploaded files are in the upload/files folder.**

Yes, they are all there (checked by ftp accessing, even the size of the files is correct). The problem is when I try to download through ProjectSend site (tried using admin accounts and clients accounts too), they download with 0 kb.

**Also check folder chmod upload/files and upload/temp**
Tried changing permissions to this two folders, even with all the permissions enabled to all users and groups (777 value), but the problem still exists.

**If you are trying to upload big file there could be a problem make sure php ini allow the size.**
All the tests that i'm doing were done with files that weights around 100kb, even much less than that, so it's not a problem with big files.

PS: I've looked at the table tbl_files at the moment of uploading new files, the records there seems to be created ok.

What else can I try?

**Comment by marcoslaurito** [comment]
**FOUND THE PROBLEM**. It's the shell_exec function (as **developer99** stated) that has been disabled in php.ini by shared hosting provider. This function is used by ProjectSend to get the size of the file and is involved everywhere on the system (manage-file page, when trying to download a file from projectsend, etc...)
That is the cause of the missing columns and even the 0kb downloads.
Now, is there a workaround to this??

**Comment by developer99** [comment]
1 - Will the shared hosting provide change the php.ini to allow it?
2 - You would have to modify the `get_real_filesize` in functions.php to detect if shell_exec can be called and if not, then use the last resort `$ff = filesize($file);`  SO article to the subject is here - http://j.mp/1WzsO1n

**Comment by marcoslaurito** [comment]
**developer99**:
**1 - Will the shared hosting provide change the php.ini to allow it?**
I'll have to ask them but i think they won't do it because i'ts a security thing.

**2 - You would have to modify the get_real_filesize in functions.php to detect if shell_exec can be called and if not, then use the last resort $ff = filesize($file); SO article to the subject is here - http://j.mp/1WzsO1n**
Thanks, that's exactly what i've done except that i don't detect if shell_exec can be called or not, i've replaced it straight for filesize() function (i've read that filesize() works ok except for files bigger than 2gb, and this is not a problem to me because the files that i will be uploading are 50 mb max.)

**Comment by lenamtl** [comment]
I'll close this for now, reopen it if you need more help.
