### ISSUE TITLE
Upgrade breaks all functionality from r582 > r609

### ISSUE THREAD

**Issue by Guyverix** [ignacionelson/ProjectSend#117]
When upgrading from the previous version, I only get a white screen in my web browser, and nothing in my error logs after the upgrade.

Using Apache v 2.2.27, with PHP version 5.3.27 (module)

Is there a loss of backward compatibility with the new release?

**Comment by ignacionelson** [comment]
Please go to sys.vars.php and change
error_reporting(0)
to
//error_reporting(0)

Paste the errors you get here please

**Comment by Guyverix** [comment]
Fatal error: Class 'PDOEx' not found in /site/project-send/htdocs/includes/classes/database.php on line 17

**Comment by ignacionelson** [comment]
That's weird, the class is on the same file.
Anyway, go to that line and replace PDOEx with just PDO
It should work. Then you can uncomment the error_reporting line again to prevent php messages from appearing.

**Comment by Guyverix** [comment]
Beginning to think that this is due to the way my company builds out apache.  Likely this would not happen if I was able to apt install...

Fatal error: Class 'PDO' not found in /site/project-send/htdocs/includes/classes/database.php on line 18

**Comment by lenamtl** [comment]
Make sure you have enabled PDO driver from php.ini

extension=php_pdo.dll
extension=php_pdo_mysql.dll
and restart the service if your are local.

**Comment by Guyverix** [comment]
My company does not have PDO installed at all.  It was the custom build of apache that is the source of my problems.  Time to talk to the boss.. :)   Thank you very much for the assistance!
