### ISSUE TITLE
current version 608 or 609?

### ISSUE THREAD

**Issue by Blake-** [ignacionelson/ProjectSend#120]
`sys.vars.php` has the version at 608 `define('CURRENT_VERSION', 'r608');` but the site is saying that should be 609.

**Comment by crashff00** [comment]
I set up a clean test environment, downloaded the file marked as version 609, and the test environment displays as 608. Also, I have noted some past fixes are missing from the 609(608) download.

**Comment by log4en** [comment]
same problem here.

**Comment by lenamtl** [comment]
I guess it is a typo error .
I will check with Ignacio which version he took for the update.

crashff00 could you point an example of the missing fixes?

**Comment by jooker** [comment]
I'm also getting this notice to upgrade to r609 after I updated from the old version and I continue to get the notice to update. I installed on a new vhost and I continue to get the notice on the new install. Is there a simple fix to update the revision in the db or inside of one of the files to remove this notice? It also prints r608 at the bottom in the footer. 
![project-send-upgrad-notice](https://cloud.githubusercontent.com/assets/1772030/15986440/04dc50f4-2fd6-11e6-9f2c-559d12f13747.png)

**Comment by lenamtl** [comment]
Hi I didn't get the answer from ignacio yet.
As a quick solution you can edit sys.vars.php and change the value 608 to 609

`define('CURRENT_VERSION', 'r608');`
to
`define('CURRENT_VERSION', 'r609');`

**Comment by obamarodrigue** [comment]
I just installed the supposedly latest version, when i go to the client page, the files preview do nt show, and same thing for the logo.
I pened the console and, this is what am having : GET http://sweshares.swecom.cm/includes/timthumb/timthumb.php?src=http://sweshares.swecom.cm//img/custom/logo/logoSWECOM.png&w=250 400 (Bad Request)

**Comment by obamarodrigue** [comment]
Hi everybody!
I have a couple of suggestions...
I installed ProjectSend on a CentOS 6.5 server. And a friend asked me if it's not possible to add the previex for other files formats (PDF, Word or Excel).
Am learning PHP develpment... So if someone else more advanced than me can give it a try.... I think it will be cool fr milins of people around the world using ProjectSend.
Thanks!!!!

**Comment by obamarodrigue** [comment]
When you Deactivate a user, the status does not change, it remains green active label. How can i fix that?!

**Comment by stricker-k25** [comment]
in my sys.vars.php there is 

define('CURRENT_VERSION', 'r609');

but i get the notice to update to r609
