### ISSUE TITLE
Can't upload files bigger than 600mb

### ISSUE THREAD

**Issue by RKO1337** [ignacionelson/ProjectSend#122]
Hey,

i tried uploading a zip/rar archive, the size is around 680mb.
When i click in upload the file the upload stops before the process is finished (stops around 20-80%).
When the upload failed i get this screen:
![upload_failed](https://cloud.githubusercontent.com/assets/18141698/16076234/98e09fca-32f2-11e6-8676-b687a7467e07.JPG)
In the sys.config.php the max upload size ist set to 2048.
Sometimes i can upload the same file without any problems, usually i need to start the upload process up to three times. 
Im Using PHP 5.4.16 and Apache 2.4.6 and projectsend r608/609.

Any suggestions?

**Comment by lenamtl** [comment]
Hi,
you will need to change the value in your php.ini some hosting company allow to have a custom php.ini file please contact them.

Here are the value you may want to change

memory_limit = 32M
upload_max_filesize = 24M
post_max_size = 32M

**Comment by karthikeyan951213** [comment]
Dear Team

i tried uploading a zip/rar archive, the size is around 300mb.
When i click in upload the file the upload stops before the process is finished (stops around 20-80%).
When the upload failed i get this screen

![image](https://user-images.githubusercontent.com/104340226/170672741-472bd2c0-b460-473f-bc75-ddd000255970.png)
![image](https://user-images.githubusercontent.com/104340226/170673151-137b6747-4f4b-4c83-bcf1-ef3fce3e2973.png)

and i am using php 7.4 , apache 2.7 ,project send r1295
