### ISSUE TITLE
blank page at install 

### ISSUE THREAD

**Issue by ehareef** [ignacionelson/ProjectSend#125]
Dear i can't make it run under turnkey LAMP PHP it's only give me blank pages :(

**Comment by lenamtl** [comment]
Hi,
Could you provide more details...
Please provide PHP version and make sure you have set up database PDO driver.
Also do you have blank page on the install page or on login page after the install?

**Comment by ehareef** [comment]
dear, 
- my php ver. is PHP 5.6.22-0+deb8u1 
- DPO driver enabled as attached
 - blank page on the install page 

![image](https://cloud.githubusercontent.com/assets/20264703/16557022/a3f0dcd2-41dd-11e6-8ab1-bd4eb4ec7345.png)

**Comment by lenamtl** [comment]
Could you check in the page source code on install page if you see any PHP warning or PHP error?

**Comment by huppet** [comment]
Unfortunately, the data base access seems to fail silently. Please check, if your data base access rights are set correctly.
An other problem i saw under some (not all) PHP installations:
(https://github.com/ignacionelson/ProjectSend/issues/130#issuecomment-230702854)

**Comment by ehareef** [comment]
Thank you i will try this and update you with status

Sent from my Huawei Mobile

-------- Original Message --------
Subject: Re: [ignacionelson/ProjectSend] blank page at install (#125)
From: huppet
To: ignacionelson/ProjectSend
CC: Youssef Allam ,Author


Unfortunately, the data base access seems to fail silently. Please check, if your data base access rights are set correctly.
An other problem i saw under some (not all) PHP installations:
(#130 (comment)<https://github.com/ignacionelson/ProjectSend/issues/130#issuecomment-230702854>)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/ignacionelson/ProjectSend/issues/125#issuecomment-230704458>, or mute the thread<https://github.com/notifications/unsubscribe/ATU2_6SMsg1xFfn1q30bdbGJ0vqUIsNuks5qS2DPgaJpZM4JD1IB>.

________________________________

“The information contained in this communication is intended solely for the use of the individual or entity it is addressed and others authorized to receive it. It may contain confidential or legally privileged information. If you are not the intended recipient you are hereby notified that any form of reproduction, dissemination, copying, disclosure, modification, distribution and/or publication of this e-mail message is strictly prohibited. If you have received this message by mistake please notify the sender immediately by e-mail, destroy it and delete it from your system. The sender is neither liable for the proper and complete transmission of the information contained in this communication nor for any special, incidental or consequential damages of any nature whatsoever resulting from receipt or use of this communication”

**Comment by ehareef** [comment]
@lenamtl  page source code  also blank page no error no warning

@huppet i try this solution but with same result blank page

**Comment by huppet** [comment]
look at `/includes/classes/database.php`, line 28:

```
catch(PDOException $e) {
/*
	print "Error!: " . $e->getMessage() . "<br/>";
	die();
*/
	return false;
}
```
an exception doesn't generate any output as this is commented out in the code.

**Comment by ehareef** [comment]
@huppet thank you too :D it was DB connection error i fix it and now all working good 

thank you all for support :+1:
