### ISSUE TITLE
WARNING - master branch is behind the current revision on ProjectSend website

### ISSUE THREAD

**Issue by wdmtech** [ignacionelson/ProjectSend#13]
**This repo is out-of-date.**

The master branch (tagged r559) is apparently _2 revisions behind_ the current revision on the  ProjectSend website (r561).

You will notice when using the master branch, that you are informed that a "new version of ProjectSend is available to download".

**This repo needs to be updated to the latest version** - please bear this in mind when submitting changes. I have [contacted the author](http://www.projectsend.org/#contact) to see if there is any intention of updating it here.

**Comment by ignacionelson** [comment]
Fixed, thanks for noticing and letting me know!!
