### ISSUE TITLE
Blank Home/Login page after update to r609

### ISSUE THREAD

**Issue by emorga1** [ignacionelson/ProjectSend#130]
just updated to r609 from r561

home/login page now shows up blank (white)
- install page still shows up/works fine (and says ProjectSend is installed OK)

tried changing my permissions [for every folder & file on my site] to both 775 & 777
- didn't fix problem 

checked sys.config.php file
- still connects to database a-ok

re-uploaded/switched back to r561
- page showed up again/works fine

my site uses
PHP 5.5.30

**Comment by huppet** [comment]
I had a similar problem with /includes/classes/database.php
My PHP installation did not allow the use of PDOEx before its definition. I had to move up the PDOEx definition in the file and everything worked well after that.
Don't know, if this is related

**Comment by kiwee90** [comment]
huppet's solution worked for me as well. Please take the change into the next releases
Debian 8 Jessie, php 5.6, Mysql 5.7

**Comment by malik1910** [comment]
hello can i ask here??

i can't login with my admin, actually for every username in login page.the home page just blank white with Network Error (tcp_error) 

A communication error occurred: "Operation timed out"
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.

For assistance, contact your network support team.

can everybody here help me???please...

**Comment by nicohermida** [comment]
I am having the same problem. When i log in with an admin account the page remains blank. With a user log in without problemas.
This started happening at leas 15 days ago.
I tried changing the php version but nothing changed.
I tried restoring backups and nothing happend.

any suggest?
