### ISSUE TITLE
Problems uploading, assigning, managing files

### ISSUE THREAD

**Issue by SFisherlmp** [ignacionelson/ProjectSend#134]
I have installed ProjectSend as recommended. As a System User or Client, I choose to upload a file and it won't allow me to save so that I can manage it.

It goes to the Orphan area and nothing can be done with it. No download, no assigning, no deleting.

My server is:
Apache Version: 2.4.18
PHP Version: 5.6.18
MySQL Version: 5.6.30
Architecture: x86_64
Operating System: Linux

I do volunteer website work for a group that are coming together to teach Oncology Massage.

I thought I had found the answer to their needs with what was spoken about you software, but I can't seem to get it to work.

They just need a space to upload and share their documents and such, as they are in different parts of the country.

Please can you help me to figure this out so I can help them.

Thank You,
Sharon Fisher

**Comment by mriolo** [comment]
It sounds to me like you want to setup all the group members as system users with the 'uploader' role.  This way when they upload files they can assign permissions to the uploaded file(s) to other users/groups at upload time.  I don't believe client users are able to set permissions on files they upload to share with other clients, so you don't want them setup as such.  If assignments are not made at the time the file is uploaded, then a system user with the administrator role will need to assign the file after the fact.

**Comment by SFisherlmp** [comment]
I tried uploading files as administrator and I couldn't assign them. They
became Orphaned files, which I couldn't do anything with.

**Comment by SFisherlmp** [comment]
I really like the ease of your software and want to use it because those I
am volunteering assistance for are not very computer techie. The easier the
better with their limited time schedules.

I know the Oncology Massage Education Associates will find it easy enough
also once this challenge is solved.

Thank you for helping.

Sharon

**Comment by SFisherlmp** [comment]
I am logged in as Administrator ---

[image: Inline image 1]

Then I click "Continue".  Screen blinks and returns this screen ---

[image: Inline image 2]

The file is not here ---


[image: Inline image 3]

But it is here.  And I can do Nothing with it.  I can't delete, assign or
anything.

[image: Inline image 4]

I have checked the database user - Full privileges.

I tried changing permissions on files and folders - that is *bad*, as then
I needed to uninstall and re-install your software.

I tried it (4) times the other night before deciding to email you.

I am desperate to get it to work.

Thank You,
Sharon Fisher

**Comment by obamarodrigue** [comment]
Hi,
I used to have quite a similar problem. My fix was giving full access to the entire folders and files:
chmod -R 755 /var/www/html/projectsend
When, I couldn't still upload and process the file, i increased the authrization to 766, 776 and finally 777.
I don't know if this can help in your case.

**Comment by lenamtl** [comment]
I close this let us know if you still have a problem
