### ISSUE TITLE
page isn’t working, http error 500

### ISSUE THREAD

**Issue by kt1024** [ignacionelson/ProjectSend#135]
install under ubuntu 14.04 lts, with LAMP stack installed. none of projectsend files(direct url) can be loaded. did I miss something?
php info & default apache page is ok.
![image](https://cloud.githubusercontent.com/assets/12657496/17010529/72d91e2c-4f37-11e6-88d9-2082a06dd785.png)
thanks.

**Comment by obamarodrigue** [comment]
Hello,
Unfortunately I have not been able to see the link you provided.
But, on a general note, a 500 http error is an internal server error (meaning, something went wrong but the server does not have information to provide).
So what I'll suggest is to cautiously do the installation of your LAMP stack, making sure, everything that t be enabled is enabled, the proper authorizations and so on.
Except if you took don your server (link above), to my opinion, you have check the server internal Firewall.

**Comment by kt1024** [comment]
fixed. try unzip & edit files in linux and works. (previously I've unzip files in windows then upload to linux).
thx.
