### ISSUE TITLE
PDOExceptions after /install/index.php

### ISSUE THREAD

**Issue by MHerrERC** [ignacionelson/ProjectSend#136]
I´m trying to get projectsend r608/609 to work.
OS: ubuntu 16.04 LTS
php7 and php5.6 tested.
phpinfo() is ok, database user and login seems to be ok (no errors in mysql logs), pdo is also enabled (tried a fix from a pull request)
![image](https://cloud.githubusercontent.com/assets/20573234/17014154/445bb4ce-4f23-11e6-8907-a5ca43245f0c.png)
after filling all basic informations and pressing the install-button I always get this:
![image](https://cloud.githubusercontent.com/assets/20573234/17014227/b552c83e-4f23-11e6-89bd-706f93bd292d.png)
I´ve got no further ideas, what I´m doing wrong. Can someone please have a look at this and give me an hint?
Thanks.

**Comment by ragnos** [comment]
I'm facing the exact same issue. I'm running this on a test server which is housing multiple other projects, including those using PDO, without issues.

Debian Jessie, software provided by distribution:
Apache 2.4
PHP 5.6
MySQL 5.5

**Comment by lenamtl** [comment]
Do you have the error using php 5.5

**Comment by th3b00** [comment]
Same problem here with Ubuntu 16.04.1 LTS

**Comment by lenamtl** [comment]
I got a lot of problem too on install page I have no problem using other pdo application,
I'm using phpmyadmin and it was set to strict mode
I have empty sql-mode="" in my.ini 
restart service if still issue restart the computer 
I'm not 100% sure that was problem but now it is ok

**Comment by emptythevoid** [comment]
Same issue here.  I did a fresh install of Ubuntu 16.04.1 with the default LAMP setup (installs PHP 7.0.8).  mysql database created (mysql-server-5.7.13) , user granted.  Tested apache, tested php.  Both of those seem fine.  Copied and configured r609.  I can get to the /projectsend/install/index.php in my browser just fine, but just like the OP, as soon as I fill it in, I get the same exceptions.

I have no idea what I'm doing, but phpinfo shows that PDO is enabled.

**Comment by lenamtl** [comment]
I don't know if it is compatible with PHP7

**Comment by emptythevoid** [comment]
Ah, that would explain it. :)

**Comment by Retrospector** [comment]
Having the exact same problem. R754, Ubuntu 16.04 LTS, PHP 7.0.8, MySQL 14.14
