### ISSUE TITLE
how to: support chinese characters in file name

### ISSUE THREAD

**Issue by kt1024** [ignacionelson/ProjectSend#139]
currently chinese characters in file name will be removed after upload. (both in ps in linux file system).
thx.

**Comment by lenamtl** [comment]
This is the best way to do it, otherwise you may have issues.
However you may want to change the regex that rename the file to what you want.

**Comment by kt1024** [comment]
before upload:
![image](https://cloud.githubusercontent.com/assets/12657496/17198111/3f67d772-54a5-11e6-8650-4404e0497df7.png)

after upload:
![image](https://cloud.githubusercontent.com/assets/12657496/17198112/44ea58aa-54a5-11e6-8fe0-64f244e48d74.png)

ps should keep the origin file name.

**Comment by lenamtl** [comment]
You can read some security problem when not renaming the files: https://www.owasp.org/index.php/Unrestricted_File_Upload

One of there suggestion

> All the control characters and Unicode ones should be removed from the filenames and their extensions without any exception. Also, the special characters such as “;”, “:”, “>”, “<”, “/” ,”\”, additional “.”, “*”, “%”, “$”, and so on should be discarded as well. If it is applicable and there is no need to have Unicode characters, it is highly recommended to only accept Alpha-Numeric characters and only 1 dot as an input for the file name and the extension; in which the file name and also the extension should not be empty at all (regular expression: [a-zA-Z0-9]{1,200}\.[a-zA-Z0-9]{1,10}).

**Comment by kt1024** [comment]
got it. thanks.
