### ISSUE TITLE
Hackers uses process-upload.php directly to upload Viruses.

### ISSUE THREAD

**Issue by h2soft-de** [ignacionelson/ProjectSend#14]
The Lib seems to be common, so i only renamed the file and modified upload-from-computer.php to use the new file. I hope this helps.

**Comment by bchhun** [comment]
+1 Had the same issue.

**Comment by semaphorism** [comment]
Is one quick fix to include `$allowed_levels = array(9,8,0);` at the beginning of the file before `require_once(...)`?  

It would be nice to see more checks here though - and maybe a newer version of plupload.

**Comment by ignacionelson** [comment]
Added your solution plus a check to see if the user is logged!

**Comment by rouben** [comment]
Is this a duplicate of #61 and was fixed by #62 ?

**Comment by lenamtl** [comment]
We can close this
