### ISSUE TITLE
Error After Uploading Files

### ISSUE THREAD

**Issue by feraldan** [ignacionelson/ProjectSend#140]
Whenever I upload a file, it successfully uploads, however on the screen after the upload where you assign those who can view it and such, once I click 'Continue', I get a 500 Internal Server Error no matter what settings I provide. It did not do this in version r608. Is anyone else having this issue?

**Comment by lenamtl** [comment]
Which version are you using?
make sure to chmod upload folder

**Comment by feraldan** [comment]
r609

What do the permissions need to be? They are set to 755 currently, although I tried 777 without resolving the issue.

**Comment by lenamtl** [comment]
Do you have enable PDO driver in PHP

**Comment by feraldan** [comment]
My host is running v5.4 which has PDO enabled by default. Is there a specific one that needs to be enabled?

**Comment by lenamtl** [comment]
Hi 
someone have post a debug code which is not commit yet (I have not tried it)
but you can edit your file manually for a test
https://github.com/ignacionelson/ProjectSend/pull/128

**Comment by emmaferguson** [comment]
I had the same issue and was running on Centos 7. Installed via git clone as per this article after a lot of issues on Ubuntu with the PDO extensions: http://idroot.net/linux/install-projectsend-centos-7/
Spent alot of time troubleshooting permissions w/ Centos 7 only to find I had missed one small line in the article regarding SELinux being in enforcing mode. Changed to permissive and everything was good after that.

**Comment by lenamtl** [comment]
I close this let us know if you still have problem
