### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by adrian99420** [ignacionelson/ProjectSend#141]
I just did fresh installation of projectsend from softaculous but still encounter the problem of login to admin panel.

After logging in with my admin username and password the page will always hang at index.php without any error message. I am using r608 version and I never changed the table prefix. Any idea how can I get through this? Thanks!

**Comment by lenamtl** [comment]
Hi,
I don't know if the Softaculous version is the same but the newest Projectsend use PDO driver that need  to be enable on your server.

**Comment by ignacionelson** [comment]
Closing since this is a server issue.
