### ISSUE TITLE
Removing file assignments puts file back in orphans list, also in file manager (R611)

### ISSUE THREAD

**Issue by crashff00** [ignacionelson/ProjectSend#149]
I assigned a test file to a user to verify some settings (re-arranging the table layout and adjusting table display sizes) this works properly. the file is removed from the orphans list, and shows up in the file manager as expected.

When I removed the assignment, the file remains in the file manager list, but it ALSO shows up in the orphan files list /again/ with this description: "All assignations were removed / File is not public."

I believe this can be fixed by removing the orphan files list altogether as suggested in #107

**Comment by ignacionelson** [comment]
Unassigned files treated as orphans is a residue from when the software only allowed each file to be assigned to one client only. 
I believe that "orphans" should only be files that were uploaded via FTP.

**Comment by ignacionelson** [comment]
Done on commit cc79b51
