### ISSUE TITLE
public files assigned to a client (user) display as orphans

### ISSUE THREAD

**Issue by tsumaru720** [ignacionelson/ProjectSend#15]
*copied from gcode*

What steps will reproduce the problem?
1. Upload file as user
2. Make it public
3. Assign to a client
4. View Orphaned files and its listed

What is the expected output? What do you see instead?
* If the file is assigned to a client then it shouldnt display as orphaned

What version of the product are you using? On what operating system?
r561 - Linux Ubuntu 12.04

**Comment by ignacionelson** [comment]
I never had this problem on the latest versions. I'm closing the issue, but feel free to reopen if something happens.
