### ISSUE TITLE
Fix SSL Mixed Content - PinBoxes templates

### ISSUE THREAD

**Issue by Jean-BaptisteFR** [ignacionelson/ProjectSend#151]
Hello,

I have see and correct some problem when the SSL (HTTPS) is using with the PinBoxes Templates:
https://github.com/ignacionelson/ProjectSend/pull/150

Have nice day :)

Jb

**Comment by ignacionelson** [comment]
Done, thanks!!!!

**Comment by Jean-BaptisteFR** [comment]
Thanks to you ! :)

2016-09-01 17:35 GMT+02:00 Ignacio Nelson <notifications@github.com>:
