### ISSUE TITLE
Feature request: allow email to be entered as username

### ISSUE THREAD

**Issue by Joohansson** [ignacionelson/ProjectSend#154]
Currently user name only support alphanumerics. Why email?

1. Account manager don't need to come up with a unique user name for each client. Password is bad enough, should be auto-generated and at least 12 characters
2. The client don't need to remember both user name and password (everybody knows their email)
3. Easier to find client uploaded files in the list if sorted by email (manager don't need to remember which client had which username)

**Comment by ignacionelson** [comment]
Done, thanks for the suggestion!
