### ISSUE TITLE
Suggestion: Button to generate random password

### ISSUE THREAD

**Issue by Joohansson** [ignacionelson/ProjectSend#155]
When creating a new user/client. Add a button that automatically generates a random unique password based on the global password minimum requirements. This will make it easier to create new users and avoid stupid passwords.

Edit: Similar suggestion mentioned here - https://github.com/ignacionelson/ProjectSend/issues/67
Closing issue to avoid duplicate

**Comment by paspo** [comment]
It's also a good idea to have a checkbox in the same form for sending the password  to the user/client in the welcome email.
