### ISSUE TITLE
User with "uploader" role unable to delete its own files

### ISSUE THREAD

**Issue by Joohansson** [ignacionelson/ProjectSend#157]
Using version r609, apache 2.2 and php 5.6. File uploaded from a system user with uploader role can't be deleted from that user. I get a green message "The selected files were deleted" but the file is still in the list. Users with admin or account manager role can delete the same file just fine. The file is not assigned to anyone.

**Comment by Joohansson** [comment]
I found this in actions-files.php. But maybe uploaders was not meant to delete others files.. The green message is wrong anyway.

function delete_files($rel_id)
	{
		$this->check_level = array(9,8);

**Comment by lenamtl** [comment]
Admin and Account Manager can delete file.
Uploader and Client cannot delete file.
