### ISSUE TITLE
Suggestion: Make public link button visible directly after upload

### ISSUE THREAD

**Issue by Joohansson** [ignacionelson/ProjectSend#158]
To make it easier for users to upload files for public access. This edit make the public link visible directly after upload. No need to go back to "manage files" in order to get the link. Perhaps not perfectly solved but if you need my code here it is. In order to get the link I had to generates the public link before it sends the file to "upload_add_to_database". edit-file.php is not affected by this.

![ps_public](https://cloud.githubusercontent.com/assets/2406720/18003791/5ee4d12a-6b90-11e6-8a68-cf1236a9b82b.JPG)
[file-upload.php_edit.txt](https://github.com/ignacionelson/ProjectSend/files/439183/file-upload.php_edit.txt)
[upload-process-form.php_edit.txt](https://github.com/ignacionelson/ProjectSend/files/439224/upload-process-form.php_edit.txt)

**Comment by ignacionelson** [comment]
Done! Thanks!
