### ISSUE TITLE
file expiring date show for all 

### ISSUE THREAD

**Issue by donsenilo1968** [ignacionelson/ProjectSend#159]
How can I change that the file expiring date is shown to all users ?

**Comment by lenamtl** [comment]
Which files? assigned private or public?

**Comment by donsenilo1968** [comment]
private and public

**Comment by donsenilo1968** [comment]
This is a screenshot as Admin where you can see the expiring date:
![screenshot_4](https://cloud.githubusercontent.com/assets/21273937/18039526/3aa382c8-6da4-11e6-9eac-e83a111369c5.jpg)
And here as "normal" user:
![screenshot_3](https://cloud.githubusercontent.com/assets/21273937/18039534/4430e43e-6da4-11e6-9756-2ea2c379604d.jpg)
Is it possible that a normal user also can see the expiring date ?

**Comment by lenamtl** [comment]
You will need to edit user template page and change the table.

**Comment by donsenilo1968** [comment]
> You will need to edit user template page and change the table.

This is not helpful. Can you please more specific ?

**Comment by ignacionelson** [comment]
What do you think? Should this be the default behavior? Maybe add an option?

**Comment by donsenilo1968** [comment]
> Should this be the default behavior? Maybe add an option?

If a file has an expiring date, how can a user know about that ?
Actual not.
Solutions:
1. The expiring date in the mail
2. The expiring date on the website
Both solutions would be very helpful and a true enhancement.

**Comment by ignacionelson** [comment]
I can't think of any yet, but maybe there are cases where the uploader doesn't want clients to know that the file will expire?

**Comment by donsenilo1968** [comment]
hmm ...
example: you get a mail, that a new file is uploaded (it expires in 3 days, but you don't know it because you don't see it). and you are so in stress, that you can download that file after 4 days ... but you can't, because meanwhile it's gone.

**Comment by crashff00** [comment]
I think there should be 2 things done for this:
1 - Include the expiration dates in the notification email that says the file is now available,
2 - in the client file screen, make the expiration dates visible

I think anything beyond that is excessive in the amount of work it would take to implement ( you would have to run some kind of scheduled task to check for what is expiring before the notices could be generated )

**Comment by ignacionelson** [comment]
Added the expiration date column to the default template.
Still need to add the info to the other templates, and the email.

**Comment by ignacionelson** [comment]
Added it to the pinboxes theme.

**Comment by lenamtl** [comment]
Is this completed?

**Comment by donsenilo1968** [comment]
Yes, thank you.
