### ISSUE TITLE
Wrong credentials and blank page after r609 update

### ISSUE THREAD

**Issue by heavenkinder** [ignacionelson/ProjectSend#160]
Hello. 
I have ProjectSend installed and i was trying to login and nothing work, always saying the credentials were wrong eventhough i am 100% sure it was right and i couldn't do anything about it, i went to search about the updates on projectsend and they had updated to r609. I thought it might had something to do, regarding that the update was made also to the database file because of the PDOEx, but now, i have a blank page. I can't do anything, i can't even try to login now. I don't if you can help me out with it or if it's something to do with the permissions but i really need this fixed ASAP and i've been trying and i'm getting nowhere. I already tried moving the PDOEx class up but it didn't fix anything. I went to the include file and killed the php file after each include and found it that the first time it doesnt do the "die()" is at line 39 "require_once(ROOT_DIR.'/includes/active.session.php');" and then in the line 15, it breaks there. I do a die after that if and that die isn't shown. I don't know what else to try and i need help as fast as possible... Can't someone give me a hand please?

**Comment by lenamtl** [comment]
Hi what was the previous version when logging was working ok?

**Comment by heavenkinder** [comment]
I'm not sure, is there any file i check the version? Because i have a backup

**Comment by heavenkinder** [comment]
Please can you help me, it's urgent. In 2 days i'm going to have clients using the plaform

**Comment by ignacionelson** [comment]
Hello! Sorry to see that you are having this problem.
Please comment line 33 on sys.vars.php
error_reporting(0);
(should then read
//error_reporting(0);
)
and let us know what error you get when you load the site.

**Comment by heavenkinder** [comment]
Parse error: syntax error, unexpected 'catch' (T_CATCH) in /srv/disk8/794898/www/ec.mvber.eu/auditoria/includes/classes/database.php on line 10

**Comment by heavenkinder** [comment]
I made it, instead of overwriting the update on top of what i had on the server, i deleted everything and re-uploaded the r609, including re-configuring the sys.config file

**Comment by heavenkinder** [comment]
Thank you anyway people

**Comment by ignacionelson** [comment]
Oh nice! I've also hidden the absolute path on your comment just so it's not out there
