### ISSUE TITLE
Code fix: Bad link in some custom email templates

### ISSUE THREAD

**Issue by Joohansson** [ignacionelson/ProjectSend#162]
In templates "New file by user" and "new file by client" the link should be %URI% but in the code it is %LINK%.

Attached fix in send-email.php row 267 and 295. Changed from %LINK% to %URI%. (Sorry, don't know how to create a pull request. I'm new to github).

[send-email.php.txt](https://github.com/ignacionelson/ProjectSend/files/441778/send-email.php.txt)

**Comment by ignacionelson** [comment]
Thanks for your input!
But I don't see this as a bug.
The actual tag on the html file that gets replaced is indeed %LINK%

Did you get missing info on your emails?

**Comment by Joohansson** [comment]
Correct but that is not told to the user in the UI where it says %URI%. If you use URI you get no link in the email. You have to change somewhere, either in send-email.php or on the page where you define your template. I had to find the corresponding code to get my emails correct.

**Comment by ignacionelson** [comment]
Oh, true! Nice find! Fixing it right away!

**Comment by ignacionelson** [comment]
Done, thanks!
