### ISSUE TITLE
Install page does not work using Wampserver 64 bit / Windows

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#163]
Blocking problem I cannot install on Windows

The new page that check the system gave me error / red ! even if info are ok
I'm getting error on these fields even if info are ok
Host  Username  Password  DB name

**Comment by ignacionelson** [comment]
That's weird, I'm on windows too. The red seems to be there by default when you load the page. After checking, if everything is ok, it changes for me.

**Comment by lenamtl** [comment]
I think the problem is related to phpmyadmin **sql-mode** that is **strict** by default.
Since I have empty the sql-mode and restarted the computer the problem was gone.
PS only restarting the services was not enough.
