### ISSUE TITLE
Suggestion: Make username and email case insensitive for logins

### ISSUE THREAD

**Issue by Joohansson** [ignacionelson/ProjectSend#165]
From my experience in windows-world and Internet, user names and emails are very seldom case sensitive. I think Linux is different but I don't see any reason why you would want that. A good password is secure enough. It just causes confusion for the user.

Suggested change in index.php:
Old - `SELECT * FROM " . TABLE_USERS . " WHERE BINARY user= :username OR BINARY email= :email`
New - `SELECT * FROM " . TABLE_USERS . " WHERE user= :username OR email= :email`

**Comment by ignacionelson** [comment]
I see your point. Right now you can't create users with the same name but different casing. Ex: if admin exists, you can't create ADmin or adMin.
I believe the check was added as extra security but doesn't really provide much.
