### ISSUE TITLE
Rename file with accent does not work anymore

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#168]
Have a file named **été test.png**
result will be 
�_t�_193_1.png

and won't be uploaded
so this is blocking

**Comment by ignacionelson** [comment]
"Fixed" but the result is not optimal.
It's replacing every char with a _, while for example é should be replaced with e.

**Comment by lenamtl** [comment]
Thanks

**Comment by ignacionelson** [comment]
Fixed on commit e67fa31

**Comment by Joohansson** [comment]
Swedish characters å, ä and ö are replaced by double underscores. Not a big deal but just so you know.

**Comment by ignacionelson** [comment]
This should be fixed now. Are you having this problem with the git version or with r609?

**Comment by Joohansson** [comment]
Ah sorry, I missed the latest update "Better renaming of uploaded files". I use r609 with some modified code right now.
