### ISSUE TITLE
Add a class to generate the tables

### ISSUE THREAD

**Issue by ignacionelson** [ignacionelson/ProjectSend#172]
Code is hard to read right now as each table is hard coded.
Also, if tables are generated by a class, it would be easy to implement a custom pagination instead of the one from footable. This is a problem in pages like "Manage files" where each row has a couple of SQL queries and the site takes some time to load if there are many results.

**Comment by lenamtl** [comment]
+1
I have switched to datatables since it is responsive and have more functions

**Comment by ignacionelson** [comment]
Done!
