### ISSUE TITLE
Problem with download of larger files

### ISSUE THREAD

**Issue by FrankvdAa** [ignacionelson/ProjectSend#173]
When uploading a large file, f.e. 4.6GB OVF, everything is working fine, but when trying to download that same file, it stops every time at ~618MB. In Apache logging it shows a HTTP status 200 with 648453632 bytes.

Also tried with a text file of 2.2GB, but still no luck; this one fails at ~900MB.

After a quick debug I found out that readfile() in download.php is stopping at 648453632 bytes.

Managed to solve this issue by replacing readfile() in download.php:

```
65c65,73
<                                       readfile($real_file);
---
>                                       $hfile = fopen( $real_file, 'rb' );
>                                       $buffer = '';
>                                       while( !feof( $hfile ) ) {
>                                               $buffer = fread( $hfile, 4096 );
>                                               print $buffer;
>                                               ob_flush();
>                                               flush();
>                                       }
>                                       fclose( $hfile );
```

**Comment by Joohansson** [comment]
I have the same problem with all files over 2GB. The file is downloaded correct, all bytes are there but the file is corrupt! Adding your code fixed the problem (thanks!) but the download speed went down from 80MB/s to 13MB/s. How can I speed things up? Increasing the buffer size did not have any effect.

**Comment by ignacionelson** [comment]
On [this post in SO](http://stackoverflow.com/questions/14664409/fread-a-lot-slower-for-downloads-than-readfile) user mr.freshwater suggests using stream_context_create() and stream_get_contents()

The example set there is this

`$context = stream_context_create();
$file = fopen($url, 'rb', FALSE, $context);
while(!feof($file))
{
    //usleep(1000000);
    echo stream_get_contents($file, 2014);
}`

Joohansson, can you please check if using this functions fixes the problem for you?

**Comment by Joohansson** [comment]
My test environment has slower download speed for some reason, have no idea why because it's the same web server. Only difference is an invalid https cert on test page because I connect using an IP instead of host name.

Both code example seems to work on my production server though with same speed as before and no corrupt files. My final code:

**download.php:**
```
if (file_exists($real_file)) {
					while (ob_get_level()) ob_end_clean();
					header('Content-Type: application/octet-stream');
					header('Content-Disposition: attachment; filename='.basename($real_file));
					header('Expires: 0');
					header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
					header('Pragma: public');
					header('Cache-Control: private',false);
					header('Content-Length: ' . get_real_size($real_file));
					header('Connection: close');
					//readfile($real_file);
					
					$context = stream_context_create();
					$file = fopen($real_file, 'rb', FALSE, $context);
					while(!feof($file))
					{
						//usleep(1000000); //Reduce download speed
						echo stream_get_contents($file, 2014);
					}
					fclose( $file );

					die();
				}
```
**process.php:**
```
if (file_exists($this->real_file)) {
							while (ob_get_level()) ob_end_clean();
							header('Content-Type: application/octet-stream');
							header('Content-Disposition: attachment; filename='.basename($this->real_file));
							header('Expires: 0');
							header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
							header('Pragma: public');
							header('Cache-Control: private',false);
							header('Content-Length: ' . get_real_size($this->real_file));
							header('Connection: close');
							//readfile($this->real_file);

							$context = stream_context_create();
							$file = fopen($this->real_file, 'rb', FALSE, $context);
							while(!feof($file))
							{
								//usleep(1000000); //Reduce download speed
								echo stream_get_contents($file, 2014);
							}
							fclose( $file );

							exit;
						}
```

**Comment by ignacionelson** [comment]
Thanks for the code! Worked like a charm.

**Comment by olimax** [comment]
I'm not sure why this needs to be set to 2014
`echo stream_get_contents($file, 2014);`

I was getting failed downloads until I changed download.php to 
`echo stream_get_contents($file); // param2 defaults to -1`

Can we change this

**Comment by Python-cffi78** [comment]
@ignacionelson https://phps.space/questions/difficulty-encountered-while-using-fopen-to-download-file-in-php
