### ISSUE TITLE
Improve password security when accounts are created with Google Sign-in

### ISSUE THREAD

**Issue by pmclain** [ignacionelson/ProjectSend#176]
When new accounts are created the via Google sign-in a password is generated in the ClientAction class. The password generation method is not perfectly random and should be corrected or removed. I'm not sure what the preferred method of correction would be. I am currently evaluating two options and welcome input and/or suggestion.

1. Use the random.org API for generating the random numbers used during password generation.

2. Disable login using password on these accounts until the client sets their own password.

**Comment by ignacionelson** [comment]
I have added the [random_compat() polyfill](https://github.com/paragonie/random_compat) to be able to use random_bytes() in php 5.x
The Google callback file is now reflecting this. Is there any other place I missed?

**Comment by pmclain** [comment]
No sorry. I thought I closed this after learning you added random_compat().
