### ISSUE TITLE
logo on the login page

### ISSUE THREAD

**Issue by shoulders** [ignacionelson/ProjectSend#177]
I would like to see the logo on the login page. This would help with clients knowing they are on the right website and brand awareness will be helped. For people who do not want this perhaps a simple on/off toggle in settings.

**Comment by lenamtl** [comment]
See #101

**Comment by shoulders** [comment]
i did look at that, but it did not cover simply adding the logo. It was about templating the login page.

But i am happy if it will get covered there.
