### ISSUE TITLE
cannot add a file to a group if there are no clients

### ISSUE THREAD

**Issue by shoulders** [ignacionelson/ProjectSend#178]
When you first install ProjectSend you are unable to upload files via the main admin account because you get a warning about there are no clients created (sorry i forgot to get the exact error message).

This is only really a problem when you first start out and are wanting to configure the groups with the relevant files before going live with the site. i.e. 'Website Design group' and inside this you include the website design pointers for the client to download, your terms and conditions etc..

**Comment by lenamtl** [comment]
Suggestion this can be transform to be  only a warning without blocking the function.

**Comment by ignacionelson** [comment]
Fixed! If no clients or groups exists, a warning is shown but you are still allowed to upload and import files.
