### ISSUE TITLE
Cannot install on Php7.0-fpm

### ISSUE THREAD

**Issue by Phenomite** [ignacionelson/ProjectSend#179]
Not sure if it's a php config issue on my end (would be happy to be told the fix), or if it's application specific.
![help](https://cloud.githubusercontent.com/assets/8285537/18473583/11d0529a-7a01-11e6-9152-4962db51c6f1.PNG)

There seems to be an error. Please try again.

PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'expiry_date' in /var/www/****/install/index.php:31

Know what could be causing this?

**Sys versions:**

PHP 7.0.10-2+deb.sury.org~xenial+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, 

mysql  Ver 14.14 Distrib 5.7.13, for Linux (x86_64) using  EditLine wrapper

**Comment by Phenomite** [comment]
Edited database.php and changed 
  `expiry_date` TIMESTAMP NOT NULL, to include "DEFAULT CURRENT_TIMESTAMP()" like the latest commit and that fixed it!

I tell ya, I hate new core operating updates (php7)

**Comment by kylegordon** [comment]
@Phenomite thank you for that. I had this issue the other week, and never got around to investigating.

**Comment by genxcoders** [comment]
I can see this line: 
`expiry_date` TIMESTAMP NOT NULL DEFAULT \'0000-00-00 00:00:00\',

how do i put this "expiry_date TIMESTAMP NOT NULL, to include "DEFAULT CURRENT_TIMESTAMP()""... I am noob actually...
