### ISSUE TITLE
Requirement fo production environment question

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#181]
Hi,
Regarding the latest build.
Does the latest build is solid enough to use it in production environment?
I need to install it on production environment Linux server so which PHP version should I use?

Thanks

**Comment by ignacionelson** [comment]
It would be ok to install the download the master from here and use it. It's not marked as release but the only thing preventing me to package it is a bug when you upload files with the same name. Otherwise, it's much, much better tan r609.

**Comment by lenamtl** [comment]
Could you fix it this weekend?

**Comment by ignacionelson** [comment]
I'm on it right now :)

**Comment by lenamtl** [comment]
Very appreciate thanks

**Comment by ignacionelson** [comment]
Fixed it yesterday on c406921

**Comment by lenamtl** [comment]
I'll reopen this as performance is bad when having like 2000 small files 
it's load all the files on the first page.....

It cannot be use in production for that reason

**Comment by lenamtl** [comment]
There is a perfomence issue that prevent using this in production #94
