### ISSUE TITLE
Suggestion: File upload renaming to randomized character string

### ISSUE THREAD

**Issue by crashff00** [ignacionelson/ProjectSend#183]
With the problems experienced renaming files for upload (i.e. latin characters, underscores, unrecognized characters, etc)  I was thinking it may be more efficient if the system renamed the files to a randomized Hex string at the time of upload.

Your file starts as "some long name created by word when you save.docx" .
When you upload the file to PS, PS stores that original file name in the database, but renames the file itself as "F01517CA1569.file" for storage. You could even add a number check to see if the random file name is already in use and generate another one if it is.

By using a standardized file naming convention ( and adding a nonsense extension on the end like .file), could alleviate some issues like file storage and reference, and possibly mitigate some security issues like executable files or macros being snuck into your system. Randomizing the file name each time it's uploaded would prevent someone from trying to upload a file over the top of another pre-existing copy, and you you're less likely to have people trying to delete files from the backend/ftp upload side and wreaking havoc (like in my office)

Many secure file downloads from banks and government agencies do this to prevent people from knowing what a file contains before they can access the file.

**Comment by lenamtl** [comment]
Using timestamp for name is also a good solution + saving the real file name in another row.

**Comment by ignacionelson** [comment]
So randomstring + timestamp + .file could work

Overall the whole processing of uploaded files needs to be reworked so this could come in handy later.
The problem right now is that the forms to add the file information to the database, and the edit file forms, while sharing the same design, are separeted. This makes it harder to maintain, and also applying each change to 2 forms leads to possible errors and is waste of code+time.

One thing that I think will be a problem is if you want to download your files via FTP. Then it would be a chore to rename them. But hey, in the name of security, it might be worth it...

**Comment by ignacionelson** [comment]
Fixed on 4a2e3b5
