### ISSUE TITLE
CSS and responsive issue

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#184]
In all form 
Field content overlap the field icon
Button are not responsive

Orphan text link is not responsive

View as a client is the worste but other are not much better
The search field and button are not well organized
![form](https://cloud.githubusercontent.com/assets/2241324/18595910/c1abff42-7c14-11e6-89ae-5a6cab44fb08.jpg)
![orphanfile](https://cloud.githubusercontent.com/assets/2241324/18595911/c1b04822-7c14-11e6-83b0-8dddd78791b4.jpg)
![profile](https://cloud.githubusercontent.com/assets/2241324/18595913/c1b1080c-7c14-11e6-9fce-f60cd25c10ca.jpg)
![userview_search](https://cloud.githubusercontent.com/assets/2241324/18595912/c1b0a678-7c14-11e6-964a-41f38bf4df39.jpg)

**Comment by ignacionelson** [comment]
Fixed, can you check again please?
Also, what would you do with the search box and other controls on mobile?

One option is to have an icon for each form, and have them all closed by default. So you can open/close by clicking each icon.

**Comment by lenamtl** [comment]
I will check what I have done with my previous template and let you know.

Also a quick tips for tabs and button, what I usually do is to display an Icon on small device otherwise words are too long especially french ... so depending of screen size I show text OR display an icon
 see http://getbootstrap.com/css/#responsive-utilities

**Comment by lenamtl** [comment]
The logo on login page should be center, now it is align left
