### ISSUE TITLE
projectsend site quit working?

### ISSUE THREAD

**Issue by ichbas** [ignacionelson/ProjectSend#19]
So, I am not sure why, but the site just quit working. The login page is viewable, but afteri login with anyone (admin or user or client) it just shows the top banner and dies after the <div id="main">..

Any ideas on how to fix this?

**Comment by wdmtech** [comment]
Hi @ichbas, have a look in your PHP error logs as a first step. Without being able to access the site or view your code, there's no way for anyone to find out what's wrong (could be code/bug/configuration/any combination of these!).

**Comment by ichbas** [comment]
I'm on shared hosting, so i don't have access tot he PHP error logs. I recently moved to a new hosting company and the exact same thing is happening on the new server as well.
