### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#190]
**1 -** I have translated the french files from transiflex and download the files today.
In social media settings drop down Yes & No  are not into in the french po file , they appear in english only.

This is because it is plain text not using the 
`<?php _e('Yes','cftp_admin'); ?><?php _e('No','cftp_admin'); ?>`
To fix it on option.php
```
<option value="1" <?php echo (GOOGLE_SIGNIN_ENABLED == '1') ? 'selected="selected"' : ''; ?>><?php _e('Yes','cftp_admin'); ?></option>
<option value="0" <?php echo (GOOGLE_SIGNIN_ENABLED == '0') ? 'selected="selected"' : ''; ?>><?php _e('No','cftp_admin'); ?></option>

```
**2 -** It seems that pupload language file is not loaded if not set to english, ie french

I can see this comment but the code snippet is not working for french .

_Load a plupload translation file, if the ProjectSend language
on sys.config.php is set to anything other than "en", and the
corresponding plupload file exists._

Any clue on how to fix this

3- Missing string in fr

Get a new password
Set new password
File not found

This present en POT but not in fr
Quick fix
We can update the fr.po with POT using PoEdit

**Comment by ignacionelson** [comment]
The problem is that the po files on r754 are not updated. They are the same as r609.
My mistake :(

**Comment by ignacionelson** [comment]
Ok, I have updated the .po files on 5be4240
Ideally there would be some kind of official repository for translations from where you could download new ones through the admins interface.
And an automatic version control for the loaded translation files.

A huge task...

**Comment by lenamtl** [comment]
yes huge task

I'm still looking for a solution for pupload translation...

**Comment by ignacionelson** [comment]
Just fixed it on f13d6ff

**Comment by ignacionelson** [comment]
Oh, made a mistake on that commit. Fixed it now.

**Comment by lenamtl** [comment]
This seems to be possible to integrate Transiflex with Git.
http://docs.transifex.com/integrations/best-practices/
