### ISSUE TITLE
English is the source, how to fix it?

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#191]
I'd like to dissociate en.po from the source language, in PO Edit there is a way to fix that, 
any recommendation for the settings?

![source](https://cloud.githubusercontent.com/assets/2241324/18615989/8b482386-7d81-11e6-9c04-340818f5c2c8.jpg)

![sourcefixit](https://cloud.githubusercontent.com/assets/2241324/18615999/b28efb18-7d81-11e6-9c36-76915984ae2a.jpg)

**Comment by ignacionelson** [comment]
I'm sorry, I didn't understand the issue.
en.po is there so it can be used to correct errors or customize some phrases without changing the language.

**Comment by lenamtl** [comment]
If I edit the en.po and update en.mo
Do  I need to also edit the corresponding string or not?
example`<?php _e('All activities','cftp_admin'); ?>`

**Comment by ignacionelson** [comment]
No, you don't need to edit the string on the php file. It will get replaced like it would with any other language :)

**Comment by lenamtl** [comment]
Ok I just don't know why I'm having this alert warning on en.po, do you have the same alert?
I'm using the latest poedit version for windows.

**Comment by ignacionelson** [comment]
Yes, it happens to me to, I don't know why but doesn't seem to cause any problems for now.

When editing the po file, go to Catalog -> Update from POT file

**Comment by lenamtl** [comment]
Ok that a good idea thanks
