### ISSUE TITLE
Error Strict standards: Declaration of PDOEx::prepare() 

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#192]
I have enable error display` error_reporting(E_ALL);` in sys.vars.php

I'm having thid error on all the pages:
_Strict standards: Declaration of PDOEx::prepare() should be compatible with PDO::prepare($statement, $options = NULL) in ...projectsend\includes\classes\database.php on line 29_

**Comment by ignacionelson** [comment]
Maybe PDOEx shouldn't be enabled by default, as it's for debugging only.
I'll change that.

**Comment by ignacionelson** [comment]
Done on 24e6382.
Anyway, hiding the message is not a solution to the problem. I'll keep investigating.
