### ISSUE TITLE
Status Filtrer on manage-file doesn't work

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#193]
Hidden and visible filter is not working on manage-files.php

**Comment by ignacionelson** [comment]
Fixed
I have also updated the file on the r754 version, so future downloads include the patch. It would have been overkill to make a new release for this change only.

**Comment by lenamtl** [comment]
Could you give me the code so I can do manual fix

**Comment by ignacionelson** [comment]
Copy the file from here: https://github.com/ignacionelson/ProjectSend/blob/e1cf519007cc97de417e27bdad1008316da44278/manage-files.php

**Comment by lenamtl** [comment]
Thanks a lot
