### ISSUE TITLE
Brand logo on log in page

### ISSUE THREAD

**Issue by SpudR** [ignacionelson/ProjectSend#199]
Path is wrong if in subdirectory (image placeholder only shown).

Path current;y domain/img/custom/logo
Should be domain/**subfolder**/img/custom/logo

**Comment by lenamtl** [comment]
Hi this is not a real bug
you need to change the setiings
go to option - thumbnail and check the checkbox of **Use file's absolute path**

**Comment by SpudR** [comment]
Worked fine in previous version...

**Comment by lenamtl** [comment]
is this ok since you have check the checkbox?

**Comment by SpudR** [comment]
It does indeed work with the checkbox enabled :)

**Comment by lenamtl** [comment]
That could be a default setting
