### ISSUE TITLE
Updated, Still showing old version

### ISSUE THREAD

**Issue by expphoto** [ignacionelson/ProjectSend#20]
I've uploaded the new files for the latest version. I login, and it still tells me to update.

**Comment by ignacionelson** [comment]
Sorry, the download didn't include the correct version number. It has been
fixed.
Please re download the new version or just the file sys.vars.php


*IGNACIO NELSON*
WordPress specialist
Buenos Aires, Argentina

*Mobile:* (54) 11 31 52 59 31
http://about.me/ignacionelson <http://subwaydesign.com.ar>

2015-05-25 22:14 GMT-03:00 expphoto <notifications@github.com>:
