### ISSUE TITLE
Filter on manage-file dissappear 

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#201]
I'd know why but the filter is no more displaying on manage-file.php

if($current_level != '0' && $results_type != 'global') {

if a change it to 
if($current_level != '0') {

I can see it 
What $results_type != 'global' mean?

**Comment by ignacionelson** [comment]
Global means that the page is not filtering by client, group or category. It tries to show all the files.
It's defined on line 33 and it's the default setting for the query.
If you are deleting it and it works, it means that somewhere it's getting overwritten.

**Comment by lenamtl** [comment]
What can it be do you have the same problem on your installation?
This occurred since the last update, it was ok before as I open a bug regarding this.
Just to make sure it not my code, I have test it on vanilla install and same problem.

**Comment by lenamtl** [comment]
I have fixed by updating the file.
I was testing using two install to compared and because a cache issue that gave me the impression that the bug was also on new install.
Sorry my bald.
