### ISSUE TITLE
r754 MYSQL error 

### ISSUE THREAD

**Issue by eyeobticeo** [ignacionelson/ProjectSend#203]
I just test to install r754 
my older version r609 working fine

![unbenannt](https://cloud.githubusercontent.com/assets/21228058/18644896/5fa8aaea-7eab-11e6-8322-5da6c1c0d657.PNG)

**Comment by lenamtl** [comment]
Make sure Mysql PDO driver is enabled
Which PHP version are you using?

**Comment by eyeobticeo** [comment]
The PDO driver is enabel 
I try it with the PHP version 7.7 5.6 5.5

**Comment by cdoepmann** [comment]
Same issue here with PHP 5.4 (Debian Stable) running in php-fpm behind nginx. MySQL version is 5.5. The problem occurs on fresh install. PDO is enabled, of course.

**Comment by cdoepmann** [comment]
By running `git bisect`, I found that the bug was introduced in commit b81098679a0e2ce97fd39f467db2d66514edda10,

**Comment by cdoepmann** [comment]
Seems like this change silently started requiring MySQL >= 5.6.5.

> Changes in MySQL 5.6.5 (2012-04-10, Milestone 8)
> 
> Previously, at most one TIMESTAMP column per table could be automatically initialized or updated to the current date and time. This restriction has been lifted. Any TIMESTAMP column definition can have any combination of DEFAULT CURRENT_TIMESTAMP and ON UPDATE CURRENT_TIMESTAMP clauses. In addition, these clauses now can be used with DATETIME column definitions. For more information, see Automatic Initialization and Updating for TIMESTAMP and DATETIME.
