### ISSUE TITLE
How can we disable file size calculation to reduce the load?

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#221]
How can we disable file size calculation to reduce the load on files

**Comment by pmclain** [comment]
You could change line 669 in manage-files.php to

if ( false ) ) {

A little hacky, but it should do the job.

**Comment by ignacionelson** [comment]
Real pagination should fix all of this problems :/

**Comment by lenamtl** [comment]
Thanks pmclain :)

Yes I know, but I need something for next week I don't have much time left...

**Comment by lenamtl** [comment]
Size and extension could be saved in db instead of checking on load too.

**Comment by lenamtl** [comment]
With the latest package and real pagination this is fixing the problem.
Thanks for the great work.
