### ISSUE TITLE
Public download link missing token if viewed directly after upload.

### ISSUE THREAD

**Issue by njuergens** [ignacionelson/ProjectSend#235]
Hey,

I just noticed that with r754 you can set a file upload to 'public' immediately after upload (which is great)

But if you then hit the blue 'public' button immediately afterwards an incorrect link (without the token) is shown. If I go to files->manage files afterwards the link is correct, so this is only after the upload.

See this screenshot:
![projectsend missing token](https://cloud.githubusercontent.com/assets/5329520/18834420/07c901a8-83f6-11e6-9130-d3eab7d5cf71.png)

Thanks!

**Comment by ignacionelson** [comment]
Fixed, thanks for your report!!!
