### ISSUE TITLE
Impossible to install ProjectSend

### ISSUE THREAD

**Issue by Christof1** [ignacionelson/ProjectSend#239]
Hi!

I've tried to install ProjectSend but without success.
I downloaded the newest file from the website, extracted the file and put it on the server. I changed the sys.config.sample.php by editing the database connection details and the name of the file.

After having sent the form of /install, I get the following error message:
<img width="617" alt="bildschirmfoto 2016-09-29 um 22 29 29" src="https://cloud.githubusercontent.com/assets/20914417/18971882/1772e0d0-8697-11e6-8325-45aaf63361a9.png">

Same error occurs on two different servers.

Any idea of how to solve the problem?

Thank you in advance!

Christof

**Comment by lenamtl** [comment]
Have you tried with the latest package?
I know there was a fix about Timestamp few days ago.

**Comment by eyeobticeo** [comment]
The website Version have Not implement the fix use the GITHUB version

**Comment by lenamtl** [comment]
ok I saw a label 10 days ago about this so I thought it was fixed

**Comment by ignacionelson** [comment]
I have replaced the installer on the r754 download from the website. It should be ok now.

**Comment by Christof1** [comment]
Yes, I also figured out the problem and I've installed the older web version because I fixed the problem manually. This is also ok, isn't it? Or has the newer version also other improvements?

Thank you for your quick responses!
