### ISSUE TITLE
Image preview doesn't work

### ISSUE THREAD

**Issue by Christof1** [ignacionelson/ProjectSend#247]
Hi again!

If I open the page with the file overview, I should get a image preview. Nevertheless, that doesn't work.

Some thumbnails loaded but I couldn't see them. Then I found out that the loaded thumbnails were on the other page. (Only the first 10 pictures get shown then I have to navigate to another page and there I can see the thumbnails)

I figured out the problem - because there are more than 200 photos, the server memory gets reached.

At some point it says:

> The website is temporarily unable to service your request as it exceeded resource limit. Please try again later.

If I try to open the file it says:

> Fatal error: Allowed memory size of 98566144 bytes exhausted (tried to allocate 24576 bytes) in [...] on line 1093

Is it possible to only load the first site, so the first ten thumbnails, and if the user navigates to another page (so the next 10 images), it will load the next 10?

Or to make a pause after some thumbnails and then continue loading?

Or do you have any other idea of how to solve the problem that the user gets the thumbnails and I don't reach the server limits?

Thank you in advance!

Christof

**Comment by Christof1** [comment]
I have to add that I keep getting the error although I changed the max size of the thumbnails to 30x30 and the JPEG quality to 20. Hence I can't see any sense in making the thumbnails even smaller, since I also expect to get a lot more pictures than the 200 ...

**Comment by lenamtl** [comment]
Hi, have you tried the latest version as there is a real pagination now on file list, so it only load a few file at the time.

**Comment by ignacionelson** [comment]
The new table and pagination class is not yet on the template, so it wont make any difference right now. Ill try to solve it this week

**Comment by Christof1** [comment]
In spite of the memory size warning, I get another warnings.

I recognized that before too, but I thought that this was due to the memory size limit.

But now I just loaded 10 pictures and afterwards 10 and so on. Although the memory limit wasn't reached, not every picture got shown.

Here are the errors:

> Warning: imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Invalid SOS parameters for sequential JPEG in /home/.sites/144/site9073009/web/bilder/includes/timthumb/timthumb.php on line 1093 Warning: imagecreatefromjpeg(): '/home/.sites/144/site9073009/web/bilder//upload/files/20160927_232917.jpg' is not a valid JPEG file in /home/.sites/144/site9073009/web/bilder/includes/timthumb/timthumb.php on line 1093

> Warning: imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Corrupt JPEG data: premature end of data segment in /home/.sites/144/site9073009/web/bilder/includes/timthumb/timthumb.php on line 1093 Warning: imagecreatefromjpeg(): '/home/.sites/144/site9073009/web/bilder//upload/files/20160922_082402.jpg' is not a valid JPEG file in /home/.sites/144/site9073009/web/bilder/includes/timthumb/timthumb.php on line 1093

And some sites on which the thumbnails should get shown were just blank.

**Comment by Christof1** [comment]
Although I'm sure that you can do it better than me, I'd like to recommend to you realizing the new table with datatables.net with an ajax call which is easy and normally works perfectly.

By the way, is it possible that the above mentioned error has a relation to the size of the original picture? In my case no thumbnails of pictures with about 5 to 8 MB were shown. (I only found one picture with 7 MB of which the thumbnail was shown)

**Comment by Christof1** [comment]
Are there any news?

**Comment by ignacionelson** [comment]
Sorry, not yet. I've moved this week and I'm catching up with emails and work. I'll get to work on this on the weekend!

**Comment by ilackskills** [comment]
@Christof1 what version of PHP are you running?

**Comment by Christof1** [comment]
@ilackskills I recently updated to PHP 7.

**Comment by Christof1** [comment]
@ignacionelson Because I was interested in doing that, I have already implemented the feature of loading the table asynchronously and showing only the current ten (or twenty, as the user wants) rows.
If interested, just let me know.

**Comment by ilackskills** [comment]
@Christof1 

includes/timthumb/timthumb.php

there is a memory cap in 

line 28 `if(! defined('MEMORY_LIMIT') )				define ('MEMORY_LIMIT', '30M');							// Set PHP memory limit`

File size cap in
line 41 `if(! defined('MAX_FILE_SIZE') )				define ('MAX_FILE_SIZE', 20971520);						// 10 Megs is 10485760. This is the max internal or external file size that we'll process.  
`
...

Have you changed any of these setting to accommodate your needs?

**Comment by ilackskills** [comment]
@Christof1 limitations in the timthumb.php file?

**Comment by Christof1** [comment]
I've just changed the memory limit to 90M and the Max_File_Size From 10485760 to 30485760.

Nevertheless, only the half of the thumbnails loads. The error messages vary - if a picture doesn't load, I will get one of these three messages:


> Fatal error: Allowed memory size of 98566144 bytes exhausted (tried to allocate 20480 bytes) in /home/.sites/144/site9073009/web/bilder/includes/timthumb/timthumb.php on line 1093

Although I only load ten thumbnails at the same time. On one page, for instance, there are 4 pictures that can't load with that error message, followed by two pictures that can load and another 4 thumbnails that don't get shown.


> Warning: imagecreatefromjpeg(): gd-jpeg, libjpeg: recoverable error: Corrupt JPEG data: premature end of data segment in .../includes/timthumb/timthumb.php on line 1093 Warning: imagecreatefromjpeg(): '...//upload/files/20160922_082402.jpg' is not a valid JPEG file in .../includes/timthumb/timthumb.php on line 1093


And some bad requests - no error message:

>  the server responded with a status of 400 (Bad Request)

**Comment by ilackskills** [comment]
@Christof1 from my understanding each of the thumbs are processes separately.

please provide me the specs of one of the files that do not load.

Files size
extension
width
height

1500x1500 is pretty small for a 10mb file, one guess is on issue is your width and height are maxed per the timthumb.php file
Line 50
```
if(! defined('MAX_WIDTH') )					define ('MAX_WIDTH', 1500);								// Maximum image width
if(! defined('MAX_HEIGHT') )				define ('MAX_HEIGHT', 1500);							// Maximum image height
```

**Comment by Christof1** [comment]
Like for instance, picture "p1010306.jpg".

Has on my disk the following specs:

<img width="266" alt="bildschirmfoto 2016-10-09 um 22 16 02" src="https://cloud.githubusercontent.com/assets/20914417/19223357/0f0a9af8-8e6e-11e6-9a82-0118a74aab33.png">

And the thumbnail should load with width 80 and quality 80.
The error is about the memory size.

**Comment by ilackskills** [comment]
well for one your exceed the default width and default height for the images processed by timthumb.php, you need to increase these to accommodate your needs, try increasing 

Example of my thumbnails after changing the config
![image](https://cloud.githubusercontent.com/assets/15673241/19225462/db2f7cf4-8e62-11e6-83b3-e728d0507fdf.png)

the first images specs are:
![image](https://cloud.githubusercontent.com/assets/15673241/19225480/1051a45c-8e63-11e6-8559-ca45d8fdfd4a.png)

can you send a print of the error?

**Comment by Christof1** [comment]
I think I've adapted the timthumb.php correctly, haven't I?

<img width="1257" alt="bildschirmfoto 2016-10-10 um 14 25 56" src="https://cloud.githubusercontent.com/assets/20914417/19236130/052241d4-8ef6-11e6-8e82-c3b9ca74d07c.png">

But I nevertheless get the same error.

<img width="1222" alt="bildschirmfoto 2016-10-10 um 14 26 12" src="https://cloud.githubusercontent.com/assets/20914417/19236136/106fc9da-8ef6-11e6-8336-8d0034b008bf.png">
<img width="871" alt="bildschirmfoto 2016-10-10 um 14 26 40" src="https://cloud.githubusercontent.com/assets/20914417/19236135/106e97ea-8ef6-11e6-80ad-0ea7dc5de0fc.png">

Concerning the corrupt jpeg, I will report you later on.

**Comment by ilackskills** [comment]
@Christof1 

are you still getting this error as this one should be cleared not the config has been changed

> Fatal error: Allowed memory size of 98566144 bytes exhausted (tried to allocate 20480 bytes) in /home/.sites/144/site9073009/web/bilder/includes/timthumb/timthumb.php on line 1093

**Comment by Christof1** [comment]
@ilackskills Yes

**Comment by Christof1** [comment]
@ilackskills I installed ProjectSend again with the current github version and a new database. I uploaded 6 pictures of which the thumbnails didn't work and the result is again the same.

> Fatal error: Allowed memory size of 98566144 bytes exhausted (tried to allocate 8192 bytes) in /home/.sites/144/site9073009/web/storage/includes/timthumb/timthumb.php on line 1093

The same error before changing the timthumb.php again and afterwards.

**Comment by Christof1** [comment]
Any suggestion?

Should I send you a picture of which the thumbnail doesn't work?

**Comment by ilackskills** [comment]
is it possible to set up a dummy account with that picture in it?

**Comment by Christof1** [comment]
@ilackskills How do you mean that?

**Comment by ilackskills** [comment]
can you make a temp client account and provide me access so i can see what is going on, this is pretty odd.

**Comment by Christof1** [comment]
Yes, sure.

I assigned your demo account one file, I hope you can figure out the problem.

[Link to my website](http://www.klassen-battle.at/bilder2)

Sign in using your username on github for the username as well as for the password.

**Comment by ilackskills** [comment]
Here is my demo [Link to my website](http://smarthandsonsite.net/ )
Sign in using your username on github for the username as well as for the password.

I have uploaded the image i downloaded from your site and it displays fine, please ignore some of my modifications, but you see the image in question works fine.

![image](https://cloud.githubusercontent.com/assets/15673241/19443792/8b179606-9453-11e6-9c20-4b51fdc06e73.png)

I have tried uploading a copy of the file i downloaded from your site back to your site but it is not taking, do you have uploads disabled?

**Comment by Christof1** [comment]
@ilackskills Well, thank you. 

I have just changed the timthumb.php to match exactly yours.
Now the thumbnail of that picture did work - perfect!!!

BUT as soon as I have assigned to your account more than just a few files, some thumbnails won't be shown.
By the way, I noticed that some errors occurred on uploading using your demo account (uploading is activated and works fine). Please, just have again a look on my site and if you want to reproduce the errors, feel free to upload images.

**Comment by ilackskills** [comment]
@Christof1  I uploaded my files fine, they preview fine, your files on the other hand are corrupt.

![screenshot_20161017-173859](https://cloud.githubusercontent.com/assets/15673241/19458325/ec8ddfde-9490-11e6-8803-d5f8aaa5c7e7.png)
![screenshot_20161017-173849](https://cloud.githubusercontent.com/assets/15673241/19458324/ec8ccf4a-9490-11e6-86a2-9f98a39bc133.png)
![p1010412](https://cloud.githubusercontent.com/assets/15673241/19458322/ec89d93e-9490-11e6-9513-45731a75baf5.jpg)
![p1010422](https://cloud.githubusercontent.com/assets/15673241/19458323/ec8bcdfc-9490-11e6-8b5e-e4ac98eaa358.jpg)

**Comment by Christof1** [comment]
@ilackskills I have taken those pictures with the same camera with which I have taken the photos that work.

Anyway, do you have any idea of what I can do about that?

**Comment by ilackskills** [comment]
the files are corrupting on upload is my guess, how I have no idea, its odd how you have 2 files combining into one.

**Comment by Christof1** [comment]
@ilackskills If I upload the picture using FTP and assign it afterwards, it will work fine. See p1010317 and p1010317_2.

So, yes, there is something wrong with the upload.

**Comment by Christof1** [comment]
@ilackskills These are the errors I could make a screenshot of while uploading the corrupt pictures again.

<img width="887" alt="bildschirmfoto 2016-10-18 um 20 44 13" src="https://cloud.githubusercontent.com/assets/20914417/19491711/4b86f488-9574-11e6-9d8f-1687c3386f57.png">
<img width="885" alt="bildschirmfoto 2016-10-18 um 20 44 19" src="https://cloud.githubusercontent.com/assets/20914417/19491712/4bb66ae2-9574-11e6-8785-be1daa2b6fd4.png">
<img width="459" alt="bildschirmfoto 2016-10-18 um 20 44 25" src="https://cloud.githubusercontent.com/assets/20914417/19491713/4bbac4a2-9574-11e6-8302-ae67cc1729d7.png">

**Comment by ilackskills** [comment]
I think it is a connection issue between you and your server, is this a in House server or rented space?

**Comment by Christof1** [comment]
@ilackskills

Rented web space.

**Comment by Christof1** [comment]
@ilackskills So, what can I (or the web hoster) do in order to fix that?

**Comment by ilackskills** [comment]
I had no issues uploading to your server, so it looks like it is an issue between you and your server, maybe try another internet connection?

**Comment by Christof1** [comment]
Ok, then it's no problem since I can upload via FTP and the users can upload their pics without any problem.

If there were a problem again, I would tell you, ok?

Anyway, thank you very, very much for your help!!!

**Comment by ilackskills** [comment]
please close this if issue is resolved.
