### ISSUE TITLE
Can't install [Wizard]

### ISSUE THREAD

**Issue by vwhissell** [ignacionelson/ProjectSend#250]
Doesnt detect mysql server on localhost even if 100% sure that mariadb is working and well configured.

**Comment by vwhissell** [comment]
php is well installed also. CentOS 7 LAMP

**Comment by vwhissell** [comment]
That's what I used:
https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-centos-7

**Comment by lenamtl** [comment]
does pdo driver is installed?
what do you get on install page?
any error, message, warning?

**Comment by vwhissell** [comment]
does pdo driver is installed?
**yes**
what do you get on install page?
**I get the wizard**
ProjectSend setup

any error, message, warning?
**no, but a **red** icon next to:
Host
Database name
Username
Password
Table prefix**

**Comment by lenamtl** [comment]
Ok so when you filled and verify those fields, click on the **verify button** at the bottom of the form they should turn green after. Then the verify button will be changed to  Install or something like that then click on it.
If the fields stay red, on the page right click check in the source code to see if there any errors...

**Comment by ilackskills** [comment]
Do you have a database and db user created, did you use the info from that db?

**Comment by ignacionelson** [comment]
The config file maker is full working now. Ill close this issue
