### ISSUE TITLE
Google Social Login suddenly not working / SSL

### ISSUE THREAD

**Issue by hailthemelody** [ignacionelson/ProjectSend#252]
Hi all,

Not sure exactly what I've done, or how exactly to troubleshoot it. I had the Google Social Login functionality working, and the following day it was not. Specifically, when enabled, the login page now stops generating HTML after `<div id="main">`, rendering it effectively useless.

The only change I can think of was that I went from a self-signed SSL cert to one generated via Let's Encrypt. I'm not sure where to check for errors, and `/var/log/apache2/error.log` only has this to say:

```
[$DATE] [mpm_prefork:notice] [pid 1301] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.19 OpenSSL/1.0.1f configured -- resuming normal operations
```

Perhaps I have also 'deactivated' the Google Project somehow? All looks good and fine on that end, though I don't know where to check that it's 'communicating' properly with ProjectSend. As a test, I would offer to retract from using Let's Encrypt to a self-signed SSL cert but it's now a production system.

**Comment by lenamtl** [comment]
Have you fixed this?

**Comment by hailthemelody** [comment]
I did a fresh install, switched to my branch and it's working fine. I must have borked something somewhere, even though I tried forcing a pull pre-fre-install.
