### ISSUE TITLE
Category List/Add/Edit 

### ISSUE THREAD

**Issue by alevic** [ignacionelson/ProjectSend#253]
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/public_html/projectsend/categories.php:1) in /home/public_html/projectsend/sys.vars.php on line 12

**Comment by lenamtl** [comment]
What are the steps to reproduce?

**Comment by alevic** [comment]
1. Download and install the master version today.
2. Login as admin.
3. Go menu Files > Categories

**Comment by lenamtl** [comment]
Are you using PHP 5.5+
I saw another user having an issue on this page with PHP 5.4

**Comment by dabenzel** [comment]
Using PHP 7, having same Issue :smile:

**Comment by MaharishiCanada** [comment]
I had the same issue. It just an extra tab before the php tag in categories.php.

**Comment by lenamtl** [comment]
There is a fix see https://github.com/ignacionelson/ProjectSend/pull/261
