### ISSUE TITLE
Wrong letter encoding in german file descriptions

### ISSUE THREAD

**Issue by MHerrERC** [ignacionelson/ProjectSend#255]
ProjectSend r609
PHP-version 5.4.45
Server: Apache
tested with Firefox 49.0.1, Edge 25.10586.0.0, Chrome 53.0.2785.143m

German special chars (Umlaute) (ä ö ü Ä Ö Ü) in file desription are not correctly displayed. They are displayed as &auml, &ouml, &uuml, &Auml, &Ouml, &Uuml.

Best regards
Markus Herrmann

**Comment by lenamtl** [comment]
Please check this #182 for a complete solution.
I'm closing this let me know if you have any question.
