### ISSUE TITLE
Suggestion: Update Bootstrap to version 3+

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#26]
Update Bootstrap to the latest version 3.3.4

**Comment by lenamtl** [comment]
I have started the upgrade.
This is going to be a lot of work.
jQuery and some other JS scripts need to be upgraded or changed.

**Comment by ignacionelson** [comment]
Indeed, it will be a lot of work!
Also, you need to make sure to update (if needed) a couple of bootstrap addons: datepicker and spinedit.

**Comment by lenamtl** [comment]
Hi, 

I have 60% done...
Like you said this is a lot of work....

**Comment by lenamtl** [comment]
Hi just an update, I have 90% done

**Comment by lenamtl** [comment]
Almost ready

**Comment by ASardar** [comment]
Has the update to Bootstrap 3+ been released?

**Comment by lenamtl** [comment]
Not yet, I have to update all page to add all security fixes.
Hope I will have the time to complete it soon
