### ISSUE TITLE
Is it normal that I have no style when I use https to login?

### ISSUE THREAD

**Issue by MaharishiCanada** [ignacionelson/ProjectSend#260]
After the login, I get a mixed content error and all the css files are blocked by the browser (Firefox). When I look at the source file, I see that all the css URLs have an http, not an https, and that is why they are blocked. Why do you allow login on a non secure page anyway?

**Comment by MaharishiCanada** [comment]
Nevermind. I changed the base_uri to https:// ...

**Comment by xoroz** [comment]
I have the same problem.
Sorry where it the base_uri defined!?!

**Comment by lenamtl** [comment]
in sys.vars.php

You may want to check some post about SSL and htttps
https://github.com/ignacionelson/ProjectSend/issues/65

**Comment by xoroz** [comment]
got it working!!! Lost few hours on this today :( 

I wonder how base_uri was auto configured? 
Could it be because the install was on http and latter I added https

**Comment by lenamtl** [comment]
This file have a lot of setting so always refer to it.
