### ISSUE TITLE
All logins suddenly stopped working

### ISSUE THREAD

**Issue by risottto** [ignacionelson/ProjectSend#264]
I've been using projectsend to send files to clients for several years with almost no issues for several years, but all the sudden last night for no reason at all, ALL logins do nothing but reload the login page! if i enter the wrong password it does tell me that the credentials are incorrect, however when i put in the correct password (either for me as the admin or for ANY client), the page just reloads and clears all the fields. I did a password reset for my account, which it successfully sent an email link for, but I still can't log in, nor can ANY clients!?

is there any way to troubleshoot this other than completely wiping out the entire installation and killing all me accounts and files?

**Comment by ignacionelson** [comment]
Sorry to see that you are having this problem!
What version are you using?
Are you using any other scripts on your server that use the php session feature? (probably anything in php that requires a login).

**Comment by lenamtl** [comment]
Contact your hosting provider ans ask if they have update PHP or Mysql version...

**Comment by ilackskills** [comment]
the accounts wont be deleted as long as you do not drop the DB, check file permissions. so php seems to be working and sql seems to be working, has the hosting provider changed software?

**Comment by risottto** [comment]
Thanks you all for the quick replies, i am running 754, I checked my server and re-initiated the PHP version to 5.4.43, (it had mysteriously dropped to 5.2) ... then re-uploaded the same 754 version via FTP .. seemed to fix the problem!

**Comment by ilackskills** [comment]
@ignacionelson  issue resolved.
