### ISSUE TITLE
manage-files.php shows "There are no files for this client."

### ISSUE THREAD

**Issue by ilakskill** [ignacionelson/ProjectSend#265]
manage-files.php shows "There are no files for this client." if you delete all files from a selected page even if you have files on pages before that

**Comment by lenamtl** [comment]
could you write the step to reproduce

**Comment by ilackskills** [comment]
manage-files.php?page=3

![image](https://cloud.githubusercontent.com/assets/15673241/19484582/b06128da-951d-11e6-9aef-7672fc52877f.png)

delete the files on that page

![image](https://cloud.githubusercontent.com/assets/15673241/19484606/c4d37ed0-951d-11e6-9cba-f894cc480519.png)

if you are on the last page of the list and delete all the files it tells you you have no more files.

**Comment by lenamtl** [comment]
Ok no more file only on this page...
I guess this need to be update to work with the new pagination system
