### ISSUE TITLE
Please wait while your download is prepared does not go away after zip is downloaded

### ISSUE THREAD

**Issue by ilackskills** [ignacionelson/ProjectSend#266]
Please wait while your download is prepared does not go away after zip is downloaded, if you click off the div or click the 'X' it goes away but it does not go away on its own.

![image](https://cloud.githubusercontent.com/assets/15673241/19490166/b7997a42-9533-11e6-8035-c081021be2b3.png)

![image](https://cloud.githubusercontent.com/assets/15673241/19490129/8ac2af84-9533-11e6-9e83-cf0993830073.png)

**Comment by lenamtl** [comment]
This is a very old bug, I have already create a post on this
see #205

**Comment by alioztr** [comment]
i can not see your post for this bug

**Comment by lenamtl** [comment]
See bug 205 https://github.com/ignacionelson/ProjectSend/issues/205

This is an old bug that need to be fixed, it was present since the first versions of PS....long time ago...
