### ISSUE TITLE
Can we make a forum for this project?

### ISSUE THREAD

**Issue by ilackskills** [ignacionelson/ProjectSend#267]
Can we make a forum for this project for support and other questions that are not issue related.

**Comment by ignacionelson** [comment]
There was phpbb a forum but it got pretty bad with spam really quick and the solutions I've found didn't make it stop.
I should give it a go with another software.

**Comment by ilackskills** [comment]
If it was me I would, you would probably get more participation, and being this is open source and most likely not getting much money from it you could at least draw in a little ad revenue.  Just a thought.

**Comment by lenamtl** [comment]
I't's not a bad idea, but to my opinion only one place like Github is better.
When too much place like it was in the past, it was no good, the information (fixes) get lost and not regrouped. 
And user will still ask question and post fixed on both places.
Also it double the job as we have to check more than one place.

There are places like Stackoverflow to find answer about server configuration for example.

**Comment by ilackskills** [comment]
I understand but like myself I make modifications to the software that might benefit the public but because I do not use github much I still do not fully understand how to use it so that I can offer my changes, if there was a forum people show off some of the modifications they have done and help that way.
