### ISSUE TITLE
Clients not able to update password in their accounts

### ISSUE THREAD

**Issue by supersunken** [ignacionelson/ProjectSend#27]
Clients not able to update password in their accounts after upgrading to r572. The page does not load. Hitting Enter key a second time reloads the page but the password is not saved.

**Comment by ignacionelson** [comment]
Fixed.
Line 78 of clients-edit.php changed to

if ($client_id != CURRENT_USER_ID) {

**Comment by supersunken** [comment]
Thank you for the quick fix.

**Comment by ignacionelson** [comment]
r582 includes this fix. Closing the issue now.
