### ISSUE TITLE
free version and paid version of projectsend ?

### ISSUE THREAD

**Issue by ericbeaucourt** [ignacionelson/ProjectSend#271]
I find projectsend one of the best file managers I tested.
There have to be made a number of improvements as demonstrated by the reactions
This requires of course the necessary time, especially if this happens all voluntary.
Is it a good idea to make two versions: an open source free version and a paid version, where the improvements can be made much faster?
If everything must be done in free time then this is not evident.

**Comment by lenamtl** [comment]
This is a free opensource project.

You can make a donation if you want
http://www.projectsend.org/donations/

**Comment by ilackskills** [comment]
I'm not sure a paid version is possible due to the code base.
