### ISSUE TITLE
Group Manager

### ISSUE THREAD

**Issue by dannyulman** [ignacionelson/ProjectSend#273]
Is there a way to make group managers
I have a few groups.
I want a login account that can login and see all the files that belong to clients in a certain group.
But I don't want the clients in this group to be able to see files of the other clients in the same group.
Only the group admin should be able to see the files in this group

**Comment by lenamtl** [comment]
Client will only the file they own or the file of the group they belong

**Comment by dannyulman** [comment]
Will all the clients be able to see the other clients files in the group or can I make it so there is only 1 person that can see all files in the group but nobody else.

**Comment by lenamtl** [comment]
Most of the time group will have more than one client, and will be use to send file to be visible from all client of the group.

So you can assign to one or several client or you can assign the file to one or several group.

Let say you create a group Testers, John Doe and Jane Doe are into tester group.
When you add a file to this group, both will see the file, other Client that are not into the group will not see the file.

If you upload a new file and only want to be visible by Jane Doe just assign it to this client (not to a group) so only Jane Doe will see it.
So if a file is assigned to a specific client it won't be visible from other group members.

You this is important to take your time and think how you want to manage your files and do some test prior to go live.
