### ISSUE TITLE
Upload email notification to client

### ISSUE THREAD

**Issue by dannyulman** [ignacionelson/ProjectSend#274]
Right now clients can receive an email if I upload a file to them
and also i get emails when a client uploads a file.
But is there an option for the client to be able to receive a confirmation email
as soon as their file is upload?

**Comment by dannyulman** [comment]
Also would like to be able to have notifications go to more than 1 email address per client.
And Also using same email for multiple clients would also be nice.
I have hospitals that have multiple clients uploading to us from multiple departments but use one email address.
The only thing that should have to be unique is the username.

**Comment by lenamtl** [comment]
Client don't need to receive an email when they upload a file, 
they will see their file in the backend asap as it is uploaded, I don't see any use for this.

This is not a good idea to have multiple client with same email address.
And this is not a good idea to have multiple email address for a client.
Both case are not best practice, and will cause several problems.

Imagine the problem when asking for reset password for example.
