### ISSUE TITLE
Clients can set expiration Date

### ISSUE THREAD

**Issue by dannyulman** [ignacionelson/ProjectSend#285]
when I check the box under client options that says "Clients can set expiration Date"
then I click update all options it is unchecked again when I click back into the client options.

**Comment by eyeobticeo** [comment]
This may happen if  the file includes/site.options.php does not include have the code

if (isset($options_values['clients_auto_approve'])) {
	define('CLIENTS_CAN_SET_EXPIRATION_DATE',$options_values['clients_can_set_expiration_date']);
}
which wersion you use and as you have it instaled

**Comment by dannyulman** [comment]
I have the code from version 757

**Comment by eyeobticeo** [comment]
As a New install ? Or update ?

**Comment by dannyulman** [comment]
an update.
I used the latest master.zip from github about a week ago and overwrote everything except the database and the database config file since its not included.

**Comment by eyeobticeo** [comment]
Thank you for your help I found my mistake and create a pull reqest #286

**Comment by eyeobticeo** [comment]
A Quick fix for now you can set in Database  tbl_options / last_update  = 757

**Comment by eyeobticeo** [comment]
@lenamtl i think we can close this Issue
