### ISSUE TITLE
Unable to complete install wizard on PHP5/Jessie

### ISSUE THREAD

**Issue by kylegordon** [ignacionelson/ProjectSend#288]
Hi,

After a clean install of Debian Jessie, with the following packages, I am getting PDOException exception errors after submitting the initial site configuration settings.

Debian Jessie, Apache 2.4, PHP 5.6
Packages : apache2 php5 php5-mysql php5-apcu php5-mcrypt php5-intl
Projectsend master from git

After installing the above packages, the fhe _apcu mcrypt intl pdo_mysql_ modules were all enabled with php5enmod, and php5dismod used to disable _mysqli mysql_

Apache isn't running, and is temporarily started with /usr/sbin/apache2 -D FOREGROUND

phpinfo() confirms the PDO Driver for MySQL is loaded.

However, the error persists, and can be seen at https://gist.github.com/kylegordon/f7bc8d161485e523d6ba127d7aba7c4c

Any thoughts? :-)

**Comment by lenamtl** [comment]
Are you using the latest PS version?

**Comment by kylegordon** [comment]
Sorry, I failed to mention that I'm using the latest clone from the master branch

**Comment by kylegordon** [comment]
I've altered my DockerFile to use r756 in exactly the same configuration, and it works as expected. Using the master branch from git causes this error.

The Dockerfile and startup script that I'm working on lives at https://github.com/kylegordon/ProjectSend just now.

**Comment by lenamtl** [comment]
This seems to be the same problem see
https://github.com/ignacionelson/ProjectSend/issues/179

**Comment by kylegordon** [comment]
So it is! I'd written off PHP7 support back then, but didn't know it's a problem that crept in with PHP5.6
