### ISSUE TITLE
Bug: Delete a non assigned file will delete another file

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#29]
Have one file that is not assigned, private, not expire on
manage-files.php
Select the file 
Select Delete
Click Proceed
Message delete with success appear, but the file is still in the list and in the folder.

If there are other assigned files on 
manage-files.php the next file get deleted from the list and the folder!!!

*Nice to have the system should display the file name in the confirmation message.

**Comment by ignacionelson** [comment]
Horrible bug!
The delete function is passing an ID which cannot be found on the relations table, and that's why the file is never found to be deleted.
Working on a fix now.

**Comment by ignacionelson** [comment]
Fixed

**Comment by lenamtl** [comment]
Thanks

**Comment by ignacionelson** [comment]
r582 includes this fix. Closing the issue now.
