### ISSUE TITLE
default home page

### ISSUE THREAD

**Issue by dannyulman** [ignacionelson/ProjectSend#290]
Is there a way after login to have it load manage-files.php instead of home.php

**Comment by lenamtl** [comment]
For which role?

**Comment by RickkeeC** [comment]
Moved to more current post 1214
Where in latest version?  Somewhere around here?  Or someplace else?
if ($login->status == 'success') {
$user = new \ProjectSend\Classes\Users($login->user_id);
ps_redirect($login->location);
