### ISSUE TITLE
Cloud Service: Download Zipped option not working

### ISSUE THREAD

**Issue by alioztr** [ignacionelson/ProjectSend#297]
please wait while your download is prepared' pop up, nothing ever happens, regardless if its 1 or several files selected.

I did try other help issues but nothing changed.

what should i do.

Thanks

**Comment by alioztr** [comment]
Which php version should i use for this script.

**Comment by lenamtl** [comment]
I'm using PHP 5.6.9 and it's working OK

**Comment by alioztr** [comment]
same version but not working. can you send me your process-zip-download.php

**Comment by lenamtl** [comment]
Make sure gzip installed...

Have you checked the phpinfo to make sure?

The problem you having is not related to code but to your server configuration
are you using local webserver, online webserver, is this a share hosting server or your own server?
Which OS etc.

Is the file is a very big one?

Check your server logs to see useful information about error or warning.

You can download process-zip-download.php from the PS code page
https://raw.githubusercontent.com/ignacionelson/ProjectSend/master/process-zip-download.php

**Comment by alioztr** [comment]
Same file, nothing changed.
gzip installed.
online web server.
cloud server.
no error message, but popup window wait and nothing download.
i don't know what should i do.

thanks.

**Comment by lenamtl** [comment]
I'm not sure what is your problem based on your title.... > Download Zipped option not working
Please specify which is you case.

Does the zip file download or not ?
Does the zip is corrupt?

If YES this is a configuration issue.

If the zip is ok and you are only referring to the animation that never end is a known issue and there is no fixed.
see https://github.com/ignacionelson/ProjectSend/issues/266
and 
https://github.com/ignacionelson/ProjectSend/issues/205

**Comment by alioztr** [comment]
https://cloud.githubusercontent.com/assets/15673241/19490129/8ac2af84-9533-11e6-9e83-cf0993830073.png

**Comment by alioztr** [comment]
not downloading, waits look like picture i added.

**Comment by lenamtl** [comment]
The wait popup is going to stay like this because of the animation bug.

The zip file should be created and downloaded (the popup will remain open)
I can see on your picture that there is a file downloaded, could you check your download folder (based on your browser settings) if the file is downloaded

**Comment by alioztr** [comment]
no download. It was manual download.

I think i can not use this script.
I changed to turkish language. I worked 2 days for translate.
And i have turkish character problem.

thanks.

**Comment by lenamtl** [comment]
I think the problem is related to the cloud service you are using.

For language issue I provided you the fixed already https://github.com/ignacionelson/ProjectSend/issues/182

**Comment by ilackskills** [comment]
This is a configuration issue, you need to modify your php.ini

http://www.php.net/manual/en/ini.list.php
