### ISSUE TITLE
Turkish character problem

### ISSUE THREAD

**Issue by alioztr** [ignacionelson/ProjectSend#298]
If i write something to description area, i have character problem.
some turkish character not show correct,
for example ö,ü character shows wrong.
if i look to description tables in phpmyadmin, it shows wrong again.
But in admin area if i want to change description it shows normal character.

How i fix this problem, thanks

**Comment by lenamtl** [comment]
Hi please check this solution, it is working ok, this is not only fix the problem but also save character correctly into the DB
https://github.com/ignacionelson/ProjectSend/issues/182
