### ISSUE TITLE
Bug: the search filter on assign to field, is not finding an existing client name

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#30]
Let say I have a client Jane Doe and I want to assign a file to this user
If I enter Jane or Jane Doe into the assign to field = No result found!

In fact it's only search on lastname and cannot find group.

PS the search is working ok on groups-edit.php

Note: In my old custom version I use Select2 instead of Chose and the search is working ok.

**Comment by ignacionelson** [comment]
Fixed!

**Comment by lenamtl** [comment]
Thanks

**Comment by ignacionelson** [comment]
r582 includes this fix. Closing the issue now.
