### ISSUE TITLE
duplicate email addresses

### ISSUE THREAD

**Issue by onlinestatements** [ignacionelson/ProjectSend#309]
Is there a way to be able to use the same email address in more than one account when creating new accounts?
I got a customer that has multiple clients and needs multiple accounts but needs them all to be the same email address.
The login name is not the email address so I don't see why that would be an issue.
For now I just create the accounts then manually modify the MySQL database to make all the emails the same.
If you don't want to implement this into the public release could you at least tell me where I can manually change it in the code?
Thanks

**Comment by FloorOut** [comment]
yes there is: edit the raw datatable in MySQL and type the duplicate adres.
Do not edit the user after that.

Op 7 dec. 2016 14:21 schreef "onlinestatements" <notifications@github.com>:

**Comment by lenamtl** [comment]
This is not recommended but there is a quick solution for this
https://github.com/ignacionelson/ProjectSend/issues/238

**Comment by FloorOut** [comment]
Right, but it disables the check for every new user. One shoot keep that in
mind!

Op 8 dec. 2016 18:24 schreef "lenamtl" <notifications@github.com>:

**Comment by lenamtl** [comment]
I don't recommend to use it.
What is the use case for this?

**Comment by FloorOut** [comment]
leam, you are right, disabling the check in php is wrong. I only use
editing the row table to give one person the role of client/user/mediater
with diverend credentials but the same mailaddress. Just this exeptional
case. No risk involved!!

Op 9 dec. 2016 03:25 schreef "lenamtl" <notifications@github.com>:

**Comment by lenamtl** [comment]
Ok no problem, but why this user need 3 roles that is another question ;)

**Comment by FloorOut** [comment]
Just for testing, me/myself/alterego ;)
