### ISSUE TITLE
Suggestion: Replace TimThumb script

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#31]
We should not use TimThumb anymore.

We should replace it by another script
or 
if it is only for the logo, remove the upload logo feature and modify the template to use logo.png so we just need to change the dummy logo with site owner logo.

**Comment by ignacionelson** [comment]
I agree completely, but it's not only for the logo. The templates use it for the thumbnails of images.

**Comment by lenamtl** [comment]
Replacement suggestion (never tested)
https://github.com/magnetikonline/thummer

**Comment by lenamtl** [comment]
Any other suggestion for this?

**Comment by ignacionelson** [comment]
Replaced with SimpleImage
