### ISSUE TITLE
Can there be a direct download link?

### ISSUE THREAD

**Issue by daelvn** [ignacionelson/ProjectSend#316]
Hello.
I've set up ProjectSend on aur.rf.gd using Softaculous, and it works perfectly, but the original purpose of it was having direct links for a package manager to be able to download them. Is there a way I can modify it to use direct download links? Or do I have to use SQL and other tricks?

Thanks in advance
~ Dael

**Comment by lenamtl** [comment]
I'm not sure what you need but there is public link available.

**Comment by daelvn** [comment]
Just a link that instead of an interface, downloads the files. Ive tried process.php?do=download and a custom script to solve the SQL IDs with no result and upload/files appends a `.` on it, i need a link that directly downloads it with no interface and no changes. If its possible, on a custom configurable folder

**Comment by lenamtl** [comment]
The only option for now is using the public link.

**Comment by ilackskills** [comment]
can you please explain what you are trying to do.
