### ISSUE TITLE
Known-Good Install Environment

### ISSUE THREAD

**Issue by Ciscog33k** [ignacionelson/ProjectSend#333]
Since there are some issues with current versions of MySQL, and PHP. 

What is a known-good pairing of these two that will result in a working ProjectSend install?  

Is it only PHP 5.5?  (EOL)

**Comment by lenamtl** [comment]
I'm using PHP 5.6.19 with no problem make sure PDO drivers are enabled.

**Comment by Ciscog33k** [comment]
What about SQL version?

**Comment by xrat** [comment]
Installation fails on MySQL 5.5, cf. #320

**Comment by lenamtl** [comment]
I'm using MySQL 5.7.11
