### ISSUE TITLE
Clean 757 install. Upload not working

### ISSUE THREAD

**Issue by macintyres** [ignacionelson/ProjectSend#335]
upload-from-computer.php seems to display correctly and function correctly, letting me add files. Upon clicking the upload button, I'm sent to: upload-process-form.php.

upload-process-form.php shows the Project Send navigation bar, but the body of the page has "Upload Files" within an h2 tag. That's it.

Going to manage files, shows me that nothing uploaded.
I checked all my folder permissions on the server and I don't see anything that would stop the upload from happening there, and the file types I tried were all in the allowed formats (e.g. jpg, txt)

I also tried uploading from the branding section with similar results, making me think it's a privilege issue, but I can't find it.

I've also created a text file in /upload/files. Then searched orphan files. It found the text file, but when I tried assigning groups, etc. I got the same issue at the upload-process-form.php

**Comment by macintyres** [comment]
I also tried uploading from the branding section with similar results, making me think it's a privilege issue, but I can't find it.

**Comment by eyeobticeo** [comment]
I can confirm the error. After Security Fixes #321 , it does not work anymore.
But I still have no idea what it could be

**Comment by eyeobticeo** [comment]
I think issues  #329 is the same.

**Comment by macintyres** [comment]
After trying the  #329 fix, everything seems to be working properly.
