### ISSUE TITLE
connect remotely with different port

### ISSUE THREAD

**Issue by macintyres** [ignacionelson/ProjectSend#338]
I have Project Send installed on a Ubuntu server 16.04
It works fine locally, but from outside my Lan, it doesn't work completely.
I have my cisco 5505 setup to nat port 84 traffic to my server's ip, and I have apache listening on 84. The website comes up partially; it's missing css and other stuff. I have an idea that it's because system uri is:
http://192.168.1.5/projectsend/ 
I've tried setting the uri to my external ip and port number, but that didn't work.

**Comment by ilackskills** [comment]
you are correct, http://192.168.1.5/projectsend/ is port 80, you will need http://192.168.1.5:84/projectsend/

**Comment by macintyres** [comment]
It's not working for me. I don't have a domain for the project so I'm using the ip. When I try the local ip it doesn't work because the outside world can't figure out what to do with the local ip. When I try the outward facing ip it doesn't work either.

**Comment by lenamtl** [comment]
You will need to have IP/DNS service for this.
This is not a problem with PS,  it is a server configuration.

**Comment by ilackskills** [comment]
forward external port 84 to inner 80 but why not just use port 80?
