### ISSUE TITLE
User view by Category

### ISSUE THREAD

**Issue by pcmvirtual** [ignacionelson/ProjectSend#346]
### I have used ProjectSend for some time, and I can say that it is very practical and good.

One thing I would like to know if there is a **possibility to enable the user to view by category**.

That would help the organization a lot.

And it would be more organized. It would be a great improvement on the system, which is very good. #

**Comment by lenamtl** [comment]
Could you elaborate?

**Comment by barna119** [comment]
I think he would like to have folders view. (Categories can be used like folders.)

**Comment by lenamtl** [comment]
If you are talking about a table filter
https://github.com/ignacionelson/ProjectSend/issues/225

else feel free to reopen and elaborate
