### ISSUE TITLE
Letter "ó" in description is improperly shown as "&oacute;"

### ISSUE THREAD

**Issue by mnlabs** [ignacionelson/ProjectSend#35]
What steps will reproduce the problem?
1. Upload file with letter `ó` in description. Assign to a client.
2. Go to Clients -> Manage Clients. View as a client.
3. Letter `ó` in description is improperly shown as `&oacute;`

What is the expected output? What do you see instead?

What version of the product are you using? On what operating system?
r561. Debian 8 (Jessie). Same situation with r582.

![bad](https://cloud.githubusercontent.com/assets/12913971/8186590/7b8b27ea-144b-11e5-8833-23fbdfd22ab4.png)
![good](https://cloud.githubusercontent.com/assets/12913971/8186591/7b908032-144b-11e5-87d9-f20388d0817c.png)

Please provide any additional information below.
Mysql/MariaDB database is in utf8 mode. Other letters are shown and stored in a proper form.

Info on the old tracker: 
https://code.google.com/p/clients-oriented-ftp/issues/detail?id=537&thanks=537&ts=1432194897

**Comment by lenamtl** [comment]
I'm having same issue with french #25

**Comment by ignacionelson** [comment]
Haven't tried it yet, but how about this?
On templates/default/template.php, change, on line 132,
echo htmlentities($file['description']);
to
echo htmlspecialchars($file['description']);

Please let me know if that worked for you.

Thanks!

**Comment by mnlabs** [comment]
Unfortunately it didn't help. Also tried changing all instances of 'htmlentities' in template.php and in manage-files.php.

**Comment by lenamtl** [comment]
The problem is the way the data is saved in the DB.
It is not save correctly
we should not see this in the DB &oacute; 
but this instead ó

I have checked on most of the web application I use that use UTF-8 
like Mantis 
and the data is save like ó not &oacute;

**Comment by mnlabs** [comment]
This. It looks like lenamtl is right. Special case is edit page where value is inserted into text areas/input fiels and browsers change `&oacute;` to ó the same way this post doesn't make sense for example in web-mail client.

    +-------------------------------------+-------------------------------------------------+
    | filename                            | description                                     |
    +-------------------------------------+-------------------------------------------------+
    | debian 8.0.0 amd64 netinst          | &oacute;&oacute;&oacute; żćź&oacute;łźćś        |
    | czołg                               | Test public downloadu                           |
    | &oacute;łżźćś                       | &oacute;&oacute;&oacute;&oacute;                |
    +-------------------------------------+-------------------------------------------------+

**Comment by ignacionelson** [comment]
Another option could be to set the db each time to utf8 after it connects, with the following query

SET NAMES utf8;

It will probably break other things, and some functions may need to be changed, but if you do that query just before the one that gets the files, the encoding might change.

I can't try it right now, I will give it a go later. If anyone can run a quick test, it would help a lot!

**Comment by ignacionelson** [comment]
And a second one could be changing
 echo htmlentities($file['description']);
to 
 echo htmlentities(utf8_decode($file['description']));

**Comment by lenamtl** [comment]
I believe that the htmlentities is not a good approach ...

We should use something like this
(I took it from http://stackoverflow.com/questions/26971036/php-prevent-from-encoding-%C3%A9-to ) 

>The data of your file is UTF-8
>When you use string functions with constant strings (e.g. str_replace('e', 'é', $foo)) this file is UTF-8
>The database connection you use allows the transportation of UTF-8 encoded characters and is configured for that (SET NAMES 'utf8' for MySQL)
>The Content-Type header (or meta-tag) of your page tells the browser to expect UTF-8

Temporary solution:
Here is what I did with previous old version this may applied to this new version too I have not tried yet.
This was a plaster solution:
https://code.google.com/p/clients-oriented-ftp/issues/detail?id=279&q=french

I plan switching the whole code to PDO but this will take a some time....

**Comment by mnlabs** [comment]
> I plan switching the whole code to PDO but this will take a some time....

Please do. Can we also switch to Postgresql as default backend? It's sooo much nicer to work with than Mysql.

**Comment by lenamtl** [comment]
My knowledge of PostgreSQL is very limited but when using PDO the advantage is we can use other PDO drivers.

For now I'm still working on updating the whole template to latest Bootstrap and other jQuery scripts version this is lot of work ... ( I have 40% done)

Then I plan to update the application to PDO, lot of work ...

I plan to share both forks when completed and tested.

**Comment by lenamtl** [comment]
Hi just to let you know the new update is using PDO (prepared statement)
https://github.com/ignacionelson/ProjectSend/issues/114

**Comment by honeybadge** [comment]
The German Umlauts are also not displayed properly "ä ö ü ?"
Using UTF8 should fix theses issues.

**Comment by lenamtl** [comment]
See #182 after a lot of debugging
 I have found a way that seems to work for french, this need to be tested to make sure but till now it's working fine.

**Comment by Kerstin2017** [comment]
hello, 
is there between time a solution?
In the database are the files with the umlauts (ä, ö,...)
![image](https://cloud.githubusercontent.com/assets/27786037/25201610/9d90daf0-2552-11e7-844e-e1f075a3440a.png)

but in User Font : 
![image](https://cloud.githubusercontent.com/assets/27786037/25201563/793d59ee-2552-11e7-9103-2ed1e44ce03c.png)

Can anybody help ? :-) 

Thanks

**Comment by lenamtl** [comment]
You have to modify the scripts according to this:  https://github.com/ignacionelson/ProjectSend/issues/182

Sorry there is no shortcut to fix the problem.
