### ISSUE TITLE
FTP upload, notification when file was downloaded by client 

### ISSUE THREAD

**Issue by wilqndm** [ignacionelson/ProjectSend#350]
Hi, 
I have two questions. 
First, Can I transfer a file via FTP to the client folder? 
Second, when notifications are sent ? I ask for notification when the file is downloaded by the client.

**Comment by ilackskills** [comment]
> First, Can I transfer a file via FTP to the client folder?
Not sure

> Second, when notifications are sent ? I ask for notification when the file is downloaded by the client.
would not count on this being added anytime soon, dont think its something most people want or need.

**Comment by lenamtl** [comment]
1- if you sent the file using FTP, you the file will appear in orphan list.

**Comment by lenamtl** [comment]
1- if you upload the file using FTP, you the file will appear in orphan list.

2- Use the audit trails to check, notification on download will be too much email for nothing.
