### ISSUE TITLE
r754 - Broken img on login page (index.php)

### ISSUE THREAD

**Issue by supersunken** [ignacionelson/ProjectSend#351]
After upgrading from r609 to r754, index.php page shows a broken image. The code bit shows...

```
<div class="col-xs-12 branding_unlogged">
<img src="/img/custom/logo/m_logo.png" alt="foobar">
</div>
```

The logo is inside this img directory, but not showing up on the login page.

**Comment by lenamtl** [comment]
log as admin, go to option - thumbnail and check the checkbox of Use file's absolute path
see #199
