### ISSUE TITLE
r754 - Unable to change client's template

### ISSUE THREAD

**Issue by supersunken** [ignacionelson/ProjectSend#352]
After upgrading from r609 to r754 I'm not able to change the client's template under options. Stuck on default template. When I try to change it to Gallery or PinBoxes I get a pop up dialog in Chrome "Please complete all fields" even though all fields are completed on this tab.

**Comment by lenamtl** [comment]
Check this pull https://github.com/ignacionelson/ProjectSend/pull/343

**Comment by supersunken** [comment]
The pull did not fix the issue with Chrome. I used Firefox instead to make the template change.

**Comment by ignacionelson** [comment]
Fixed. The template selection is on it's own page now.
