### ISSUE TITLE
"Check if the field value is a valid e-mail address" fails on .museum TLD

### ISSUE THREAD

**Issue by Blake-** [ignacionelson/ProjectSend#354]
Tried to register a new user at the TLD .museum and the result was " E-mail address is not valid" 
I think this regex might be off a bit?
https://github.com/ignacionelson/ProjectSend/blob/52a09ac8faf6c5efa761648e3141319899941ced/includes/classes/form-validation.php#L44

.museum is a real Top Level Domain:
http://about.museum/

**Comment by ilackskills** [comment]
your email address is XXX@museum.com?

**Comment by Blake-** [comment]
My email address is not xxx@museum.com no, but I just tried to add a new user to my projectsend install that was indeed xxx@museum.com
There are indeed email addresses @museum.com

**Comment by lenamtl** [comment]
Please check previous discussion https://github.com/ignacionelson/ProjectSend/issues/105
