### ISSUE TITLE
php error on categories page

### ISSUE THREAD

**Issue by cpcnw** [ignacionelson/ProjectSend#357]
r754: Shown in header when loading categories.php

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at /home/domain/public_html/projectsend/categories.php:1) in /home/domain/public_html/projectsend/sys.vars.php on line 12

**Comment by cpcnw** [comment]
At advice elsewhere I pasted 

<?php ob_start(); ?>

right at top of categories.php and it remove the above error?

**Comment by lenamtl** [comment]
Have you edited the page previously, have you removed the included header.php ?
or made some changes on header.php ?

**Comment by cpcnw** [comment]
header.php is as provided in update r754

**Comment by lenamtl** [comment]
Have you edited the page previously, have you removed the included header.php ?

**Comment by cpcnw** [comment]
All I did was update from the previous version [actually from the one before that] by overwriting as in the howto! So all the files where replaced with the new ones!

**Comment by cpell** [comment]
this is fixed here https://github.com/ignacionelson/ProjectSend/commit/b2d1ffe6001ee9136847611406f312770c83bb05
