### ISSUE TITLE
Public files token missing

### ISSUE THREAD

**Issue by jucajuca** [ignacionelson/ProjectSend#358]
Hello

This is the way to replicate the problem:

(new installation, no clients, no companies)
Upload a file
Mark it as public
Click next

In the next screen there is a button that marks the file as public. When you click it a download link appear, but it has no token, and it doesn't work.

When I go to manage files, however, the token is there. 

Thanks.

**Comment by lenamtl** [comment]
Hi I got similar issue in the past when latin accent and special characters was used I think that was for description or inside the name of the file, don'T remember.

**Comment by jucajuca** [comment]
it worked perfectly!
