### ISSUE TITLE
Download Zipped option

### ISSUE THREAD

**Issue by ghost** [ignacionelson/ProjectSend#36]
Hi, currently running ProjectSend r582 and all appears fine apart from the fact that the 'download zipped' option for Clients is causing an issue. Process runs through and a zip file is produced but the file is empty. No errors received and the dashboard reports the zip download in the stats. Is anyone else getting this ? Any suggestions as to a solution ? Many thanks.

**Comment by mnlabs** [comment]
Works for me. Maybe you miss some dependencies on a server? Do you have gzip installed?

Although I have a different issue. "Please wait while your download is prepared." pop-up doesn't close itself.

**Comment by k33fy** [comment]
I will run through the dependancies and have a look. Also, I do not believe I have gzip installed.

In addition to my issue above I also have the issue of the splash notification not closing.

**Comment by lenamtl** [comment]
The splash notification not closing is a known issue.

Did you fixed the download zip issue?
