### ISSUE TITLE
Max members of a group is 998?

### ISSUE THREAD

**Issue by jameswoodinfo** [ignacionelson/ProjectSend#362]
Hello all,

Have setup ProjectSend for a client and have encountered this issue:

When adding all users to a group (in this case >1000) the result is that the first 998 are added and the remaining are excluded. 

When I trace what is happening in actions-groups.php it seems that the $arguments['members'] variable contains only the first 998, so only those are inserted in the database.

What might be happening here?

Thanks in advance!

**Comment by lenamtl** [comment]
Does any special characters in client name?
Maybe there is a limit when processing.
Check PHP and Mysql log file
and enable PHP error to display during the test to get the maximum of info.
I don't have a setup with 1000 clients and the relations between tables are very complex so I cannot recreate your bug for that reason.

**Comment by jameswoodinfo** [comment]
No special characters.
I have checked for errors and there are none, everything is processed successfully.
When I edit the group, and ADD ALL (which is more than 1100) I see all the names listed in the box. When I click submit, the form is processed, but it seems only the first 998 are submitted for processing...

Like I said in actions-groups.php it seems that the $arguments['members'] has only 998 client IDs.

**Comment by paspo** [comment]
can you check post_max_size and max_input_vars ini php.ini?
max_input_vars is default to 1000, try to raise this to 2000

**Comment by jameswoodinfo** [comment]
That solved the issue. Thanks!
