### ISSUE TITLE
Thumbnails not Showing

### ISSUE THREAD

**Issue by rickbolla** [ignacionelson/ProjectSend#364]
I used cPanel to install ProjectSend on my site. Thumbnails for the custom logo and uploaded file images were not showing. In the Thumbnails system options, I selected the Use Absolute Path option. This fixed the logo display on the login screen but not on the Client's my-files screen. Is there a way to get this to work properly.

**Comment by lenamtl** [comment]
This is a configuration issue.
Do you have any error message from chrome console / right click inspect

**Comment by ilackskills** [comment]
@rickbolla please create me a test account for me to take a look.

**Comment by rickbolla** [comment]
Hi,

I created a test account and uploaded some photos.

www.shadeofgreyweims.com/fileVault <http://www.shadeofgreyweims.com/fileVault>

User: testUser
Password: testPassword

Thanks,
Rick Bolla

**Comment by ilackskills** [comment]
500 error on thumbs, can you turn on errors?

**Comment by rickbolla** [comment]
??? Not sure what you mean?

**Comment by ilackskills** [comment]
Can you turn on errors in your ini file, so i can see whats causing the issue.

**Comment by lenamtl** [comment]
Use Chrome tool (rigth-click inspect) you will see JS error into the console
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

https://shadeofgreyweims.com/fileVault/includes/timthumb/timthumb.php?src=https://shadeofgreyweims.com/fileVault//img/custom/logo/sogw-logo-300x276.png&w=300

Your links display with https but not your website....

**Comment by rickbolla** [comment]
Hi,

I turned on error display in my php.ini file for (home directory and shadeofgreyweims.com <http://shadeofgreyweims.com/> directory) but no errors are displaying. Is there an ini file somewhere else I need to change?

When I enter a https link to an image in the browser it displays okay - https://shadeofgreyweims.com/fileVault//img/custom/logo/sogw-logo-300x276.png <https://shadeofgreyweims.com/fileVault//img/custom/logo/sogw-logo-300x276.png>

I appears to me that the issue is related to timthumb not being able to find or display the image.

**Comment by lenamtl** [comment]
The problem is related to https / http 
You cannot mix https and http
When you use https all links even image need to be https
or if you use http all link must be http

So fix the https and check all links to make sure it is using https
 or don't use https and make sure it is using http

Also make sure you the uri is set correctly
sys.var.php to set the system_uri to use https:// or http://

**Comment by rickbolla** [comment]
Thanks for trying to help with this issue. It appears that we are not going to be able to solve the problem so I guess I will need to find some other software solution for uploading pictures.

**Comment by rickbolla** [comment]
As far as I know, I am not mixing http and https. My site, www.shadeofgreyweims.com <http://www.shadeofgreyweims.com/>, is using all https. I used cpanel to add ProjectSend as a subdirectory to my site. Where is http being used?

**Comment by ilackskills** [comment]
I still do not see the errors


![image](https://cloud.githubusercontent.com/assets/15673241/23722913/c723d424-040c-11e7-9976-bf8f6fb0345e.png)

**Comment by lenamtl** [comment]
Open Chrome right click + inspect you will see somes errors

I can see this which clearly show https
https://shadeofgreyweims.com/fileVault/includes/timthumb/timthumb.php?src=https://shadeofgreyweims.com/fileVault//img/custom/logo/sogw-logo-300x276.png&w=300

**Comment by ilackskills** [comment]
Yes I understand that but because I dont know much about how this software handles HTTPS i need to see the line errors.

**Comment by rickbolla** [comment]
But where is the http you say is being mixed in?

**Comment by lenamtl** [comment]
Because I can access your web site login page using http and https

**Comment by rickbolla** [comment]
My web site does not have a login page. The login page is part of the ProjectSend utility. I did not write or configure this software. I just installed in using my web host’s cpanel utility. 

As for seeing the errors, I’m not sure what else I need to do. I made your suggested changes to the php.ini and sys.var.php files.

**Comment by lenamtl** [comment]
The login page of projectsend is on the same domain name...

Please take the time to answer this question
Do you want to use SSL for Projectsend yes or no?

You have to configure Projectsend to make it work base on your server settings...
Every web application need to be set so this is not only for Projectsend.

Make sure you the uri is set correctly
sys.includes.php to set the system_uri to use https:// or http://

If you want to see php error on your pages for debug purpose 
you have to set error_reporting(E_ALL) to true on sys.var.php
don't forget to put it back to false in production mode.

**Comment by rickbolla** [comment]
Turned on error_reporting in sys.var.php and am now seeing an error.

Warning: shell_exec() has been disabled for security reasons in /home/shadeofg/public_html/fileVault/includes/functions.php on line 726
File size: 176.85 KB

**Comment by lenamtl** [comment]
Please contact your webhosting company with the error message .
