### ISSUE TITLE
Auto delete files with no filesize

### ISSUE THREAD

**Issue by Invictaz** [ignacionelson/ProjectSend#368]
I use projectsend to upload files and then a cronjob to move everything to another directory.
I hope projectsend can have an option that auto removes files with no filesize (since they are removed) after 1 week.

**Comment by ilackskills** [comment]
Remove the files from the DB?  Do not believe that is a current function...may have to wait for some time to get that done or code it yourself.  That is a bit of work.

**Comment by lenamtl** [comment]
Using your cronjob and a php script you should update the database too.
Check this post about script to purge https://github.com/ignacionelson/ProjectSend/issues/65

**Comment by lenamtl** [comment]
I'll close this for now, and keep other post open so maybe we can add a purge file function in future version.
