### ISSUE TITLE
Suggestion: Show default e-mail templates code inside of input fields. 

### ISSUE THREAD

**Issue by mnlabs** [ignacionelson/ProjectSend#37]
Hi.

Default templates are quite nice but to change only minor thing one needs to write whole template from scratch. It would be nice to have default code right there in text areas ready for quick tweaks. 

PS And in that case reset to default button would be nice. Thanks!

**Comment by lenamtl** [comment]
+1

**Comment by honeybadge** [comment]
+1
Does anyone know where the default templates are stored right now? I'd like to review all of them and right now there is no way to do this.

**Comment by ignacionelson** [comment]
Added buttons to load the default templates on the textareas.
