### ISSUE TITLE
Automated Email Subjects

### ISSUE THREAD

**Issue by nathan93** [ignacionelson/ProjectSend#370]
How can I changed the subject lines of the automated PHP emails that are sent by ProjectSend? For example, I don't want my clients to see an email with a subject that says "Welcome to ProjectSend," rather something having to do with my company.

**Comment by ilackskills** [comment]
You will need to modify includes/classes/send-email.php, I have done this to display the user name of who has uploaded.

**Comment by ilackskills** [comment]
check #275
