### ISSUE TITLE
Missing checkbox in Groups Administration

### ISSUE THREAD

**Issue by ArsenioV** [ignacionelson/ProjectSend#371]
Checkbox missing from Groups Administration page, causing Admin to not be able to delete existing Clients Groups.

Version: r754

Screenshots attached.
Cheers.

![1](https://cloud.githubusercontent.com/assets/25642111/24008882/5b5689fe-0a73-11e7-9412-627328bb8b8c.png)

![2](https://cloud.githubusercontent.com/assets/25642111/24008886/5f5be0da-0a73-11e7-8a34-1695151f23f5.png)

**Comment by lenamtl** [comment]
Please see this post for a fix https://github.com/ignacionelson/ProjectSend/issues/64
