### ISSUE TITLE
projectsend uninstall

### ISSUE THREAD

**Issue by jb2210** [ignacionelson/ProjectSend#373]
hi there github community,

I was wondering because I only want to use this service very temporarily. And after that remove Projectsend and move the files to another server to reinstall projectsend on that server. So because of this very shot use i would like to know the directory's projectsend installs in? So I can quickly delete and reinstall on the other computer.

**Comment by ericbeaucourt** [comment]
Normally the project is installed in "projectsend". So it is very easy to remove "projectsend" for example trough filezilla .

**Comment by jb2210** [comment]
okay good to know, thank you!!!

2017-03-20 11:13 GMT+01:00 ericbeaucourt <notifications@github.com>:
