### ISSUE TITLE
bad startup page

### ISSUE THREAD

**Issue by jb2210** [ignacionelson/ProjectSend#375]
I downloaded ProjectSend today and did everything described here: http://uncovertech.com/howto-install-projectsend-ubuntu-14-04/, but I end up with this when opening http://server-ip/ProjectSend to install it.
![screenshot](https://cloud.githubusercontent.com/assets/25897516/24117921/47110762-0dac-11e7-91db-30c213777033.png)

**Comment by jb2210** [comment]
I retried to open the page on apple, ios, android, w8, wp8, ubuntu, debian and w10 in chrome, firefox, safari, internet explorer and edge. Non of them provided a normal page, although the phones gave a different layout of this page. It stil doesn't look like it's supposed to be, do I miss php drivers? What am I missing here?

**Comment by ilackskills** [comment]
its a php server issue.

**Comment by jb2210** [comment]
Is there any way to solve it?

Op 21 mrt. 2017 19:44 schreef "ilackskills" <notifications@github.com>:

**Comment by paspo** [comment]
Most likely the PHP engine is not enabled.
put a file named "info.php" in the webserver document root, with this content:
`<?php phpinfo(); `
then go to  http://server-ip/info.php. If you see the content of the file, PHP is not enabled. If you see a very long page with a lot of informations on PHP variables, then PHP is ok.

**Comment by jb2210** [comment]
okay thank you, I got it working. If anyone else runs into this problem, this is what I did:

first I added this at the end of the /etc/apache2/apache2.conf file
`<FilesMatch \.php$>`
`SetHandler application/x-httpd-php`
`</FilesMatch>`

after doing that, I issued the following command:

`sudo a2dismod mpm_event && sudo a2enmod mpm_prefork && sudo a2enmod php#current version number#`

to finish it all up I issued:
`service apache2 restart`

Thank you all for helping out so far!!
