### ISSUE TITLE
Error on WAMP Installation

### ISSUE THREAD

**Issue by genxcoders** [ignacionelson/ProjectSend#382]
There seems to be an error. Please try again.
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'expiry_date' in C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php:31 Stack trace: #0 C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php(31): PDOStatement->execute(Array) #1 C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php:31 Stack trace: #0 C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php(31): PDOStatement->execute(Array) #1 C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php:31 Stack trace: #0 C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php(31): PDOStatement->execute(Array) #1 C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php:31 Stack trace: #0 C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php(31): PDOStatement->execute(Array) #1 C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' in C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php:31 Stack trace: #0 C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php(31): PDOStatement->execute(Array) #1 C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php:31 Stack trace: #0 C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php(31): PDOStatement->execute(Array) #1 C:\wamp64\www\GenXCoders-CTO\GenXDMS\install\index.php(108): try_query(Array) #2 {main}

What do i do?

**Comment by lenamtl** [comment]
https://github.com/ignacionelson/ProjectSend/issues/179
