### ISSUE TITLE
client group selection on signup page

### ISSUE THREAD

**Issue by kkplein** [ignacionelson/ProjectSend#387]
Hi,

Is there a way for client registration to indicate / request access to a specific client group?

We have defined multiple client groups, and we will allow client self registration. We are unsure how to  'match' client sign-ups to the groups we have defined. Specially in the case of a buzier site with many clients / client groups this can become problematic?

An available client-groups selection pull down on the sign-up page would be perfect. In that case the client-signup notification email could also be sent to the client-group owner.

**Comment by lenamtl** [comment]
Could you specify which domain activity you will use it?

It's can be a nice to have, I can see some use of it, this should be an option as not everyone need this feature.

You will have to add a select dropdown so visitor can select a group when they register, then you have to modify the registration code so it add the user to the correct group in the database.

**Comment by kkplein** [comment]
I'm unsure what "which domain activity you will use it" means...?

But your summary matches our use case exactly: drop-down upon registration, and (optionally as well) even allow the creator/owner of the group to allow/deny access for the new registration.

Does this project accept sponsored features..? Unsure how much this would be, but I could try to get (some) funding for this.

**Comment by ignacionelson** [comment]
This looks like a good idea.
The only thing that goes against the current way of doing things, is that groups are private and only visible by site administrators and not clients since they are a way of simply organizing clients. So, a new option would have to be added to enable groups to be public, and another one to let the new client select their group on sign up and when editing his profile.

On the other hand, each group could get a new setting, to indicate if it must be hidden or visible (by default, hidden? to not mess with users already using groups on their sites)

We should analyze the more friendly approach for system admins.

Would this work for you?

Thanks!

**Comment by kkplein** [comment]
Yes, this sounds very good, new options while preserving old behaviour.

**Comment by barna119** [comment]
Self assigning clients to (public) groups. Sounds good!

(I'd allow all groups to be visible, if self-assigning is allowed.)

**Comment by barna119** [comment]
The same functionality can be obtained if you set one Projectsend installation per client group. Then you don't need client groups.

**Comment by kkplein** [comment]
But keeping multiple (and quite possibly MANY) ProjectSend installations up-to-date is not really a nice solution. But I agree: it would give you the desired behaviour.

**Comment by barna119** [comment]
I couldn't agree more.

But this was the suggestion I got from lenamtl in issue #391.

**Comment by kkplein** [comment]
We are currently in discussion with PS author to implement this functionality. In exchange we would be willing become a patreon for a certain period. Perhaps you could do similar, as that would surely help to get this implemented.

**Comment by barna119** [comment]
I'll write it if I get a little time.

**Comment by kkplein** [comment]
Ah a programmer :-)

**Comment by barna119** [comment]
:-)

A lazy one. :-(

**Comment by lenamtl** [comment]
The solution I provided you is to save time and money, so you don't need to hire a dev  to do it and get it fast setup.
If you have time and budget you can get any custom code you want ;)
