### ISSUE TITLE
home.php navigation fails

### ISSUE THREAD

**Issue by marcurdy** [ignacionelson/ProjectSend#388]
For admin and user, when logged in to the home.php page, all header links do nothing.  If I manually navigate to /my_files/, the links to the header dropdowns start working.  Once I go back to the dashboard at home.php, they stop working again.

MYSQL 5.6 on Linux Ubuntu 14.04.

Thanks.

**Comment by ignacionelson** [comment]
Hello!
What is your php version?

Please try renaming the .htaccess file to anything else temporarily to see if that works. Also, if PS is on a folder, there might be additional htaccess from upper level directories files affecting it.

**Comment by marcurdy** [comment]
I meant to say PHP 5.6 (mysql 5.5).  
Renaming .htaccess didn't change anything.
I don't know what PS is in context of a Linux server.  I ensured the group that apache uses has read/write to the entire tree.  I can upload files after fixing that, but it didn't affect the main problem.
To recap:
/home.php -> dropdowns are ignored
/options.php, users-add.php, group-add.php, etc -> dropdowns work

**Comment by ignacionelson** [comment]
Oooooh sorry, i misunderstood your problem! I thought that you couldn't get home.php to work at all.
Do you have any javascript errors on that page? You can check with firebug or the default console of the browser.

**Comment by marcurdy** [comment]
In bottom console doesn't change when I try to click.  I've since found that many variables used are pulled using _GET leaving form manipulation to chance.  I was hoping to use this as an http replacement for ftp, but I need the utmost security.
