### ISSUE TITLE
textarea  - file edit description box

### ISSUE THREAD

**Issue by onlinestatements** [ignacionelson/ProjectSend#389]
How can I make the description textarea more than 2 lines high?
I would like it to be atleast 5 lines high and also have the ability to resize it vertically.
Right now I can only resize this box horizontally.
Also would like it to stop adding html characters to the box after submitting it.
Thanks

**Comment by barna119** [comment]
"Also would like it to stop adding html characters to the box after submitting it."

I think it's a bug.  To remove HTML character visibility in file list I changed templates/default/template.php
line 161

- <td class="description"><?php echo htmlentities($file['description']); ?></td>
+ <td class="description"><?php echo $file['description']; ?></td>

**Comment by lenamtl** [comment]
Could you explain 

> Also would like it to stop adding html characters to the box after submitting it.

**Comment by barna119** [comment]
In the description text
\n is changed to &lt;br />
é is changed to &amp;eacute;
etc. when stored in the database. I think he means that.

**Comment by dannyulman** [comment]
@barna119 
Thats exactly what I was talking about!
Thank You
It would be nice if the box was also atleast 5 lines tall
and have the ability to resize it vertically.

**Comment by dannyulman** [comment]
it mainly just adds <br> to the end of every line
It displays the code instead of interpreting it

**Comment by lenamtl** [comment]
The system is using a plain textarea....

You can use textarea script like tinyMCE, 
this way you can manage all the settings and allow or disallow the features and have the responsive possibility and this will interpret the HTML script if you allow it.
https://www.tinymce.com/

For the box you have to adjust it into the code find textarea then change row="" attribute for what you want. I believe the plain texarea have the right corner handle to allow the user to expand the box.

Also you can use auto grow textarea or other script it's up to you..
http://onehackoranother.com/projects/jquery/jquery-grab-bag/autogrow-textarea.html
