### ISSUE TITLE
TABLES_PREFIX not working correctly

### ISSUE THREAD

**Issue by colpaert** [ignacionelson/ProjectSend#39]
I have a new installation of PS and have changed the tables prefix from "tbl_" to "ps_" in sys.config.php before proceed to install.
PS install finished installation (successfully), but created the tables with "tbl_" prefix instead.
When I hit the "log in" button, I was redirected to .../install/index.php and could not log into the system.
If I tried to configure the system again, the response was that it already had an entry.
The only way to get out of this situation was to reconfigure sys.config.php setting TABLES_PREFIX back to "tbl_".

**Comment by lenamtl** [comment]
+1

**Comment by Harry-Harrison** [comment]
Same issue here. Comment for the option even suggests changing it for added security... :smile:

**Comment by kbeyer33** [comment]
+1
./install/database.php has table names hardcoded and doesn't use TABLES_PREFIX from ./includes/sys.config.php

**Comment by ClmH** [comment]
Thanks for your quick answer, I haven't found this topic.
Could you add a line about it in the README.md for futur users ?
"1. Rename includes/sys.config.sample.php to sys.config.php and set your database info there. Do not change the TABLES_PREFIX, it's currently messing with the installation (to be fixed)."

**Comment by glego** [comment]
Hi,

It's probably not on your top priority list but the bug is almost 1 year. Are there any plans to fix this in the near future?

Best Regards,
Glego

**Comment by lenamtl** [comment]
I have not tested it yet but I beleive this has been fixed try the latest version and let me know

**Comment by lenamtl** [comment]
This has been fixed please try the latest package
