### ISSUE TITLE
Filesize: find orphan files - not correct

### ISSUE THREAD

**Issue by MOGRPHXZ** [ignacionelson/ProjectSend#390]
Hi
I'm trying to use Projectsend with large videofiles. Everything goes well when i upload via the website interface but when i use the find orphan files function after i copied a large file into the files folder , large files have the wrong filesize. For example a 4.5GB quicktime displays as a 524.1 MB file. Size is the same when i try to download that file. 

version R754

**Comment by MOGRPHXZ** [comment]
Correction, after uploading a 37GB videofile through the interface that shows as a 1.26GB file also

**Comment by lenamtl** [comment]
This is a huge file.... Soon or later you will encounter issue with the server.
I don't recommend to upload huge files.

**Comment by MOGRPHXZ** [comment]
i know its a huge file, but even with 4.5GB it doesn't work as expected I'm running 64bit WAMP server and changed the php.ini. While uploading the filesize of the selected file is correct. its when i look at managed files or orphan files its not as expected

**Comment by MOGRPHXZ** [comment]
changed to PHP version 7.0.10. that seems to do the trick
