### ISSUE TITLE
Role - client with admin rights in his/her group

### ISSUE THREAD

**Issue by barna119** [ignacionelson/ProjectSend#391]
A kind of superclient should have rights - only in his/her group - to ...
1. ... add/manage clients
2. ... add/manage categories
3. ... add/manage files

Just I want to mention, this is a great peace of software. Easy to use, easy to manage, and looks good.

**Comment by lenamtl** [comment]
Hi, I cannot see any situation for a client to manage other clients ...

Could you explain in which situation you need this?

**Comment by barna119** [comment]
There are several projects (Client groups) at a company. Every project has it's leader ("super" Client, or "group manager"), he manages the project participants (Clients in the group). Currently he could be an "Account Manager", but an Account Manager in ProjectSend can see/manage other projects (Client groups), which is too much power.

There are 3 system users
- System Administrator
- Account Manager (almost the same as System Administrator)
- Uploader (useless in my view)
and there is one user
- Client

I would prefer (at least) 3 user levels
- System Administrator
- Group Manager, or Super Client
- Client

This is a great system, and Client groups is a good idea. But IMHO a mamager role for a group is missing.

**Comment by lenamtl** [comment]
You are trying to have different Projectsend inside one.

So what I suggest to you, is to set one Projectsend installation per project, you will endup with less custom code. And you can always create a custom web page entrance with the project links.

**Comment by barna119** [comment]
I understand.

Why there are client groups? The same functionality can be obtained if you set one Projectsend installation per client group.

**Comment by lenamtl** [comment]
It's just to simplify some admin repetitive tasks (for system user not for clients)
System user upload one file for several clients that all.

Duplicating Projectsend will save you time, but if you have budget you can hire a dev to make all your custom needs.

But before giving admin role to your clients you should definitively think twice...
