### ISSUE TITLE
How to share a client a file to another clients in our group or client can assign?

### ISSUE THREAD

**Issue by sarkiroka** [ignacionelson/ProjectSend#396]
I have 2 client in a same group. The Client1 upload a file (and he can't categorize or select group) the other client Client2 can't access to uploaded file. 
How client1 could assing file to client2 which previously uploaded.

I guess the file which uploaded by Client1 in Group1 should be visible by Client2 (which in Group1)

**Comment by lenamtl** [comment]
This is not possible, only system user can do that.
There are already some discussions already about this subject so I close this for now.
