### ISSUE TITLE
not all strings can be translated

### ISSUE THREAD

**Issue by barna119** [ignacionelson/ProjectSend#398]
not all strings can be translated
e. g. "Get a new password" button translation is not available in Hungarian and Italian

"Download zipped" can be translated only Italian, not Hungarian

"Found: 9999 files" is not translatable either.

**Comment by lenamtl** [comment]
Some string may not be translated check with Poeditor

**Comment by barna119** [comment]
"Some string may not be translated"

Why is that 

#. Text in echo
#: templates/default/template.php:44
msgid "Download zipped"
msgstr "Scarica come compresso (ZIP)"

is available in the Italian .po but not in Hungarian .po?

**Comment by barna119** [comment]
Does this issue duplicate another one? Which one?

**Comment by lenamtl** [comment]
As you have opened several posts on the same subject, I kept only one open.
Every issues you have with language file is related to the PO that is not updated to the latest POT.
When you will fix this and translate the new strings all the problems you having will be fixed.

Also check other posts about language that may help:
https://github.com/ignacionelson/ProjectSend/issues/182
https://github.com/ignacionelson/ProjectSend/issues/188
https://github.com/ignacionelson/ProjectSend/issues/190
