### ISSUE TITLE
translation not works

### ISSUE THREAD

**Issue by barna119** [ignacionelson/ProjectSend#399]
Translated "all categories" at default templtes, still at "View my files" the English text appears.

"Client edited correctly." also does not translate (to Hungarian), although translated in .po (.mo) file.

**Comment by lenamtl** [comment]
Hi, 
You have to compile the language file using POeditor or use ready to use PS language file.
Sometimes Transiflex languages files are not uptodate.

**Comment by barna119** [comment]
"You have to compile the language file using POeditor"

I did that.

"Make sure the string are there and translated"

I did that.

"Sometimes Transiflex languages files are not uptodate."

I translated.

"Also make sure language is correctly set in config."

What means "correctly"? What language is correct for you?

"Please regroup your questions next time instead of opening different issue on similar subject"

These were different issues, so I reported clearly separately. Should I mix them next time into one?

So.  Translated "all categories" at default templates, still at "View my files" the English text appears. The text "Client edited correctly." also does not translate (to Hungarian), although translated in .po (.mo) file. What's next?

**Comment by barna119** [comment]
In the "view my files" list table header: "Name", "Desctiption", etc. are translated by the default language of the site, while "Ext." is translated by the client's language.

If you change in templates/default/template.php
&lt;th>&lt;?php _e('Title','cftp_template'); ?>&lt;/th>
&lt;th data-hide="phone">&lt;?php _e('Ext.','cftp_admin'); ?>&lt;/th>
&lt;th data-hide="phone" class="description">&lt;?php _e('Description','cftp_template'); ?>&lt;/th>
&lt;th data-hide="phone">&lt;?php _e('Size','cftp_template'); ?>&lt;/th>
&lt;th data-type="numeric" data-sort-initial="descending">&lt;?php _e('Date','cftp_template'); ?>&lt;/th>
&lt;th data-hide="phone" data-sort-ignore="true">&lt;?php _e('Expiration date','cftp_template'); ?>&lt;/th>
&lt;th data-hide="phone,tablet" data-sort-ignore="true">&lt;?php _e('Image preview','cftp_template'); ?>&lt;/th>
&lt;th data-hide="phone" data-sort-ignore="true">&lt;?php _e('Download','cftp_template'); ?>&lt;/th>

every 'cftp_template' to 'cftp_admin', then all will be translated to client's language.

**Comment by Invictaz** [comment]
@barna119 I have the same issue. I have the translated files from Transifex AND my own and they don't display correctly. This is most likely a regression as some versions ago it worked fine.

**Comment by lenamtl** [comment]
Hi check some of the solution I provided in this post.
https://github.com/ignacionelson/ProjectSend/issues/190
