### ISSUE TITLE
Large files cause "network reset by peer" error

### ISSUE THREAD

**Issue by colpaert** [ignacionelson/ProjectSend#40]
Everything works fine if the files are around 250Mb, if they're much bigger than this, I get an error during the download. The error is "network reset by peer".
It seems to be related to the execution limit of a php script (30s).

**Comment by lenamtl** [comment]
What is the limit of your server (PHP) and your limit settings in the projectsend config file?

**Comment by colpaert** [comment]
If you mean the MAX_FILESIZE in sys.config.php, it is set to 2048.
I see a post_max_size = "65M" in php.ini, but I don't know if this would
cause this issue (I cannot change this value in the host I use).

Is there anywhere else I should look for?

**Comment by lenamtl** [comment]
Here is what I found about this error:
http://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean

**Comment by crashff00** [comment]
I found a possible solution to the problem, but I'm not sure how to implement it for testing:
http://stackoverflow.com/questions/28023878/download-large-file-and-connection-reset-by-peer-mod-fcgid

**Comment by lenamtl** [comment]
Did you fix the problem?

**Comment by lenamtl** [comment]
I'll close this for the moment

**Comment by simar88** [comment]
Any news about this issue?
Thanks in advance,
Simone

**Comment by lenamtl** [comment]
@simar88 
Have you checked http://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean
