### ISSUE TITLE
garbled translation

### ISSUE THREAD

**Issue by barna119** [ignacionelson/ProjectSend#401]
In the "view my files" list

table header, Name, Desctiption, etc. are translated by the default language of the site, while "Ext." is translated by the client's language.

**Comment by lenamtl** [comment]
Make sure the default language it is set in configuration

**Comment by barna119** [comment]
"Make sure the default language is set in configuration correspond to the language you want"

I don't want any language. Client is free to chose his language. But only "Ext." is translated by the client's language. "Name", "Desctiption", etc. are kept as the default language, they don't translate to clien't language, like everything else.

This issue duplicates another one? Which one?

**Comment by lenamtl** [comment]
As you have opened several posts on the same subject, I kept only one open.
Every issues you have with language file is related to the PO that is not updated to the latest POT.
When you will fix this and translate the new strings all the problems you having will be fixed.

Also check other posts about language that may help:
https://github.com/ignacionelson/ProjectSend/issues/182
https://github.com/ignacionelson/ProjectSend/issues/188
https://github.com/ignacionelson/ProjectSend/issues/190
