### ISSUE TITLE
PHP7-Error: Blank Page - Declaration of PDOEx

### ISSUE THREAD

**Issue by mr-bluescreen** [ignacionelson/ProjectSend#403]
I have a problem regarding PHP7.

Last night my hoster updatet from PHP 7.1.3 to 7.1.4 and all of a sudden there was a blank page showing when trying to use ProjectSend.
After enabling PHP Errors the following message popped up:

`Thu May 04 22:48:35 2017] [warn] [client XXX.XXX.XXX.XXX] mod_fcgid: stderr: PHP Warning:  Declaration of PDOEx::prepare($statement) should be compatible with PDO::prepare($statement, $options = NULL) in /var/www/vhosts/abc.com/subdomain/includes/classes/database.php on line 13`

`[Thu May 04 22:48:35 2017] [warn] [client XXX.XXX.XXX.XXX] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to a member function query() on null in /var/www/vhosts/abc.com/subdomain/includes/site.options.php:18
`
(copied directly from server logs)

Together with my hoster we downgraded to PHP 7.0.18 with no difference. Downgrading to 5.6.30 showed that everything worked as normal, but the error is still visible above the page header.

I hope you can help me!

Greetings,
Tim

**Comment by ignacionelson** [comment]
Fixed!
