### ISSUE TITLE
[REQUEST] Send username and password in each notification email

### ISSUE THREAD

**Issue by uussaammaahh** [ignacionelson/ProjectSend#405]
@lenamtl @ilackskills Can this be done? When I select multiple clients while sending files. The notification email which goes to the client should also contain the specific username and password of each specific client every time I upload files and assign them to clients.

For example, something like this:
<img src="http://i.imgur.com/vQRLxre.png" />

**Comment by lenamtl** [comment]
Why sending this info every time this is no making sense to me...
I don't recommend to do this for security reason, but you can always hire a dev for your custom needs

**Comment by uussaammaahh** [comment]
Just tell me if it's possible or not? Then only I'll try looking for a dev.

**Comment by ignacionelson** [comment]
Hi @uussaammaahh 
It won't be possible, as passwords are encrypted on the database and therefore are not available to send after that first email, where the value is taken from the user input directly.

A dev could change the way this works for you, but security will decrease exponentially and is not recommended at all.

**Comment by uussaammaahh** [comment]
@ignacionelson Thank you for your positive reply. Love your work by the way! And all those who have helped in this project 👍
