### ISSUE TITLE
Change BASE_URI to https

### ISSUE THREAD

**Issue by txnet1** [ignacionelson/ProjectSend#407]
I'm trying to use https but no css or images are displayed. I have read through the other posts but i am not seeing how to change. All i want to do is use https. any ideas?

**Comment by txnet1** [comment]
never mind. found an easy solution. just change the BASE_URI in the database. everything starts working.

**Comment by ignacionelson** [comment]
No need to change it directly on the db, on the options page you can change it also :)
Glad you find a solution anyway!

**Comment by txnet1** [comment]
omg where were you yesterday when i was scanning over every php page? lol ya your solution is way easier.

**Comment by ignacionelson** [comment]
At that time, sleeping i think lol.
Hope to be able to help you faster next time!
