### ISSUE TITLE
Public link download doesn't work - r842

### ISSUE THREAD

**Issue by remez** [ignacionelson/ProjectSend#409]
Hello,

When I try to download a public file with the link provided, I see the "File information" page where are reported the file name and the "Download File" button.
When I click on the "Download file" button, the page is reloaded without shows the file name and the download doesn't start.

In download.php file it seems that "download" routine (line 87) checks the existence of the "real name" ("original_url" field in tbl_files) of the file to download and not the "effective scrambled file name" ("url" field in tbl_files) of the file that is the real saved file in upload/files directory.

I modified the lines 89, 98 and 103 of download.php file to report the correct file name saved on the server and the download starts correctly.

Please check your download.php file and, eventually, correct it (I don't know how to make it here).

Thank you.

**Comment by remez** [comment]
This is my modification to download.php

`

				// DOWNLOAD
				$real_file = UPLOADED_FILES_FOLDER.basename($real_file_url);
				$random_file = UPLOADED_FILES_FOLDER.basename($random_file_url);
				if (file_exists($random_file)) {
					session_write_close(); 
					while (ob_get_level()) ob_end_clean();
					header('Content-Type: application/octet-stream');
					header('Content-Disposition: attachment; filename='.basename($real_file));
					header('Expires: 0');
					header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
					header('Pragma: public');
					header('Cache-Control: private',false);
					header('Content-Length: ' . get_real_size($random_file));
					header('Connection: close');
					//readfile($real_file);				
					$context = stream_context_create();
					$file = fopen($random_file, 'rb', FALSE, $context);
					while ( !feof( $file ) ) {
						//usleep(1000000); //Reduce download speed
						echo stream_get_contents($file, 2014);
					}			
					fclose( $file );
					die();
				}
`

**Comment by kwadrat** [comment]
The same problem was in my case. I created Pull Request to solve the problem:
https://github.com/ignacionelson/ProjectSend/pull/411

**Comment by ignacionelson** [comment]
I merged the fix by @kwadrat and it solved the issue :)
Thanks!

**Comment by dipenpatel235** [comment]
Hello..
Download File is fixed but still issue there it is download file as download.php instead of given file name.

Thanks

**Comment by ignacionelson** [comment]
I'm not having that issue :/
Is the file correct other than the name?

**Comment by dipenpatel235** [comment]
ok...then no problem.
i have clone your new code instead of patch code.
and work fine now

**Comment by ignacionelson** [comment]
Great, thanks for the heads up!!
