### ISSUE TITLE
Issues with create and download archive zip file - r842

### ISSUE THREAD

**Issue by remez** [ignacionelson/ProjectSend#410]
When I try to create and download an zip file clicking on the checkboxes at the side of the files, select "Download zipped" on the dropdown menu at the upper right side, then click "proceed", I see the "Please wait" Windows but nothing happens.

It's necessary to create the directory "tmp" under the root dir of the site...

If the archive created is big (I tried with a 1.3GB archive), the temp file is created but the file downloaded is 0 bytes long.

If the archive is small the file downloaded is ok

I made some modification to process-zip-download.php /starting from row 122) so all works correct:

`

	if (file_exists($zip_file)) {
		$zip_file_name = 'projectsend_'.date('Ymd-His').'.zip';
		session_write_close(); 
		while (ob_get_level()) ob_end_clean();
		header('Content-Type: application/octet-stream');
		header('Content-Disposition: attachment; filename="'.$zip_file_name.'"');
		header('Expires: 0');
		header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
		header('Content-Length: ' . get_real_size($zip_file));
		header('Pragma: public');
		header('Cache-Control: private',false);
		header('Connection: close');
		$context = stream_context_create();
		$file = fopen($zip_file, 'rb', FALSE, $context);
		while ( !feof( $file ) ) {
		//usleep(1000000); //Reduce download speed
			echo stream_get_contents($file, 2014);
		}
		fclose( $file );
		unlink($zip_file);
	}
`

**Comment by lenamtl** [comment]
More than 1 gig this is really huge file!!!
You may get other issue like server crash or corrupt data...

**Comment by ignacionelson** [comment]
Oh that's great! I've wanted to replace the readfile function with stream for a long time, and I always forget about it!

**Comment by rpjludeke** [comment]
I'm on version r859 - also experiencing issues with downloading a zip file. I created a `tmp` directory, but still nothing happens. Any solution would be appreciated

**Comment by ignacionelson** [comment]
Solved on commit c86b939
Thanks for your help!
