### ISSUE TITLE
Site doesn't work anymore after upgrade to a newer version than r842

### ISSUE THREAD

**Issue by remez** [ignacionelson/ProjectSend#412]
Hi all,

I upgraded my working version r842 with newer versions in master branch but, when I try to open the site, I don't have the login page but a blank page.

If I try to reinstall from scratch with a newer version than r842 (without database and includes/sys.config.php created and configured), I have errors http 500.

I have configured permissions and owner of the files and directories same as I have configured in r842.

If I revert to r842 all works.

This is my configuration:

SOFTWARE
Version r842
Upload max. file size 2048 mb.
Template Default
Files 0
Clients 0
System users 1
Groups 0

SYSTEM
Server Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16
PHP version 5.4.16
Memory limit 128M
Max execution time 14400
Post max size 8M

DATABASE
Driver mysql
Version 5.5.52-MariaDB

Thank you

**Comment by lenamtl** [comment]
This is normal because the newer version is very different from old version (BD changes, pw encryption change new features ect).
For version r608 and later you will need to enable PDO extension from php.ini
You will need to upgrade to php 5.5+

What you can do is make a new clean installation then make it work ok on your server than compare database and map the data or just recreate the user with new pw then start from scratch no files.

**Comment by remez** [comment]
I'm sorry, I have writtet the wrong release. The right release is r842 and not r482...

**Comment by ignacionelson** [comment]
sorry to read this :(
r842 is not an official release so there are parts that are not finished yet, and unexpected results might appear.
Can you enable debug mode in sys.vars.php and see if you get any error please?

**Comment by remez** [comment]
Ok, I have upgraded my test intallation from r842 (that works) with r582 and enabled the debug (I've learned something new today :-) )

When I try to connect to my test installation, in my /var/log/httpd/error_log I have this error:

[Thu Jun 01 10:50:14.870939 2017] [:error] [pid 13905] [client XXX.XXX.XXX.XXX:52677] PHP Parse error:  syntax error, unexpected ')', expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in /var/lib/nethserver/vhost/projectsendtest/includes/classes/send-email.php on line 44

( /var/lib/nethserver/vhost/projectsendtest is the path where i have my installation test)

And the page returns HTTP error 500 (With Google Chrome)

Thank you

**Comment by remez** [comment]
Maybe can help this?

https://stackoverflow.com/questions/18863625/parse-error-syntax-error-unexpected-expecting-t-paamayim-nekudotayim

The second answer

**Comment by ignacionelson** [comment]
This was driving me crazy, as my php editor was showing errors on that line, but the app worked. You saved me a few headaches! Thanks!

**Comment by remez** [comment]
Hi, I think I made a mistake...
You using "!empty" to check if the parameter was empty or not.
"defined" works in reverse mode, it's check if the parameter exist (not empty) or not (empty)

So, in schematic mode:

If the parameter is empty/not existant:  empty=true  defined=false
If the parameter is not empty/existant:  empty=false  defined=true

So, I think that in the rows 44 53 62 75 92 102 the correct fucntion must be  "defined"  and not "!defined".

But I don't know very well PHP so I could be writtek stupid things...

**Comment by ignacionelson** [comment]
You are right :D Thanks again! it's fixed now.
