### ISSUE TITLE
ProjectSend r754 - IDOR & Authentication Bypass Vulnerability 

### ISSUE THREAD

**Issue by remez** [ignacionelson/ProjectSend#413]
Hi,

I found this article about a vulnerability disclosure in r754.

http://seclists.org/fulldisclosure/2017/Feb/58

It's already fixed?

**Comment by ignacionelson** [comment]
It was already fixed a few weeks ago. Thanks for reporting anyway!

**Comment by attritionorg** [comment]
Can you please link to the fixing commit @ignacionelson? Thanks!

**Comment by ignacionelson** [comment]
https://github.com/ignacionelson/ProjectSend/commit/e4b9ef6526656a6d53aee061f57109b5635cc61f

That's it :)

**Comment by attritionorg** [comment]
Excellent, thank you!
