### ISSUE TITLE
r859: Doesn't create correctly tbl_options if installed from scratch

### ISSUE THREAD

**Issue by remez** [ignacionelson/ProjectSend#415]
Hi,
I have a issue installing r859 from scratch: in "tbl_options" some fields aren't created (ad example: footer_custom_enable and footer_custom_content).
If you try to customize the footer you can't (the field is already populated with a "CUSTOM_FOOTER_SOMETHING" and any modify isn't saved).

Workaround:
Close the site, put the value  754  in the field "last_update" in the table "tbl_options", restart the site. You will see a message that the database was updated.

The custom footer filed in option list now is empty and the options are saved.

Please note that if you leave the custom footer field empty, when you save, the site "whining" that field is empty...

Ciao

**Comment by ignacionelson** [comment]
Thank you!! I've uploaded the fix now :D
