### ISSUE TITLE
E-mail notification couldn't be sent.

### ISSUE THREAD

**Issue by Syedwaheed** [ignacionelson/ProjectSend#416]
When ever i try to signup a client or either project email notification couldn't be sent. I have mentioned my gmail account in option for email and also i m on local host. Any help would be appreciated thanks.

**Comment by Syedwaheed** [comment]
Can anyone help me about it?Amazed to see no one has yet commented on it.

**Comment by remez** [comment]
Please try with

Mailer: SMTP

Username: your gmail username (usally your gmail address)
Password: your gmail password

Host: smtp.gmail.com
Port: 465
Authentication: SSL

Also check this document:  https://support.google.com/accounts/answer/6010255?hl=en  and try to enable "Less secure apps" option.

**Comment by Syedwaheed** [comment]
its works for me now. Thanks alot @remez .

**Comment by remez** [comment]
I'm glad that works for you!

Please note that gmail usually rewrites the sender address (Option -> "FROM" Information -> e-mail address) with the mail address you used to authenticate on their smtp.

**Comment by Syedwaheed** [comment]
One more thing i need to know that when i select the logo from branding in option menu. My logo is not showing up on any of the place i.e index page or other pages. Do you have any idea about it?

**Comment by NareshAdapala** [comment]
E-mail notification couldn't be sent.
i am getting this i am using 
server godaddy 
PortNo: 465
Mailer:  smptp
host : smtpout.secureserver.net 
Ahuthintication : SSL
