### ISSUE TITLE
Issue with manage-files.php

### ISSUE THREAD

**Issue by RichH1978** [ignacionelson/ProjectSend#42]
Using r582, We were having an issue with deleting files which seems to be similar to that described in bug #29.

Having investigated the issue, it appears to be caused by using id instead of file_id on line 527 of manage-files.php

Change made on file 527 of manage-files.php:
$file_id = $data_file['file_id'];

Issue will only appear if the file_id and relation id are not the same.

**Comment by lenamtl** [comment]
Hi,

In which case the file_id and relation id are not the same?

**Comment by RichH1978** [comment]
Yes, the file_id and relation id may not be the same. For instance if a file is assigned to 2 users, there would be 1 record in tbl_files and 2 records in tbl_files_relations. 
The file id would be 1
The relation ids would be 1 and 2

So depending on which user was viewing the file, the relation id would either be 1 or 2

If the first user tried to delete the file, it would work using the relation id as it is the same as the file id.
If the second user tried to delete the file, the system would report the file was deleted but not delete the file as no file id of 2 exists.

If you have more files on the system this could cause problems because a file id of 2 may exist and would be deleted rather than the correct file id of 1.

**Comment by lenamtl** [comment]
OK thanks your fixe seems ok.
I have also test with Group and Group + individual Clients and seems to be ok.
Any other cases we should check?

**Comment by AlanReiblein** [comment]
The delete worked but the log reported the wrong file as deleted
any ideas

**Comment by AlanReiblein** [comment]
Sorry I am now confused
Did the fix of changing I'd to file_id which appeared to work but then noticed it reported wrong info into log. So reverted back.
Looked at the fix : delete files ... 

but the comments on that appear to say it doesn't work.

Do I apply both ?

**Comment by AlanReiblein** [comment]
I have done this on a test system replicating my database.
The log definitely reports wrong file and only 1 file is deleted if you select multiple.

Also how do I change the (max) number of files viewed at any time (I have over 400 files and it seems to take forever in manage files for an admin to see the page  (on my test system)

**Comment by AlanReiblein** [comment]
Found change for number of files viewed

**Comment by eoffermann** [comment]
I was having several problems that currently appear to have been fixed by making this patch. I'm running r582 which didn't contain this fix.

Files weren't being deleted when instructed (Recent Activities would show the item as being deleted, but it would still be present), the wrong files were being deleted (same as above - the right files would be listed as deleted, but different ones were actually deleted), etc. 

I'm not sure what changed on r582 to address the wrong files being deleted problem, but it didn't fix it for me. Applying the fix listed in this thread seems to have done it though.

**Comment by lenamtl** [comment]
Please update to r583, there are a lot of security fixes, do a full backup file and DB prior the update.

There are 2 differents problems
1- sometimes the file was not deleted (depending of the case), this has been fixes.
2- when deleting multiple files at the time (depending of the case) that was not logged correctly, this has not benn fixed yet.

**Comment by lenamtl** [comment]
Please update to the latest version and let us know if still need help
