### ISSUE TITLE
Menu Bar doesn't work on Dashboard page

### ISSUE THREAD

**Issue by mikaelmantel** [ignacionelson/ProjectSend#426]
Hi,

When i use an admin account, after log in, the dashboard show up, but all the buttons in the Menu Bar (File, Clients, Clients groups) doesn't work.
I have to go on my account page for using the Menu.

It's a bug or just a problem with the configuration ?

Thank you.

**Comment by ignacionelson** [comment]
Looks like you are getting a javascript error that prevents the rest of it from executing.
Your browser's console should give you the exact error. Can you please paste it here so I can look into it?
Also, what version are you using?

**Comment by mikaelmantel** [comment]
I have an http error 500, but i don't know why.
i'm using the version 754.

I have a another issue : this morning, the home page doesn't load (the source code empty).
After some research, i modified the value of version_last_check in the db and it work for now.
I think the 2 problems are link, but i don't know why.

Thank you.

**Comment by olimax** [comment]
same problem
Error is: 
"TypeError: u is undefined"   jquery.flot.resize.min.js:19:668

**Comment by olimax** [comment]
This seems to have fixed itself for me after a restart. It may have been a problem with a cookie from an older version.

**Comment by mikaelmantel** [comment]
Not for me :)

**Comment by ignacionelson** [comment]
Updating jquery flot solves the problem.
Done on 9bad43a
