### ISSUE TITLE
Role: Assign admin/manager to group

### ISSUE THREAD

**Issue by olimax** [ignacionelson/ProjectSend#428]
It would be a great help to be able to assign either an admin or account manager to a group. 
Currently upload alerts being sent to the admin email could then, instead, be directed to the group admin.
Perhaps even limit file management to whatever groups were assigned to the manager.

**Comment by kkplein** [comment]
Yes, agreed fully!

**Comment by lenamtl** [comment]
please see #391

**Comment by olimax** [comment]
Shame. It would make it a far more professional tool. 
The main issue for me is limiting or specifying the incoming alerts but each to his own.
I'll have to open the bonnet and see what I can do

**Comment by ignacionelson** [comment]
Not possible right now. I'll be looking into limiting users to certain clients soon, and maybe I could add something so notifications in that case go to that user too. Groups would be more complicated, but I'll keep it in mind. Thanks!
