### ISSUE TITLE
Move file store location.

### ISSUE THREAD

**Issue by k33fy** [ignacionelson/ProjectSend#43]
Hi,

Currently using r582 and everything going really well. Looking ahead I think we will need to place our \Upload\Files location to another datastore which would be presented as another drive letter. 

Can anyone give me advice on what and where I would need to change to enable this within Project Send ?

Thanks,

Keith.

**Comment by mriolo** [comment]
It looks to me like the file uploads paths, UPLOADED_FILES_FOLDER and UPLOADED_FILES_URL  are defined in sys.vars.php on lines 83-84.  You can try editing these paths to reflect your desired path.  To move the uploads outside your current PS app structure, you will need to create a virtual directory path to the uploads and specify that on line 84. You will also need to ensure proper permissions on the containing folder for whatever account the web server is running under.

**Comment by mkaand** [comment]
Symlink doesn't solution for latest version. I have same issue. I changed sys.vars.php and I try making upload folder as symlink doesn't help. I am looking for solution.
