### ISSUE TITLE
unable to login after installation

### ISSUE THREAD

**Issue by jmvermillion** [ignacionelson/ProjectSend#430]
I have set up a new instance of ProjectSend, gone through the installation process, and created the initial admin account.

I have verified that the user was created in the database.

When I attempt to log in, I am just looped back to the login page. No errors. If I type an incorrect password, it tells me that the credentials are invalid.

I have tried this in Safari, Firefox, and Chrome. It seems like it may be some kind of session issue, but I'm at a loss as to how to fix it.

**Comment by ignacionelson** [comment]
Hello! I see you closed the issue. What was the problem?

**Comment by jmvermillion** [comment]
I was just typing a comment here as you asked. :)

I had the instance behind a Cloudfront GLB, and forgot to enable header and cookie forwarding.
