### ISSUE TITLE
White labeling emails

### ISSUE THREAD

**Issue by olimax** [ignacionelson/ProjectSend#431]
Without wishing to undermine the project I notice that there are references in the Welcome emails to ProjectSend.
If possible these could be replaced with the the given site title .
Near the top you'd need to add :
`require_once(ROOT_DIR.'/includes/site.options.php');`
the swap out 'ProjectSend' with THIS_INSTALL_SET_TITLE
eg
`body3'			=> __('Thank you for using ' . THIS_INSTALL_SET_TITLE,'cftp_admin'),`
There are 3 instances of this
just a thought

**Comment by ignacionelson** [comment]
The full email template can now be configured :)
