### ISSUE TITLE
HTML output from CK editor shows tags

### ISSUE THREAD

**Issue by olimax** [ignacionelson/ProjectSend#432]
The HTML output from CK editor shows tags in a couple of instances which need decoding

upload-process-form.php
line 314
`<td><?php echo html_output($uploaded['description']); ?></td>`
should be
`<td><?php echo htmlentities_allowed($uploaded['description']); ?></td>`

Pinboard template
line 200
` <?php echo $file['description'] ; ?>`
should be
` <?php echo htmlentities_allowed ($file['description']); ?>`

There was a third instance but for the life of me I cant recall now where I changed it. I'm sure I will

**Comment by olimax** [comment]
also upload-send-notifications.php     line 81
`'description'	=> $row['description']`
to
`'description'	=> htmlentities_allowed($row['description'])`

**Comment by ignacionelson** [comment]
I've just uploaded your fixes, thanks!!!
