### ISSUE TITLE
Security issue on login page

### ISSUE THREAD

**Issue by Fraddy** [ignacionelson/ProjectSend#436]
If an email address and a random password is entered on login, the login fails nicely. However, when the email address was valid the associated user name is returned on the login page. We consider this a serious security issue, because internal information is leaked.

Failed logins should return the literal keyed-in information or otherwise a blank username/email field. By testing some email addresses, hackers can test for the presence of user accounts and also obtain valid user names.

For better security, we altered index.php to remove the value with the username/email input.

**Comment by ignacionelson** [comment]
Hello @Fraddy ! And thanks for your report.
I'll change the form so the field displays the data sent by the user, and not what returns from the database.

**Comment by mschop** [comment]
Issue seems to be resolved. Closing this issue.
