### ISSUE TITLE
Suggestion: client can delete the file they upload

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#44]
Only Admin and Account Manager can delete file.
Uploader and Client cannot delete file.

Client and upload should at least delete the file they upload.
Let say a client have uploaded the wrong file, there is no way for him to delete the file...
Let say there are sensitive data in this file...

We could add a settings for this 
so admin can decide who can delete file.
For all file or only the file the user upload.

**Comment by ignacionelson** [comment]
Fixed. Added an option to allow clients to delete the files they've uploaded on commit e92d1bf
