### ISSUE TITLE
Category Filters Don't See Child Categories Without Parent

### ISSUE THREAD

**Issue by pixelbakery** [ignacionelson/ProjectSend#440]
Maybe I'm doing something wrong, but it looks like if you only assign a child category to a file it won't appear as a category option when the client tries to filter by category. Has anyone else had this issue?

**Comment by ignacionelson** [comment]
Thanks for your report!
This has been fixed but an official release is not available yet. it will be during the course of august :)

**Comment by pixelbakery** [comment]
Awesome!

**Comment by megasailor** [comment]
I see this is old, but it recently came up... Still seems to be an issue. I have written a quick fix for it, via the *arrange_categories* function (checking against all found parent ids), but just wondering when an official fix was going live?
