### ISSUE TITLE
Tabs not working

### ISSUE THREAD

**Issue by Oblivii** [ignacionelson/ProjectSend#449]
For some reason after installing successfully, clicking any of the tabs except for Dashboard do not work. I can not click files, clients, clients groups, etc.. I can however click my account, and logout. Is there a fix for this, or any reason I'm having this issue?

**Comment by olimax** [comment]
sounds like a javascript issue
have a look in the JS console and see what errors you are getting

**Comment by Oblivii** [comment]
I guess that makes a lot of sense, I don't have Java installed on the server. Can anyone recommend how to set that up, I'm not familiar with java.

**Comment by ignacionelson** [comment]
Hello! Java is not necessary, javascript (a different language but similar name) is already running on your browser. To see the error you need to open the console on your browser (by hitting f12). If you see anything that reads error, warning or similar, please paste it here.

**Comment by Oblivii** [comment]
Firefox seems not to work, IE did not work at all till I clicked my account, and now the tabs are working ONLY for IE. Here is the error.

HTML1500: Tag cannot be self-closing. Use an explicit closing tag.File: users-edit.php, Line: 39, Column: 2HTML1500: Tag cannot be self-closing. Use an explicit closing tag.File: users-edit.php, Line: 42, Column: 2

**Comment by Oblivii** [comment]
Here is a web link to the website with test user info!
http:/www.dretchstorm.com/share
Username: testuser
Password: test1234

**Comment by Oblivii** [comment]
BUMP!

**Comment by olimax** [comment]
It appears that you are not loading any JavaScript at all except jquery
I'd guess that your install is not complete
Compare it to the files here or just reinstall the whole thing via FTP

**Comment by Oblivii** [comment]
Seems like that fixed the problem. Now I'm having a issue with thumbnails not showing up.
