### ISSUE TITLE
remove : provided by projectsend version r754 - free software

### ISSUE THREAD

**Issue by romeo2482** [ignacionelson/ProjectSend#453]

**Comment by thehouseofho** [comment]
You can remove this yourself. It's in the functions.php file.

**Comment by romeo2482** [comment]
Dear Sir,

I tied to edit the above mentioned file and still i couldn't remove it,
could you please help me more.

regards,
Georges

**Comment by ignacionelson** [comment]
No problem!
If you are using r7xx, the open that file and look for line 472 which should start like this:
<?php _e('Provided by', 'cftp_admin'); ?>
Delete the WHOLE link or replace it with your custom text :)

**Comment by baloninitish** [comment]
Unable to remove : provided by projectsend version r754 - free software
