### ISSUE TITLE
RESULTS_PER_PAGE pagination bug in default template

### ISSUE THREAD

**Issue by olimax** [ignacionelson/ProjectSend#457]
There is a problem with the pagination in templates/default/template.php if you change RESULTS_PER_PAGE in includes/site.options.php, as I did 

In templates/default/template.php Limit is defined on line 13 here
`define('TEMPLATE_RESULTS_PER_PAGE', 10);`

Whereas pagination uses RESULTS_PER_PAGE, line 328
`'pages'		=> ceil( $count_for_pagination / RESULTS_PER_PAGE ),`

Either change L.13 to 
`define('TEMPLATE_RESULTS_PER_PAGE', RESULTS_PER_PAGE);`
OR
change 328 to 
`'pages'		=> ceil( $count_for_pagination / TEMPLATE_RESULTS_PER_PAGE ),`

Probably the former might be the one

It might be an idea to have the limit in the options to be able set the default value from the CMS too but not important

**Comment by ignacionelson** [comment]
Thanks! Fixed on a49e248
