### ISSUE TITLE
statistic graph: wrong data

### ISSUE THREAD

**Issue by IronKingPin** [ignacionelson/ProjectSend#462]
Hi,
the download graph shows a wrong number of downloads. I am using the current available beta.

![statistic_graph](https://user-images.githubusercontent.com/12882936/29964183-8c75fe5a-8f09-11e7-8cbe-c3eec68b89fd.PNG)

![phpmyadmin](https://user-images.githubusercontent.com/12882936/29964379-2c53fbde-8f0a-11e7-83a4-357d4f758680.PNG)

in 01/09 two downloads are done, but 11 are shown in graph. I think the problem comes from the statistics.php - any help are welcome, thanks!

**Comment by rjaletzki** [comment]
As of 427fc6c the downloads are not grouped by their dates but by their exact timestamps, which generates multiple results per day and results in graph data like
`var d8 = [[1503266400000,0],[1503352800000,0],[1503439200000,1],[1503525600000,0],[1503612000000,0],[1503698400000,0],[1503784800000,0],[1503871200000,0],[1503957600000,0],[1504044000000,0],[1504130400000,0],[1504216800000,11111111111111111111111],[1504303200000,1111111111111111111111111111111111111111111111111111111],[1504389600000,1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111],[1504476000000,1111111111111111111111111111111111111111111111111111111111111111111111111111111111]];`
Reverting this commit (adding DATE again) works for me but I don't know if that results in other issues.

**Comment by ignacionelson** [comment]
Thanks! I've just reverted the change.

**Comment by ignacionelson** [comment]
Fixed!
