### ISSUE TITLE
Sorting files by title in client view

### ISSUE THREAD

**Issue by rjaletzki** [ignacionelson/ProjectSend#465]
Sorting files by title (which is also supposed to be the default order) in client and uploader view (e.g. `/my_files/?client=...&orderby=filename&order=asc`) does not work as expected. It's working fine for system users at `/manage-files.php?orderby=filename&order=asc`.
![image](https://user-images.githubusercontent.com/16937760/30052130-d209179a-9224-11e7-80d0-5cec184d8ed3.png)

**Comment by ignacionelson** [comment]
Looks like it's always ordering by date, it just changes the asc or desc order, thanks for the report, will look into this

**Comment by ignacionelson** [comment]
fixed on 3a085fa
Thanks!

**Comment by suhajda3** [comment]
Seams to be broken again with r1295.

By supplying the arguments (?orderby=filename&order=asc) to the URL it works but clicking on Title it doesn't.
