### ISSUE TITLE
'Download zipped' not working

### ISSUE THREAD

**Issue by rjaletzki** [ignacionelson/ProjectSend#471]
The 'Download zipped'-option in client-view does not work. It's generating a url like `/my_files/?client=...&action=zip&select_all=0&files%5B%5D=35&files%5B%5D=34&files%5B%5D=33&files%5B%5D=32&files%5B%5D=30&files%5B%5D=31&files%5B%5D=29&files%5B%5D=27&files%5B%5D=28&files%5B%5D=25&page=1` which just loads the same page without offering a download.

I have also been unable to find a way to download all files as a zip at once if there are more then 10 files (multiple pages).

**Comment by kokya** [comment]
I had experienced the same issue and to solve this I increased memory_limit value in php.ini.
For work the total size of all files must be within this value.

**Comment by ilakskill** [comment]
@lenamtl I am seeing the same issue on GitHub version

Apache version 2.4.18
MySQL version 10.0.34
PHP Version 7.0.25
define('CURRENT_VERSION', 'r1022');

memory_limit | 1008M

## Default .htaccess file
<FilesMatch "\.(?i:zip)$>
AddType application/octet-stream zip 
</FilesMatch>

**Comment by ignacionelson** [comment]
Fixed!
