### ISSUE TITLE
Uploaded file does not appear in Manage Files

### ISSUE THREAD

**Issue by jamilredhat** [ignacionelson/ProjectSend#475]
Hi,

I am running ProjectSend on Linux server 64bit. I uploaded a 90GB file and file uploaded successfully and took 12 hours to upload. But after upload it does appear in the files list. This is important for auditing purpose. 

Apart from the problem above, I have a question. Does ProjectSend has resume feature. Means if network disconnects will upload resume automatically? If not can it be done by increasing some timeout values?

Thanks,

Jamil

**Comment by ignacionelson** [comment]
Hello Jamil!
After the file finished uploading, did you get the form to set a name, description, category, etc?
Also, have you checked if it's on the orphan files page?

Resuming is not supported at the moment, but timeouts should not be a problem as files are uploaded in chunks. Uploads are made via a script called Plupload. According to their docs, they are working on a build that could are resuming failed downloads.

**Comment by jamilredhat** [comment]
Thanks for the quick response. Yes file is present in "orphan files". And did not get the form after file upload. Is it because file took 12 hours to upload?

**Comment by ignacionelson** [comment]
Honestly, I've never received reports of uploading files that large, so I couldn't say. 
But if you edit it from the orphan files list, you should be able to treat it as a finished file.
After that, can you please download it through PS to see if it was really uploaded ok? Thanks!

**Comment by jamilredhat** [comment]
Thanks for your response. 
File uploaded without corruption. I checked it with MD5 hash.
