### ISSUE TITLE
Multiple Vulnerabilities

### ISSUE THREAD

**Issue by security-prince** [ignacionelson/ProjectSend#484]
Hi, is it mendatory to create a issue in order to report vulnerabilities in Projectsend because i have emailed you the details of multiple Vulnerabilities i have found in r754 and r963 on the email address provided in the website, but no response yet. Please let me know the procedure for reporting vulnerabilities.

**Comment by SimonWellborne** [comment]
Hello,
As a concerned user of ProjectSend, if you've identified vulnerabilities and had no response from the dev (and he might be busy/otherwise occupied), then I'd personally prefer to see them posted publicly.  If for no other reason than it gives us a chance to remediate the issues ourselves.

I can understand the hesitancy to publicly post them though.

Selfishly, and if you are willing, I wouldn't mind a PM with your observed vulnerabilities so that I can fix my own installs :-)

**Comment by ignacionelson** [comment]
Hello and thanks for your interest!
I haven't received any emails from someone with your username or maybe I have accidentally deleted it when selecting multiple spam messages.
Please send them again to contact@projectsend.org, I will work on a fix as soon as possible.

**Comment by security-prince** [comment]
Hi @ignacionelson the email id is shaikhishaq201@gmail.com and the Subject is Responsible Vulnerability Disclosure: Multiple Vulnerabilities, please let me know if you still don't find it in your inbox I will email the details again.

Thanks

**Comment by security-prince** [comment]
@SimonWellborne I understand your concern but I am sorry mate I can't disclose it without the permission of the owner. Hope you understand

**Comment by kantium** [comment]
Hello, same here, I contacted you about an vulnerability I found on the r756 on your email info@subwaydesign.com.ar (ProjectSend vulnerability) last week.

**Comment by security-prince** [comment]
Hi @ignacionelson any updates?

**Comment by ignacionelson** [comment]
Please resend you emails, I don't have them on inbox. Sorry :(

**Comment by kantium** [comment]
@ignacionelson Done ;-)

**Comment by ignacionelson** [comment]
Great! Just got your email, I'll work on this and update this issue when it's solved. Thanks!

**Comment by security-prince** [comment]
Hi kindly let me know on which email address should i send you the details?

**Comment by ignacionelson** [comment]
contact@projectsend.org please

**Comment by security-prince** [comment]
Sure will send the details in sometime, please acknowledge once you receive it.

**Comment by security-prince** [comment]
Hi, @ignacionelson  I have emailed you the details of the vulnerabilities.

**Comment by security-prince** [comment]
Hi @ignacionelson have you received my emails?

**Comment by security-prince** [comment]
@ignacionelson ??

**Comment by ignacionelson** [comment]
Sorry, but I didn't get any emails from you :( I did, however, get the report from @kantium 
Ânother option, if possible, send it as a message on facebook
https://www.facebook.com/projectsend/
There's no way to miss it there!

**Comment by security-prince** [comment]
Done, please let me know if you need any further information

**Comment by security-prince** [comment]
Hi @ignacionelson are you planning for new release with Security fixes?

**Comment by ignacionelson** [comment]
Yes. I'm finishing some touches on new functions, but I'm very close to have it ready. I've applied patches for the security issues that you've reported, and I also need to fix 2 more that are hanging around (reported by you and @kantium 
I wanted to have this new release ready for August, but I couldn't make it. The complexity of this new stuff delayed me.

**Comment by security-prince** [comment]
Hahaha delay happens mate, no issue and please keep me updated with it

**Comment by kantium** [comment]
Hello @ignacionelson 

I found a new critical vulnerability in ProjectSend r756, can you tell me if you received my email ?
Maybe @security-prince has already reported it, but if it's not the case I would like to make a little write-up about it here, when it's corrected.

Let's me know, and if you need more details or have a question, I'm here.

**Comment by security-prince** [comment]
Hi @ignacionelson any updates on the issues I reported?

**Comment by ignacionelson** [comment]
2 are solved :) Working on the rest now!

**Comment by security-prince** [comment]
great @ignacionelson thanks for the update :)

**Comment by security-prince** [comment]
Hi @ignacionelson any updates?

**Comment by security-prince** [comment]
Hi @ignacionelson  any updates?

**Comment by kkplein** [comment]
Yes, an update would be appreciated.

**Comment by ignacionelson** [comment]
Have you checked against the current github version? I believe that everything is solved. If not, please let me know so I can fix anything you find ASAP.

**Comment by security-prince** [comment]
Hi, should I test the version r756?

**Comment by ignacionelson** [comment]
Hello!
No, with current development version, that's always at
https://github.com/ignacionelson/ProjectSend/archive/master.zip

**Comment by security-prince** [comment]
Ok, i will try to test it and update you

**Comment by security-prince** [comment]
Hi @ignacionelson, I tested it and the vulnerabilities seem to still exist, I have sent the videos on facebook, please check it.

**Comment by ignacionelson** [comment]
Thanks for the update! Working on the fix!

**Comment by ignacionelson** [comment]
The new version contains the fixes. I can't thank you enough for your help!

**Comment by security-prince** [comment]
Hi @ignacionelson , it is always a pleasure to help.

**Comment by attritionorg** [comment]
Now that these have been fixed, can you link to the fixing commits and/or summarize the issues? Thanks!
