### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by bosscentral** [ignacionelson/ProjectSend#487]
Hi,
I have the following error during the installation:
There seems to be an error. Please try again.
Field 'address' doesn't have a default value

Thank you.

**Comment by wavemaster447** [comment]
I've had issues installing the new lastest package as well, getting white screen/no error message on install.php.

**Comment by ilackskills** [comment]
i think this is a known issue with php7, what are you running

**Comment by wavemaster447** [comment]
I originally installed on 7.1, then assumed that might be part of the issue and rolled back to 5.x (I think 5.6, the latest stable) - I still had the white-screen problem with no error message.

**Comment by ignacionelson** [comment]
Please enable debug mode by editing /sys.config.php, changing 
define('DEBUG', false);
to
define('DEBUG', true);

You should see the error messages instead of an empty screen

**Comment by ignacionelson** [comment]
Looks like this was fixed on the latest release
