### ISSUE TITLE
Save ID instead of the name

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#49]
Hi,
There are few places in the DB that the name is saved instead of the ID.

groups          created_by 
users            created_by 
members      added_by
actions_log   owner_user affected_file_name affected_account_name
files              uploader

**Comment by ignacionelson** [comment]
Yes, doesn't look good... but I remember doing this so, if the user is deleted, you can still see who it was that did the action (upload, created the group, etc). If you save the ID, and then delete the user, you won't know who it was.

**Comment by lenamtl** [comment]
ok I see.
I never delete user, I put them as deactivated state instead.
