### ISSUE TITLE
Improvements: How to install

### ISSUE THREAD

**Issue by adrianp-sti** [ignacionelson/ProjectSend#495]
https://www.projectsend.org/how-to-install-projectsend/

How to install should include a few more details, specifically whats bitten me:

* MariaDB did not work for me
* The following PHP extensions are needed:
  * zip
  * gd

**Comment by ignacionelson** [comment]
Thanks! I've added the php extensions reminder.
MariaDB not working is a surprise. What version did you use? Will need to test again!

**Comment by adrianp-sti** [comment]
If you want close down this ticket and I'll do some more testing of MariaDB on a clean install.  if I hit problems again I'll open a new ticket with version numbers etc. There was a stack trace displayed so I'll attach that as well if I can trigger it again.

**Comment by trainwreckjvbo** [comment]
I'm testing with MariaDB on Arch Linux, and it works like a charm :smile:

**Comment by ignacionelson** [comment]
@adrianp-sti Will do some testing on my part also, thanks!

@trainwreckjvbo Arch! <3
