### ISSUE TITLE
Bad character encoding - display error

### ISSUE THREAD

**Issue by richardradiohun** [ignacionelson/ProjectSend#496]
Hi!

I've experienced a bug in the current version and in r754. We Hungarians use a lot of accents. The customer-entered comment, filename in the administration interface (manage-files.php) is displayed perfectly, but unfortunately not on the client (/ my_files) interface. What could be the bug and could it be improved?

Thank you in advance, and I hope you understand what I have written, unfortunately I do not really speak English.

Regards: Richard

**Comment by trainwreckjvbo** [comment]
The current version is the r1022. This bug isn't related to the html charset?

**Comment by lenamtl** [comment]
Check this
https://github.com/ignacionelson/ProjectSend/issues/182
