### ISSUE TITLE
Sentences not avaliable on the translation file

### ISSUE THREAD

**Issue by trainwreckjvbo** [ignacionelson/ProjectSend#501]
The following ones with parentesis aren't avaliable on the translation file:
- Under E-mail Templates > "Client updated memberships"
- Under Templates > Templates > "The description of the templates"
- Under Tools > Actions log > Select tag "A client's group membership requests were processed."
- Under Options > Privacy > "PUBLIC GROUPS AND FILES LISTINGS PAGE" and all the checkboxes below
- Under any Add New > Checkbox "Send welcome email"

UPDATE:
- Files > Upload > In the table: "Filename", "Size" and "Status" columns

Perhaps there's more, because I haven't tested everything

**Comment by lenamtl** [comment]
You can add it manually to the .pot file
https://github.com/ignacionelson/ProjectSend/issues/249

Some string may be in language JS file of pupload...

**Comment by ignacionelson** [comment]
New strings are not always on the development versions. But the final release has them now :)
