### ISSUE TITLE
Filename with multiple dots

### ISSUE THREAD

**Issue by bmachek** [ignacionelson/ProjectSend#502]
Hi,

currently ProjectSend only keeps the last dot in a filename with multiple dots.
Is this wanted? If yes, can I  change it?

Cheers,
Bastian

**Comment by lenamtl** [comment]
Why do you want to keep multiple dots?
For a security reason this is not recommended to have more than one dot.

You can always change the naming function code to fit your needs.

**Comment by edmeades-lbto** [comment]
Can you elaborate on the security issue? We are dealing primarily with .tar.gz files, and it would be just that much more professional if our system didn't munge the filenames presented to our clients. I would be happy if dots were stripped unless that extension string were explicitly in the allowed extensions list, if that ameliorates concerns.

**Comment by lenamtl** [comment]
Hi, 

Can you still unzip the file if you remove .tar from the filename?
if not, in that case  .tar.gz is an exception and should be handle correctly by the system.

To my opinion the best way to handle file name is to rename the file with timestamp (so they are unique) and save the real file name in DB when user download the file it rename the file using the original name.
(this required custom code) so image.tar.gz will be renamed to 1526324124.gz and both file name 
1526324124.gz should be saved in DB as file name 
image.tar.gz should be saved in DB as original file name

Having multiple dot and other special character can cause a lot of issues, not only security issues. 

So if you allow multiple dots, the system should take the latest extension values after the last dot and validate if allowed, so if you block .exe file and someone upload image.jpg.exe this should not allow it ....

In any case you can change the rename function to suit your needs.
I don't remember how the system check the extension, this need to be tested if you change the rename function.

**Comment by duckbrain** [comment]
The "extension" is just a part of the filename saying what it contains. `image.tar.gz` means an image in the `tar` format, that's compressed with `gz`. You can chain multiple extensions to represent multiple container formats.  (We're specifically running into this issue with `.tar.xz`.

By renaming `image.tar.gz` to `1526324124.gz` the software is removing information about what type of data the file contains for the client.

The extension should never be separated from the file and the dots in the filename should be preserved. Dots are not a security issue with the exception of the file name segments of `.` and `..`, and in some cases other files that start with `.` (which represent hidden files in nix systems). If you want to strip something you can strip the leading dots. Generally project send strips many useful separators in filenames.

Also timestamps are not safe for uniqueness. UUID's are built for that purpose.
