### ISSUE TITLE
Projectsend broken?

### ISSUE THREAD

**Issue by ErikV2000** [ignacionelson/ProjectSend#513]
I have used projectsend on my website for about a year and everything was fine, until one day out of nowhere i couldn't login to my account anymore and i would instead have to wait over a minute and either get a timeout or a blank page which if you look at the source code in your browser is also completely blank.
Nothing within my projectsend got deleted, no critical file, i didn't make any changes to my web server or projectsend.  I have seen others have this bug too. I tried installing it fresh on my other website with exactly the same settings from my previous website where projectsend used to work and after installing projectsend i tried to log in and bam, it broke again, my username and password dont have any special characters so that shouldn't have been a problem. I have a theory, I think there is a memory leak somewhere within projectsend and the only way to explain why  projectsend just broke even tough i did nothing to it is most likely because of the news feed on the homepage, that seems like the most rational explanation to me, and yes trying to get to specific pages to avoid the homepage doesn't work...it also times out or gets the blank page. I will give you info: I am using cloudflare (no code interference)
Projectsend 754r and php 7.0, this is a huge problem if it affects other people, can you please fix it? and before you ask, yes i checked everything else that could interefere with projectsend but there isn't anything else that could've changed.

**Comment by rennounderscore** [comment]
sama proplem with me

**Comment by ignacionelson** [comment]
PS wasn't c ompatible with php 7. I can't confirm that everything works now but at least on the tests I did it seems to be ok.
