### ISSUE TITLE
Database Restore Problem -- PHP 5.5 to 7.0 Issue?

### ISSUE THREAD

**Issue by LaurenAdelle** [ignacionelson/ProjectSend#514]
I have an old server running Ubuntu 14.04 with the following key components:
• Apache 2.4.7
• Mysql 5.5.59
• PHP 5.5.9
• ProjectSend build 1022, upgraded from 754

The server is being retired and the projectsend information needs to be moved to a new Ubuntu 16.04 server with the following key components:
• Apache 2.4.18
• PHP 7.0.25
• Mysql 5.7.21

The basic Apache is serving projectsend clean install with no issues.   I logged in and logged out /etc.  The directory structure is the same (i.e. webroot, config files, ssl files, etc).

But then, I try to the following:
• use msyqldump to backup the database from the old server, and restore it to the new server
• straight SCP the file structure of project send (i.e. php files, uploads, client files, etc) exactly the same on the new server.
Now, when I try to login, I get HTTP Server ERROR 500 after I click "Login" and it shows the animated "Redirecting" image.

What is missing or how can I fix this?

**Comment by ignacionelson** [comment]
Looks like compatibility is fixed with php 7. At least on the tests I could do.
