### ISSUE TITLE
php 5.5 & r582 admin cant login

### ISSUE THREAD

**Issue by ichbas** [ignacionelson/ProjectSend#52]
I just upgraded to r582 and I went to switch my php version to 5.5 and as soon as i switch it over I can no longer login witht he admin account. Other people and users can login, just not the admin.

When i switch it back to PHP 5.3 everything works fine.

Any ideas?

**Comment by lenamtl** [comment]
It's working ok on 5.4.12
I have not test it on 5.5.

Here are the Backward Incompatible Changes between 5.4 and 5.5
http://php.net/manual/en/migration54.incompatible.php

**Comment by mriolo** [comment]
You could try changing the admin password to a simple password (like password) before the php upgrade, then see if it works and change to a strong password after.
Looking at the incompatibilities from 5.3 to 5.4 perhaps the changes to the php functions htmlentities() or htmlspecialchars() have changed the password hash for your current admin password...

**Comment by ichbas** [comment]
well I tried changing it to a simple password, then setting the PHP from 5.3 to 5.5 and still no luck. i even tried doing the password recovery while in 5.5 and changing the password... it accepted the change, but after trying to login it still just stays on the index.php page. I'm not getting any errors, like "the supplied  credentials are not valid", so i know the password is being accepted, but it just wont redirect to the logged in page for any user, not just the admin as I stated before.

**Comment by ichbas** [comment]
could this have anything to do with the commented line 27 and the fact that i have been using project sendfile for a long time now and passwords are probably in md5 hash?
//$sysuser_password = mysql_real_escape_string(md5($_POST['login_form_pass']));

**Comment by lenamtl** [comment]
Hi, 
I believe there will several code changes and tests before to use it under 5.5.
Not only the PW function is affected but good chance the session and other functions will also need to be modified.
The best solution for now is to downgrade to 5.4.12 or 5.3.

Also what was the previous version of Projectsend before the upgraded to r582?
Older versions of Projectsend like r412 use a different way to hash the PW and wont work if update to r582.

**Comment by ichbas** [comment]
Hey lenam, I upgraded from r561 I believe, but it was probably originally installed on r412. 

Unfortunately my hosting provider only offers PHP 5.3 and PHP 5.5, no php 5.4, so its either one or the other. I would like to upgrade to 5.5 because Im trying to install another program that requires higher than 5.3... stuck between two programs now.

**Comment by lenamtl** [comment]
Check with your hosting provider they often allow to have a php.ini in the root so with special code (they will provide) you can define the PHP code to use. So, if you have two project installations (different root or domain, maybe this work also with subdomain) you will be able to have two php versions on your plan.
It worth the try to ask them...

**Comment by ichbas** [comment]
unfortunately they only allow one php version per account. :(

**Comment by lenamtl** [comment]
I guess you will need a second account for now or use the new application offline on your PC.

**Comment by crashff00** [comment]
You can test the changes locally on your PC with Uniform Server. It's complete -portable- WAMP solution that is actually configured for live production use. They have anarchive of versions with various PHP builds integrated so you can check where the php break is.

**Comment by lenamtl** [comment]
Please try the new vesion
