### ISSUE TITLE
Working as sys-admin extrem slowly

### ISSUE THREAD

**Issue by gutenzwerg** [ignacionelson/ProjectSend#520]
If I am logged in as normal user everything works fine not to fast, but O.k. If I am logged in as sys-admin or other admin. Every new page is loading about 2 min and more. Even If I switch an account from admin to uploader. Every page takes 2 min and more. Could it be becaus at other points of handling I got the message that an e-mail could not be sent?
If I use the same name from an admin-account, do remove the admin-account and install as new user-accout everything works fine.
Any Ideas?
System is PHP Version 5.6.33-0+deb8u1
mySQL  5.5.59

Browser: Firefox

**Comment by gutenzwerg** [comment]
Version of ProjectSend is: r754
Tried other Browsers: Chrome and InternetExplorer. All the same.
I tried out lot's of different settings. Every time the same.

Nobody any ideas?

**Comment by ignacionelson** [comment]
Hello!
This is probably happening on pages with lists and pagination right? Manage files for example.
The pagination system used on that version is slow since it loads every results and divides the table via javascript. On the next version this has been changed. It will be available really soon.
Is it happening on other places too?

**Comment by gutenzwerg** [comment]
Thank You very much for the quick answer.
As far as I understand You. I would say no. If I am logged in with admin-rights every page-call lasts more than 2 min, no matter weather list's are on it ore not. Even logging out lasts as long.

**Comment by ignacionelson** [comment]
Oh that's weird.
Can you please check with your hosting service and ask them if you can get a log of slow sql queries? there might be something there that's delaying the whole system.

**Comment by gutenzwerg** [comment]
Thank you again for the quick response,
Puh, difficult to get. Because mysql is running here on a university-server, which is normally extremely fast. And why it should be so dramatical different between normal users and admins? I can see the information_schema-Tables of the database. Can I see there something like a log-file?

I meanwhile updated to r756 - no difference.
Anyway thank You for answering

**Comment by jgzgithub** [comment]
Do you have any idea when the pagination issue you mentioned above will be resolved?  It is unbearable when you have any number files of over 1000 it seems.

**Comment by ignacionelson** [comment]
The new version has this fix applied. Please give it a try!

**Comment by tomkuba** [comment]
@ignacionelson I have same problem with r1053. Before I reinstall - do you remember what was the root cause of the slow down for admin users? I could not find anything relevant in logs.

> Apache/2.4.33 (Unix)
> PHP version: 5.6.36
> Memory limit: 512M
> Max execution time: 14400
> mysql: 10.2.14-MariaDB-10.2.14+maria~jessie

**Comment by gonook** [comment]
Projectsend loading slow admin area also client area

**Comment by gonook** [comment]
Same issue with @tomkuba facing

**Comment by vlkolev** [comment]
check and update the PHP server version. In my case it was 5.5 and when updated to 7.2 it flies.

**Comment by gutenzwerg** [comment]
Probably that's the point. Our PHP Version is 5.6.40-0+deb8u4

**Comment by jonomango** [comment]
Getting this exact same issue. ProjectSend is *extremely* slow for all **System Users**, regardless of role. Blazing fast for **Clients**.

Nothing is showing up in the slow query logs or `mariadb/mariadb.log`. Nothing in `nginx/projectsend.error` either, besides some irrelevant PHP warnings. I don't mind trying to fix this issue on my end for a while longer, but I'm not the most experienced regarding web-dev, so some guidance would be appreciated.

```
ProjectSend r1605
Rocky Linux 8.7
nginx 1.14.1
PHP 7.4.33
MariaDB Ver 15.1 Distrib 10.11.3-MariaDB
```

**Comment by ignacionelson** [comment]
Sorry about this. Is it happening in every admin page?

**Comment by jonomango** [comment]
> Sorry about this. Is it happening in every admin page?

Yup. Although I've narrowed down the issue quite a bit. 

https://github.com/projectsend/projectsend/blob/28bb937d7a270284ccdd8eda6d25db47e61f5d37/header.php#L39
https://github.com/projectsend/projectsend/blob/28bb937d7a270284ccdd8eda6d25db47e61f5d37/header.php#L76

Commenting out both of these lines seems to reduce the loading times from around ~10,000ms to about ~80ms. A pretty big improvement. This makes pages such as `users-add.php`, `users.php`, `groups-add.php`, etc. load pretty much instantly now.

`dashboard.php` is still at around ~5,000ms though. Still debugging.

**Comment by jonomango** [comment]
And of course, commenting out the line with `updates.messages.php` removes quite a bit of the original webpage content. Still usable, but its just a temp fix.

**Comment by jonomango** [comment]
And without commenting the two lines I've mentioned above, `dashboard.php` takes about ~15,000ms to load... which seems to make sense.

**Comment by jonomango** [comment]
Found the source of the issues for `dashboard.php`:

https://github.com/projectsend/projectsend/blob/28bb937d7a270284ccdd8eda6d25db47e61f5d37/dashboard.php#L14
https://github.com/projectsend/projectsend/blob/28bb937d7a270284ccdd8eda6d25db47e61f5d37/dashboard.php#L37

I'll be getting off work in around ~15 minutes, so I won't be able to test more until tomorrow.

**Comment by ignacionelson** [comment]
Dashboard (including the sys info widgets) may be slow due to getting new versions info from the global server (which has been slow these days and down for a few minutes sometimes, I'm moving it into another service).

**Comment by ignacionelson** [comment]
Check get_latest_version_data
The curl call is probably the slow part. Maybe it can be replaced with something else but since these functions are not async it's not going to be easy since the update data is used across the admin in several parts

**Comment by jonomango** [comment]
> 

Yup seems like the case. Commenting that out fixes the issue as well.

**Comment by jonomango** [comment]
> Check get_latest_version_data The curl call is probably the slow part. Maybe it can be replaced with something else but since these functions are not async it's not going to be easy since the update data is used across the admin in several parts

Have you considered maybe caching this data? Maybe refresh the cached data every 1 hour or so.

**Comment by ignacionelson** [comment]
it's supposed to be cached for 1 day

`$versions = get_json(UPDATES_FEED_URI, '-1 days');`

But since the curl fails, it's probably not creating the cache file

**Comment by jonomango** [comment]
> But since the curl fails, it's probably not creating the cache file

Actually it seems the issue was on my end. Related to SELinux and https://github.com/projectsend/projectsend/issues/888, the cache directory wasn't marked as `httpd_sys_rw_content_t` so it was never able to create the cache file. I've edited my solution in the other issue, but perhaps add a check to see if this directory has write permissions as well, similar to how it is currently being done with `upload/admin` and other folders?

Regardless, all the performance issues seem to be fixed now, which is really nice!
