### ISSUE TITLE
Storage providers: Backblaze

### ISSUE THREAD

**Issue by 360path** [ignacionelson/ProjectSend#521]
It'd be great if ProjectSend supported Backblaze as a storage provider.

**Comment by mschop** [comment]
Hi @360path,

we plan to provide a plugin api that enables you to implement further storage providers. If you need Backblaze for you business, you could then implement a (hopefully open source) plugin that adds support for Backblaze to ProjectSend.
We will not support Backblaze in Core, as we do not have the manpower to support all different storage provider. Therefore I close this issue.

Best Regards
mschop
