### ISSUE TITLE
PDF Files Not Visible To Client

### ISSUE THREAD

**Issue by gnurob** [ignacionelson/ProjectSend#522]
Uploaded JPEG and PNG files are visible to the client at the my_files/?client= URL; PDF files are not.

I have tried various combinations of assignment and public visibility, and have uploaded all three file times at the same time, using various settings, with the image files always appearing as expected, and the PDF files only appearing to the administrator.

- Allowed file types includes the three file extensions tested.
- Files were uploaded with and without spaces, without issues either way.
- All three file types appear in the upload/files directory, with the same file permissions, and can be opened on the local server.
- Each uploaded file appears in actions_log table and the fields are the same (excluding the file name).
- On the client download page, HTML source, I see <ul class="photo_list"> which seems odd since other file formats are allowed for upload.

Is there something in ProjectSend that only allows images to be sent to clients, while any file type can be shared with administrators?

**Comment by ignacionelson** [comment]
Hello! Please try switching the template in the options page. If you are using the "Gallery" template, only images are shown. The other 2 templates will show all the files!

**Comment by gnurob** [comment]
Hello! I'd like to confirm that was exactly it. I'm not sure if the gallery is the default template, or an overwrite of a previous installation set the template. Thanks much, love the project!
