### ISSUE TITLE
Web playing of uploaded files

### ISSUE THREAD

**Issue by Westfielder** [ignacionelson/ProjectSend#525]
Excellent piece of software - thank you all who contributed.

I'm an ex -software engineer that many years ago became a paramedic so my PHP knowledge is almost not existent. Anyhow I managed to set up a host and managed to install projectsend in order to share recordings of music rehearsals with fellow musicians. I need to track who logs in and downloads what - so projectsend seemed ideal. All was going fine until I started rolling it out to users in our registered charity organisation.
Our old solution that we used (completely open website and file list with no logins etc.) allowed users to click on an uploaded MP3 in a list and the browser would play it, or it could be right-clicked to download. The users have really got used to this direct play method and don't want to change - 
In  the projectsend filelist clicking the filename or the download button do the same thing - force a download of the file. Would it be very difficult to link to the actual file so that the browser played the MP3.
Sorry if this is a rather stupid question but I'm probably the worst kind of user - knows a bit but doesn't know what he doesn't know,

Thanks in advance for any suggestions. This may be a feature request or maybe someone has done it but I searched and couldn't see where.

Nick Brown
r754

**Comment by ilakskill** [comment]
this is not an issue all of your files are in rootdir/ upload/files

**Comment by mschop** [comment]
Hi,

I think, playing media files is not the purpose of ProjectSend, so I think this will not be added to ProjectSend (@ignacionelson what do you think). As a first solution you could modify the template.

- Open the file /templates/default/template.php
- search the following line:

`$download_cell = '<a href="' . $download_link . '" class="' . $download_btn_class . '" target="_blank">' . $download_text . '</a>';`

- Insert this code after this line:

```
if($extension === 'mp3') {
  $download_cell .= '<audio controls><source src="' . $download_link . '" type="audio/mpeg">Your browser does not support the audio element.</audio>';
}
```

Please note:

- This guide is regarding r1053
- This may not work in all browser (versions)
- Be careful, when updating ProjectSend. The changes will be overwritten by the next update

**Comment by mschop** [comment]
We will not implement such feature, as this is out of scope of ProjectSend. You can modify the template if you need such functionality as shown in my code sample. Closing the issue
