### ISSUE TITLE
BUG  with Uploading files

### ISSUE THREAD

**Issue by ErikV2000** [ignacionelson/ProjectSend#529]
in the newest version of projectsend trying to upload files that are smaller than a megabyte just says that the file cannot be uploaded, please fix this

**Comment by mschop** [comment]
Cannot reproduce this in the latest version. Could you please:

- Check this with the newest version
- Provide us information regarding the server setup
- Maybe send us the output of phpinfo() (note! Please remove security relevant information)

**Comment by ErikV2000** [comment]
Fixed in the officiall release, was a bug during develeopment versions
