### ISSUE TITLE
no send notification for expire files

### ISSUE THREAD

**Issue by gogigopuduh** [ignacionelson/ProjectSend#53]
NO send email when expired a file at the config "days before expire", but others notification is working. (upload files, new client.. )
my system email is gmail and working great

use..
Debian Jessie
PHP 5.6.9-0+deb8u1
Apache/2.4.10 
Projectsend r582

sorry for my poor english, i speak spanish =P
![image](https://cloud.githubusercontent.com/assets/4336747/10206355/dc691564-679c-11e5-8a90-7b915c8eeef6.PNG)

**Comment by lenamtl** [comment]
hi, this is not compatible with this PHP version
check https://github.com/ignacionelson/ProjectSend/issues/52

**Comment by lenamtl** [comment]
Try to new version and let us know if you still have an issue with this
