### ISSUE TITLE
PDOException SQLSTATE during installation

### ISSUE THREAD

**Issue by leonidas-o** [ignacionelson/ProjectSend#534]
I'm using:
centOS 7
PHP 7.1.15
projectsend r756

install/database.php is already set as:
`expiry_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),

during the installation I get:
```
There seems to be an error. Please try again.

PDOException: SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause in /var/www/public/projectsend.mydomain.com/install/index.php:31 Stack trace: #0 /var/www/public/projectsend.mydomain.com/install/index.php(31): PDOStatement->execute(Array) #1 /var/www/public/projectsend.mydomain.com/install/index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table 'projectsend.tbl_files_relations' (errno: 150) in /var/www/public/projectsend.mydomain.com/install/index.php:31 Stack trace: #0 /var/www/public/projectsend.mydomain.com/install/index.php(31): PDOStatement->execute(Array) #1 /var/www/public/projectsend.mydomain.com/install/index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table 'projectsend.tbl_notifications' (errno: 150) in /var/www/public/projectsend.mydomain.com/install/index.php:31 Stack trace: #0 /var/www/public/projectsend.mydomain.com/install/index.php(31): PDOStatement->execute(Array) #1 /var/www/public/projectsend.mydomain.com/install/index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table 'projectsend.tbl_downloads' (errno: 150) in /var/www/public/projectsend.mydomain.com/install/index.php:31 Stack trace: #0 /var/www/public/projectsend.mydomain.com/install/index.php(31): PDOStatement->execute(Array) #1 /var/www/public/projectsend.mydomain.com/install/index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' in /var/www/public/projectsend.mydomain.com/install/index.php:31 Stack trace: #0 /var/www/public/projectsend.mydomain.com/install/index.php(31): PDOStatement->execute(Array) #1 /var/www/public/projectsend.mydomain.com/install/index.php(108): try_query(Array) #2 {main}
PDOException: SQLSTATE[HY000]: General error: 1005 Can't create table 'projectsend.tbl_categories_relations' (errno: 150) in /var/www/public/projectsend.mydomain.com/install/index.php:31 Stack trace: #0 /var/www/public/projectsend.mydomain.com/install/index.php(31): PDOStatement->execute(Array) #1 /var/www/public/projectsend.mydomain.com/install/index.php(108): try_query(Array) #2 {main}
```

**Comment by IB-Rahn** [comment]
Does your database user have all privilileges on the database? And I had an error (but don't remember the exact warnings) because my sql mode was set to `no_zero_date`, maybe this could also be the problem here?

**Comment by leonidas-o** [comment]
@IB-Rahn yes it has ALL privileges on it. Also checked that, as I saw it in another post:
When executing:
```
MariaDB [(none)]> select @@sql_mode;
+------------+
| @@sql_mode |
+------------+
|            |
+------------+
```

**Comment by kkplein** [comment]
I'm having the same issue on debian... Database created like:
create database ps;
GRANT ALL ON ps.* TO "ps"@"localhost" IDENTIFID BY "KsecretLg";

**Comment by kkplein** [comment]
And the result is a half-working install, where I can logon with the configured username/pasword, but the rest is not working. Hopefully ignacionelson could shed some light on this issue?

**Comment by ignacionelson** [comment]
This error was fixed, but a release version with the patch applied is not available yet.
You can use the development version right from the repo here at github, it should work fine! :)

**Comment by kkplein** [comment]
Well... my attempt was with the github version on debian stretch, and the problem appeared with THAT git version. (from a few days ago)
Now I installed an older version, and used that database with the git version, which it upgraded, and then things worked.
So: initializing a new database with the git version does *not* seem to work, but it *can* upgrade an existing database.

**Comment by ignacionelson** [comment]
what version of mysql are you using?

**Comment by ignacionelson** [comment]
Can you please test with the latest version from the repo? By setting a predefined default date for the expiration of files, instead of the current timestamp, this could be fixed.

**Comment by kkplein** [comment]
I trid briefly, and was unable to generate the error, so I guess it is fixed yes :-)
Thanks, even though I was not the original reporter of this. Hopefully it's also fixed for him

**Comment by leonidas-o** [comment]
okay, I used `r1053` and I was able to install it.

**Comment by kkplein** [comment]
then I guess you can close your issue?

**Comment by ignacionelson** [comment]
Indeed! Thanks for noticing :D
