### ISSUE TITLE
Logo Not Showing Up on Client Page

### ISSUE THREAD

**Issue by quintingsnj** [ignacionelson/ProjectSend#535]
Logo shows up on the login page. Once a client logs in, logo appears broken, with just the alternate text for the image displaying. Running version r754.

When I view the source, it is sticking some extra characters in the URL.

https://domainname.ca:443/projectsend/includes/timthumb/timthumb.php?src=https://domainname.ca:443/projectsend//img/custom/logo/logo_highercontrast-transparent.png&amp;w=250

The src url should be https://domainname.ca:443/projectsend/img/custom/logo/logo_highercontrast-transparent.png (I have confirmed that the logo is at this URL).

Why does it add an extra slash before img and then at the end, &amp:w=250??

Thanks.

Quintin

**Comment by quintingsnj** [comment]
OK, figured out that in the options table in the database, it had put the :443 for the port for my site (it's on an SSL site). I took that out, and now it displays the image, however, I believe because it puts the $amp:w=250 behind the file name, it ignores the fact that it is a "png" file, and the transparency doesn't work.  Why is it adding that? Where can I go to fix that?

Thanks!

Quintin

**Comment by thierrymtp34** [comment]
Same problem.

**Comment by mschop** [comment]
Could you please check, which value the php configuration option "arg_separator.output" has on your server? If you don't know how to find this out, just create a file called phpinfo.php with the following content:

<?php
phpinfo();

Open this phpinfo.php and try to find the option there. Please don't forget to delete the phpinfo.php afterwards, as the output contains security relevant information.

**Comment by quintingsnj** [comment]
I’m running r1053 now, and I don’t think it has the same issue.

Thanks,

Q
