### ISSUE TITLE
Suggestion: multiple emails per client

### ISSUE THREAD

**Issue by risottto** [ignacionelson/ProjectSend#54]
I love this software, just what I need without the bloat!

I just came across one issue that would be an easy fix, I have a client where I need to send two emails to two separate addresses when a file is uploaded. I can't use a comma or semicolon to add multiple addresses in the client edit email field, would it be possible to add this functionality?

Thanks for the great work!

Stan

**Comment by lenamtl** [comment]
Hi 
What you can do, is to create 2 clients, create a group for them, then share the file to this group.
They will both receive the email message.
