### ISSUE TITLE
Blank Page on any link inside the Dash Board

### ISSUE THREAD

**Issue by leonidas-o** [ignacionelson/ProjectSend#542]
Hello, after updating to r1053 I was finally able to install projectsend.
After logging in I see the Dash Board with all the statistics, system information like etc.:

#### Software
__Version__    r1053 
__Default upload max. size__    2048 mb.
__Template__    Default [Change]

#### Data

__Files__    0
__Clients__    0
__System users__    1
__Groups__    0
__Categories__    0

#### System

__Server__    nginx/1.12.2 
__PHP version__    7.1.15
__Memory limit__    1024M
__Max execution time__    14400
__Post max size__    8M

#### Database

__Driver__    mysql
__Version__    5.5.56-MariaDB

Everything looks fine so far, but when I click on any link, it doesn't matter which one, I always get a blank page. The only error in the log is:
```
projectsend.error.log 
2018/04/16 10:32:46 [error] 19021#0: *4 FastCGI sent in stderr: "Unable to open primary script: /var/www/public/projectsend.mydomain.com/includes/js/install/index.php (No such file or directory)" while reading response header from upstream, client: IPADDRESS, server: projectsend.mydomain.com, request: "GET /includes/js/install/index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-projectsend.sock:", host: "projectsend.mydomain.com", referrer: "https://projectsend.mydomain.com/install/"
```

**Comment by ErikV2000** [comment]
You need to change the config.php yourself before trying the installer

**Comment by leonidas-o** [comment]
@ErikV2000 which `config.php` and change to what?

**Comment by leonidas-o** [comment]
@ignacionelson as already mentionend there were only one error in the log:
```
projectsend.error.log 
2018/04/16 10:32:46 [error] 19021#0: *4 FastCGI sent in stderr: "Unable to open primary script: /var/www/public/projectsend.mydomain.com/includes/js/install/index.php (No such file or directory)" while reading response header from upstream, client: IPADDRESS, server: projectsend.mydomain.com, request: "GET /includes/js/install/index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-projectsend.sock:", host: "projectsend.mydomain.com", referrer: "https://projectsend.mydomain.com/install/"
```
Could also be an old one, when I visit projectsend and click on any link, no errors in the log.

**Comment by brandonllocke** [comment]
This may or may not be related to an issue that I am experiencing. The home page loads for me but when clicking any of the links, the page just adds a # to the end of the url but never goes anywhere. The dropdowns do not function either. Is any of that similar to your experience, @leonidas-o? I am not seeing anything in logs that would give a clue as to why that is happening.

**Comment by ignacionelson** [comment]
@brandonllocke Hello! Please delete the browser's cache. It will work fine after that :)

**Comment by ignacionelson** [comment]
@leonidas-o that's pretty weird. Looks like it's trying to load a js file that doesn't exist.
Can you try changing the database prefix on includes/sys.config.php and see if it let's you install again? You can delete the new tables after that

**Comment by brandonllocke** [comment]
@ignacionelson Yes, now I feel very stupid. Thanks for the help!

**Comment by leonidas-o** [comment]
@ignacionelson hmm, did you mean the `TABLES_PREFIX`? I can also drop the database, delete the files and start again, I've written an ansible playbook for it, so it is easy for me to install it again. What should I do?

**Comment by leonidas-o** [comment]
Okay, I've deleted all files, dropped the DB and installed everything again.
I get to the install screen, fill everything in, continue, looks like everything is working fine, but after log in, again the same error. In the Logs:
```
2018/04/20 12:30:30 [error] 10282#0: *17 FastCGI sent in stderr: "Unable to open primary script: /var/www/public/projectsend.mydomain.com/includes/js/install/index.php (No such file or directory)" while reading response header from upstream, client: IPADDRESS, server: projectsend.mydomain.com, request: "GET /includes/js/install/index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-projectsend.sock:", host: "projectsend.mydomain.com", referrer: "https://projectsend.mydomain.com/install/"
```
and the same behavior in the dashboard. The dashboard itself seems to work, but when clicking on any link I get the blank page again.

**Comment by JackWhite20** [comment]
@leonidas-o 
Have you checked that /var/www/public/projectsend.mydomain.com/includes/js/install/index.php exist and that the permissions are correct?

**Comment by leonidas-o** [comment]
@JackWhite20 Yes I do have checked that, it does not exist, but how could it? If you take a look into:
https://github.com/ignacionelson/ProjectSend/tree/master/includes/js
there is no `install/index.php`, so don't know where this path is comming from

**Comment by JackWhite20** [comment]
It is indeed weird that it tries to find the php file in the js directory. Is your path/root configured properly?

**Comment by ignacionelson** [comment]
That php file renders as a js one, so that's ok.
Have you tried enabling the debug mode on PS? You can edit the file sys.config.php and change the value to true. That may give a clue on the error.

**Comment by leonidas-o** [comment]
@ignacionelson i just found a debug flag in sys.vars.php. Setting this to true I see the error:
```
2018/04/24 09:47:57 [error] 28665#0: *36 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/public/projectsend.mydomain.com/header.php:38
```

**Comment by ignacionelson** [comment]
Thanks @leonidas-o 
With that info I've fixed that error on a recent commit :)
