### ISSUE TITLE
 'Download zipped' not working 

### ISSUE THREAD

**Issue by germaine1** [ignacionelson/ProjectSend#545]
I was surprised to see this issue closed as it has never worked for me.
I use PHP 7.0 with zip enabled, everything else appears to work, but the download zipped does not result in a download.
Interestingly, Using Edge under Win10 adds  'generated a zip file' to the logs, although no download is generated.  (also the url encodes the [ and ] to %5B and %5D)
I've set the php memory_limit to 1024Mb, and I believe I've added all the modules required, but still no joy.
If this can't be fixed perhaps an option to hide the option?
Best Regards
Marc

I'm using  r1053 which is the latest i have available on Softaculous.

**Comment by germaine1** [comment]
Further work shows that :
The same results using PHP 5.6, 7.1 and 7.2 on the same server.
Firefox Android shows same problem (No results, no log).
Firefox Focus Android shows same problem  but adds 'generated a zip file' to the logs.
Firefox under Linux shows same problem (No results, no log).

I will spend some time later looking at the server, possibly tweaking the code and htaccess files..  Your demo won't allow uploads, so can't really be used to test the system.

**Comment by ignacionelson** [comment]
Thank you!
I've just found the problem in the ajax routine, I'll try to solve this ASAP

**Comment by germaine1** [comment]
I am always available to help, this is a worthwhile project.   My server is at your disposal for testing.

Best Regards

Marc

**Comment by NicolaSafop** [comment]
Good morning everybody. I believe that I have the same problem reported by Germaine.
Do you have any update about the issue?
Thank you and kind regards

**Comment by afadhil** [comment]
Hello.. Is there any updates regarding this issue? because I have the same issue. thank u

**Comment by ignacionelson** [comment]
Fixed
https://github.com/ignacionelson/ProjectSend/commit/281b611724ebf42c04c1ac13226ed00377f10e94
