### ISSUE TITLE
Error after login on r1053

### ISSUE THREAD

**Issue by podz49** [ignacionelson/ProjectSend#546]
Hi, 
Since the upgrade to r1053 after each login I have a web page with this message:

{"status":"success","message":"
x<\/a>Login_success.Redirecting...<\/div>","location":"https:\/\/myserverURL:443\/home.php"}

I have to go by myself a second time to my server URL to access in projectsend successfully (without password request).

Do you have an idea ?

Thanks

**Comment by chezmohamed** [comment]
I have the same problem someone to the solution?

**Comment by jschav88** [comment]
Same problem.

**Comment by thierrymtp34** [comment]
Same problem.

**Comment by thierrymtp34** [comment]
it's a redirect problem

A provisional solution

In the process.php file which is at the root of the line 142

comment the line : 
//echo json_encode($results);

and add :

echo "<script type='text/javascript'>document.location.replace('". $results['location'] ."');</script>";

**Comment by ozirissp** [comment]
See #561 with fix in PR #562 could be a translated string with quote in JS as I was facing with french.

Do you use translation with projectsend ?

**Comment by jschav88** [comment]
Concerning me, yes. I resinstalled ProjectSend and it works well.

**Comment by ozirissp** [comment]
Ok the problem occur only with French and other translation with simple or double quote inside translated strings for on login page.

(for exemple : "Le nom d\'utilisateur n\'a pas été complété")

Use English only on login page and no error will occur.

Or use the fix provided in my PR # 562.

**Comment by podz49** [comment]
Thanks a lot for this resolution ! I'm using French translation and I've made changes described in PR #562 and now all work well.

**Comment by pmocorp** [comment]
I had to bring the patches but the error persists!

**Comment by pagchen** [comment]
For those stumping on this post. Here is what worked for me to bypass the language with apostrophe problem:
REPLACE:
`echo json_encode($results);`
WITH:
`echo json_encode($results, JSON_HEX_QUOT);`
in file process.php.

There are many occurences of this line, change everyone.

**Comment by david20240** [comment]
Hi Github Community
As french I decided to modify the fr po files without the `'` and now Project send does it's job no troubleshootings in french anymore.
If you want these files drop me a line 
 (R1053-Projectsend)

Have a nice day

**Comment by olivercode** [comment]
> it's a redirect problem
> 
> A provisional solution
> 
> In the process.php file which is at the root of the line 142
> 
> comment the line :
> //echo json_encode($results);
> 
> and add :
> 
> echo "<script type='text/javascript'>document.location.replace('". $results['location'] ."');</script>";

it works for me
