### ISSUE TITLE
file sharing between client possible?

### ISSUE THREAD

**Issue by chezmohamed** [ignacionelson/ProjectSend#549]
Hello
there is the option to allow clients to share files between them
in the transfer of file on the customer account there is not the possibility of choosing the customers

**Comment by chezmohamed** [comment]
someone there to the solution?

**Comment by cryptoxx** [comment]
exactly - anyone ?? It's quite odd that regular users can't share files with other. Is it just uploading platform for singles users with an administrator exception with sharing feature ?

**Comment by mschop** [comment]
ProjectSend is a 'client oriented file sharing platform'. Therefore this is currently out of the scope of project send. Normally clients do not have contact to each other. This is not possible currently.

Maybe we will implement this in future.  Need to a little more investigation, whether this could introduce security or legal implications.

**Comment by mschop** [comment]
@ignacionelson please correct me, if I'm wrong with this.

**Comment by ignacionelson** [comment]
@mschop Indeed. While it would be nice if at some point in the future a plugin could be made to handle special cases like this, if PS was made to do this by default it could turn it into a traditional file sharing app losing it's focus and objectives.

**Comment by mschop** [comment]
@chezmohamed  / @cryptoxx What's the use case for this? In which scenario you would like to use this feature?

**Comment by kkplein** [comment]
But perhaps you should take a look at pydio, as I think it does allow filesharing between clients..?

**Comment by mschop** [comment]
@kkplein pydio is far beyond the scope of ProjectSend. Pydio is a "Enterprise file sharing & sync platform". ProjectSend is targeting different users.

**Comment by kkplein** [comment]
Sure! I was just saying that if he/she needs that kind of functionality, there is software available that offers it over a web interface.,

**Comment by mschop** [comment]
Ok. Got your point ;-)

As most here agree, that this is out of scope of project send , I close this issue.
