### ISSUE TITLE
New Version not working on Safari Browser

### ISSUE THREAD

**Issue by sgerhager** [ignacionelson/ProjectSend#550]
The new navigation does not work on news Safari browser on current Mac OS X.
When clicking on Header in the navigation bar the unterlying navigation does not open.

**Comment by mschop** [comment]
Do you see an error in the console log?

**Comment by mschop** [comment]
@sgerhager I close this issue, as this seems to be a duplicate of #557 . Please follow the other issue for updates or reopen this issue, if the problem is different than the referenced issue.
