### ISSUE TITLE
Clients that self-register do not receive a welcome email or email notifications when a file is uploaded

### ISSUE THREAD

**Issue by InfluentialDave** [ignacionelson/ProjectSend#551]
Hi Team,

I can confirm mail is working, as when I create a client manually or create a system user (Administrator or Account Manager) a welcome email is sent, and any files uploaded also send a notification email.

My issue occurs when Clients self register. I have set options to require Account Manager approval and auto approval and still the user does not receive welcome emails or file upload notification emails. I'm registering as a client myself to test and ensuring the "Notify new upload by e-mail" is checked, and have noticed that in the tbl_users table in the database, the notify column has a value of 0. 

After manually modifying the notify column I can send email notifications when uploading a file, but I don't want to have to do this every time a new client is created, and feel a welcome email should be sent out to clients when it explicitly states on the sign up page "This account information will be e-mailed to the address supplied above".

Many thanks for your help,

David

**Comment by mschop** [comment]
I've created an PR for solving the bug, that the flag in the DB is not set.
Currently, no welcome message is sent for self-registered users, but this problem was already reported in #541. This problem should therefore be discussed in the linked issue.
