### ISSUE TITLE
Suggestion: Add to files table and to manage-files.php new column - modified date

### ISSUE THREAD

**Issue by grzmar** [ignacionelson/ProjectSend#56]
When client uploads new version of alredy uploaded file there is no information about that change. So i suggest to add new column: modified date. Field should be updated every time a new version of file is uploaded. I think that it would be better to display on manage-files modified date instead of timestamp.

**Comment by lenamtl** [comment]
Hi,

That would not work with the actual system...
The system automatically add a _1 if filename exist, so we cannot update an existing file.
We have to delete it and reupload it.

For example if I upload myfile.png
and I reupload the same file myfile.png will be renamed automatically to myfile_1.png 
and if I upload third time this will be renamed to myfile_2.png and so on...
