### ISSUE TITLE
JS error and login error with translation

### ISSUE THREAD

**Issue by ozirissp** [ignacionelson/ProjectSend#561]
With french translation (.po and .mo files), login is not working properly.

There are js errors in console and the login does not work properly.

In french there is a lot of simple quote in strings ...

In fact, all translated strings in generated js code (index.php and js.functions.php) are not escaped in js strings.

You can find these in php code with the search pattern : **'<?php _e(** or **"<?php _e(**

The fix is easy replace all `<?php _e(....); ?>` with `<?php echo addslashes(__(....)); ?>` when it is used in JS code.

**Comment by mschop** [comment]
I close this issue, as it seems to be fixed by ignacio. If there is still something not working, don't hesitate to reopen the issue.

**Comment by mschop** [comment]
@ozirissp sry. Sure, that was you ;-)

**Comment by florianproxi** [comment]
@ozirissp Hello ! I need the updates from @ignacionelson but i just get the last release so how to do that ? Thanks !
