### ISSUE TITLE
Incompatibility with MySQL 5.7

### ISSUE THREAD

**Issue by ofrzeta** [ignacionelson/ProjectSend#570]
Clicking on "Membership requests" gives:

`( ! ) Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1221 Incorrect usage of UNION and LIMIT' in /var/www/localhost/htdocs/clients-membership-requests.php on line 216
`

The reason for this is MySQL 5.7 has changed the requirements for parentheses with UNIONs: "Previous versions of MySQL may permit such statements without parentheses. In MySQL 5.7, the requirement for parentheses is enforced.", cf https://dev.mysql.com/doc/refman/5.7/en/union.html

**Comment by ofrzeta** [comment]
I submitted a PR that fixes this issue: https://github.com/ignacionelson/ProjectSend/pull/571

**Comment by ignacionelson** [comment]
Merged, thank you!!!!
