### ISSUE TITLE
Email Address Validation does not work for new IANA TLD's

### ISSUE THREAD

**Issue by crashff00** [ignacionelson/ProjectSend#58]
The list of TLD's has grown quite large, and anything over 4 characters doesn't seem to work. This should probably be changed to check against a list of valid TLD's, since the list is ever expanding and a regex solution will probably be more trouble than it's worth.

Valid TLD List, Alphabetic: http://data.iana.org/TLD/tlds-alpha-by-domain.txt
See: http://www.regular-expressions.info/email.html

**Comment by jwallinder** [comment]
Also, some valid emails is rejected. Please see http://www.w3.org/TR/html5/forms.html#valid-e-mail-address for a good regexp example (alse below)

     The following JavaScript- and Perl-compatible regular expression is an implementation of the above definition.

    /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/

**Comment by lenamtl** [comment]
I agree this need to be updated.
This one seems good
^.+@[^\.].*\.[a-z]{2,}$

See: http://www.regxlib.com/REDetails.aspx?regexp_id=174

**Comment by crashff00** [comment]
/^.+@[^.].*.[a-z]{2,}$/ allows invalid characters, addresses, and code insertion as noted in the comments on that page dated from 2003-2009. Nearly all recent references to client side email address validation say to stop using regex altogether.

**Comment by lenamtl** [comment]
Yes I know, that was a short one.

@jwallinder regex solution seems a good solution for now

**Comment by crashff00** [comment]
Does anyone know if the php function FILTER_VALIDATE_EMAIL works for this? the whole regex process could be eliminated.

**Comment by jwallinder** [comment]
FILTER_VALIDATE_EMAIL does not validate all emails in this post (ok and not
ok email)
http://haacked.com/archive/2007/08/21/i-knew-how-to-validate-an-email-address-until-i.aspx/

Regexp does.
Den 12 nov 2015 23:21 skrev "crashff00" <notifications@github.com>:

**Comment by crashff00** [comment]
I don't believe the short address problem is a duplicate of this.  I have plugged various regex expressions into online testers and the addresses work. When I use those exact same regex expression in the form validation, they fail until I make the first part of the address a minimum 3 characters.  This doesn't have anything to do with the domain side of the address.

**Comment by lenamtl** [comment]
Ok I see, I guess it depending of the settings.

Can you tried the jwallinder solution just to see if this will fix your problem...

**Comment by crashff00** [comment]
I have his solution currently in place, and it does not work.
For:  name@company.com
 if the name part of the email is 2 characters:  i.e.  ia@company.com   it fails
if the name part of the email is 3 characters:  i.e.  ian@company.com   it works.

according to the regex testers I have tried online, BOTH are valid according to the regex, which makes me believe the problem lies elsewhere in the code.

the only way I have found to circumvent this is to enter a purposefully wrong email address and then correct it by modifying the database table entry directly.

**Comment by lenamtl** [comment]
That's need to be fixed in JS /includes/js/jquery.validations.js

**Comment by martin-gerdes** [comment]
Thanks to lenamtl for the file location!
I changed the regexp for my installation from
/^([^@])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/ to
/^([^@])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,})$/

to allow longer TLDs (in my case, "finance")

**Comment by lenamtl** [comment]
Hi martin-gerdes ,
I'm testing the regex with PHP and it give an error
_preg_match(): Compilation failed: range out of order in character class at offset_
about this part [A-Za-z0-9_-.]
I also tested it with https://regex101.com and it's give an error too.
seems to work ok if I change it to 
`^([^@])+\@([A-Za-z0-9-])+.([A-Za-z]{2,})$`

**Comment by ignacionelson** [comment]
Fixed on ee6af1e
