### ISSUE TITLE
can't add allowed file extensions using the webinterface.

### ISSUE THREAD

**Issue by joopmartens** [ignacionelson/ProjectSend#60]
Using the system options security tab file extensions can be removed and saved without a problem.

When I try to add an extension a new empty white extension box appears that allows me to enter the file extension text.

It does not seem to be possible to create a new extension box to add a second one and more important the added extension is not being saved after hitting the update all options button.

Not any error is provided at the webinterface nor at the webservers (error) log.

As a workaround I have added the extensions directly in the database.

PS. I have tried this using both Firefox and Internet explorer without any difference.

**Comment by lenamtl** [comment]
which php version are you using?

**Comment by joopmartens** [comment]
I'm running CentOs 6
php-common-5.3.3-46
httpd-2.2.15-47 (Apache)
mysql-server-5.1.73-3

**Comment by lenamtl** [comment]
Have you tried using another browser?

**Comment by crashff00** [comment]
The comma is what threw me off when I tried this. I kept trying to press enter and tab.

**Comment by lenamtl** [comment]
So is it ok with the comma now or not?
which browser are you using?
