### ISSUE TITLE
Hidden file 

### ISSUE THREAD

**Issue by lenamtl** [ignacionelson/ProjectSend#66]
Hi,

When a file is marked as hidden how can we put it back to show from the admin interface?
The check box is not selected when I edit the file so I cannot uncheked it 
can someone check this

Not sure the purpose of this option, I guess it is one time only use when uploading.
If so, then checkbox should not be in edit form.
else it need to be fixed.

Thanks

**Comment by honeybadge** [comment]
+1 
I think the explanation "Upload hidden (will not send notifications)" is misleading. ProjectSend will not send a notification and hide the file from the client for eternity.

**Comment by lenamtl** [comment]
I don't see any use of this ?
Why uploading a file assing it to a client but you don't want the client to see it?
Is this for internal purpose, like add an hidden file to user but admin can see it?
