### ISSUE TITLE
file upload can't be finished

### ISSUE THREAD

**Issue by Wohnzimmerpirat** [ignacionelson/ProjectSend#68]
Hey,

to the beginning: Thank you for your very nice tool. It look very nice.
I have only one problem during the file upload.

The first step works fine. The file upload is transfered to my server.
But the following step doesn't work. I didn't get the input field(s) to insert title, and so on.
The result: The process could not be concluded.

Is it a error in the configuration?

(I use PHP 5.1 on IIS.)

Thanks.
Marco

**Comment by lenamtl** [comment]
Hi,

Is this a big file?
Is the file is opened?
I'm not familiar with IIS, do you have other error message or error number or log information?
Are the other form are working ok?(add client, group, user..)

Some settings you can verify :
php_value upload_max_filesize 
php_value post_max_size 
memory limit

**Comment by Wohnzimmerpirat** [comment]
Hi,

thanks for your quick response.
It isn't depend on the file size.
Which log information do you mean? Internal logs of your program* or php/iis logs?
*Where can I find these.
The other forms work fine.

The settings are ok. The upload, after the first step, works fine, but I didn't get the next windows
to insert the title (and other informations) of the file.

**Comment by lenamtl** [comment]
Yes IIS and PHP logs may help.
It is probably related to some security permission issue, IIS configuration...
As I said I'm not familiar with IIS but on Apache/Linux we have to set folder permission to upload file so you have probably some similar settings on IIS/Windows
https://support.microsoft.com/en-us/kb/979124

**Comment by ITIZ** [comment]
I had the same issue, probably because I copied the files/folders instead of uploading. I believe it's a permissions problem.
