### ISSUE TITLE
Proper Upload Folder Permissions?

### ISSUE THREAD

**Issue by shawning** [ignacionelson/ProjectSend#69]
If we use: chmod -R 777 upload we are able to upload files fine however an unauthenticated user can view the files by going to http://xxx.xxx.xxx.xxx/upload/files which defeats the purpose.

I don't fully understand the flow of the uploads though. I was hoping once they were uploaded they were moved or modified with the proper permissions through the application.

Anyone able to help us determine the proper permissions for the upload folder?

**Comment by crashff00** [comment]
Turn off folder indexing by your webserver software. They wont see anything then.

**Comment by sysrunner** [comment]
With indexing you can still go to http://address/upload/files/document.pdf
Is there anyway with permissions to prevent this?  If not can it be encrypted/decrypted when the user uploads or downloads the file

**Comment by mtsnuc** [comment]
Hi,
I have exactly the same problem as sysrunner.
Is there any solution?
