### ISSUE TITLE
Add Support for PHP 7

### ISSUE THREAD

**Issue by gasserfelstechnik** [ignacionelson/ProjectSend#70]
With PHP 7.0.0, the login page doesn't load.

**Comment by lenamtl** [comment]
Hi,

ProjectSend is not compatible from php 5.5

**Comment by gasserfelstechnik** [comment]
Security support of PHP 5.5 ends on 10 Jul 2016, do you think it's possible to ensure compatibility with PHP 5.6 until then? Acutally I haven't found any issues using PHP 5.6, are there some known?

**Comment by lenamtl** [comment]
Interesting....

Some users have reported problems using 5.5 
but I don't have tested this version yet, I'm using 5.4.12
This may also depends on settings or other installation problems.

Here are the Backward Incompatible Changes between 5.4 and 5.5
http://php.net/manual/en/migration54.incompatible.php
I know that ob_start(); is used in the code 

It is maybe to earlier to support PHP7 but I think updating to 5.6 & PDO is more realistic.

**Comment by MariusStuparu** [comment]
It's running on PHP 5.6.16, but not on 7.0.1. Database is MariaDB 10.
Errors reported: 

```
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; 
PasswordHash has a deprecated constructor in
.../includes/phpass/PasswordHash.php on line 27
```

**Comment by lenamtl** [comment]
Just to let you know that the Projectsend now is using PDO.
https://github.com/ignacionelson/ProjectSend/issues/114

**Comment by crashff00** [comment]
Confirmed that 608 / 609 does work with php 7.0.7 (at least in my test environement)
