### ISSUE TITLE
Unable to delete files

### ISSUE THREAD

**Issue by AlanReiblein** [ignacionelson/ProjectSend#73]
Trying to delete files. The system states that the files have been deleted but they are not.
File Permissions are set to #776 
I am doing this in an SSL environment.

Any ideas 

Version R582
Browers IE and Chrome
Server Unix

**Comment by lenamtl** [comment]
Have you tried this fix 
https://github.com/ignacionelson/ProjectSend/issues/42
I did apply this fix and that was working ok.

But I did some test last week and cannot delete file anymore, so I have to retest all the manual fix I did...
Maybe there is a conflict with anotherfix update...

This is why we have to test all pull request before updating the main package to prevent this kind of issues.

**Comment by lenamtl** [comment]
Some tests using the latest package 

Logged as Admin and file uploaded by Admin

-when the file is not assigned and set to not expire = the file got deleted
-when the file is assigned to more than one user & group and not expire = the file got deleted
-when the file is assigned to more than one user and is expired = the file got deleted
-when the file is orphan and set to not expire = the file got deleted

Problems
-when the file is assigned to more than one user & group and is expired =  the file is not getting deleted
(1 user johndoe +  groupA and groupB, johndoe is the only member of both groups)
(I got success message but the file is still in the list)

-when the file is assigned to more than one user and is going to expired in future =  the file is not getting deleted (I got success message but the file is still in the list)

-when the file is assigned to more than one user and set to not expire  =  the file is not getting deleted (I got success message but the file is still in the list)

**Comment by AlanReiblein** [comment]
I have not done the methodical testing you have done , but the log reported a different file deleted to the one that was actually deleted. I will do a more methodical test.

**Comment by lenamtl** [comment]
The manual fix provided should fix most of the problem, I will redo the test with the fix from
https://github.com/ignacionelson/ProjectSend/issues/42

**Comment by AlanReiblein** [comment]
Got into a worse situation 
I can't delete, I can't allocate a file to a user. Says it has done it but not.
(This is all on my copy test system)
I am resetting back to my zipped r582 files.

Hope the database has not got screwed (I have a backup though)

**Comment by lenamtl** [comment]
Hi, 

I have made some extra tests and the fix from 42 does not cause any of those issue you have.
Which PHP version are you using? 
Some users having issues when using PHP 5.5+

Regarding SSL, you can check a user have posted some improvement.
https://github.com/ignacionelson/ProjectSend/issues/65

**Comment by AlanReiblein** [comment]
Having reset back to r582, then applying your changes. I find that I can delete files.
I am using PHP 5.4.45. 

Still does not report the correct file being deleted this could also be another  file_id / id issue somewhere else

I have been running in an SSL environment for over a year and got all that sorted out by r514

I must resolve the log reporting

I analysed data base use tbl_files and tbl_file_relations
I imported the files (the number in front is its id value in tbl_files)
1736 LesMisTickets.pdf 
1737 MGSSInvoice.pdf
1738 legends_product.pdf  
1739 helmets      
1740 jersey      
Now in tbl_files_relations 
id 1738 has file_id 1597  which is file W30_Payroll_Output.zip
id 1739 has file_id 1598  which is file EOY_PAP32TOT_1.pdf
id 1740 has file_id 1599 which is file M12_PAP32TOT_1.pdf
When I deleted the five files the log reported 
 W30_Payroll_Output.zip  EOY_PAP32TOT_1.pdf and  M12_PAP32TOT_1.pdf
as being deleted
The ones not having an id in tbl_files_relations  did not show in the log.

I found in manage-files,php at line  166

$sql_distinct_files = $database->query("SELECT file_id FROM tbl_files_relations WHERE id IN ($files_to_get)");

This does not seem quite right but ......

$sql_distinct_files = $database->query("SELECT DISTINCT file_id FROM tbl_files_relations WHERE file_id IN ($files_to_get)");

would be better giving a distinct set of file_id  (s) to add to the log 
There is a comment a few lines later which intimates this list was used to update the log.

When I tried this the log gives the correct file name deleted. Now not being a developer in this system (although I have contributed to enhancements when on google) I would prefer if someone checked this for other repercussions.

Alan

**Comment by lenamtl** [comment]
Thanks :)
I will try to find some time this week to make a complete set of test.

**Comment by mriolo** [comment]
I just posted a fix in issue #72 related to the same query from manage-files.php referenced above to fix the logging info.  Even after applying my fix, I still see an issue with an uploader user attempting to delete a file and receiving an operation successful message, and the deletion being logged, but the file not having actually been deleted.  I haven't seen any problems deleting files as sysadmin after the logging fix.

**Comment by crashff00** [comment]
Using r583 currently, and this problem has reappeared. selecting files to delete logs them as being deleted, but does not remove them from the database or from the folder.   

making Alan's change to line 166  AND the change to line 527 solved it.

**Comment by mriolo** [comment]
I believe these are two separate but related issues that both have to be fixed - the line 166 change fixes the logging issue and the changes around line 527 (from issue #72) fixes the actual file deletion issue.

**Comment by lenamtl** [comment]
Please update to the latest version and let us know if you still have issue
