### ISSUE TITLE
Is it possible to restrict features depending on group?

### ISSUE THREAD

**Issue by srmobile** [ignacionelson/ProjectSend#76]
First thank you for such a well thought out easy to use software.

Is it possible to restrict users to only uploading files and making them public? We have a need to upload files and provide the link to external users, so I would only want this portion when a user logs in.

The links would then be manually sent via email.

Thank you

SR

**Comment by lenamtl** [comment]
Hi, 

For system user you can select Uploader role.
For client there is only one global option : Clients can upload files Y/N.
If these are not working for you what can be done is to edit the template and removed the non necessary elements/pages to a specific user role.
if you want to make public file by default you can hardcode it, or create a rule for this.

A more complete solution would be to have a more granular user role, client and group,  but this is not possible at the moment.

**Comment by srmobile** [comment]
Hi 

So if I want to hide the dashboard from regular users I guess I just comment it out?

thanks for the reply.

**Comment by lenamtl** [comment]
What you can do is to change the access to page elements or to the page

Let say I usually keep admin like it is and I edit another role like uploader
if this is the admin that connect = display the dashboard, if not I show other content this could be notes, welcome messages, help file etc, or you can automatically redirect them to another page.

On each page you have the access level defined so you can change this, check in DB to find out what are the level for each
$allowed_levels = array(9,8,7);

then for the menu or page section
you have something like this

$clients_allowed = array(9,8);
if (in_session_or_cookies($clients_allowed)) {
?>

So you can change this to what you want and add your own rule to section that don't have any rule.

Check page code and you will find plenty of rule based on level.

**Comment by srmobile** [comment]
That's a much cleaner solution! Thank you very much!
