### ISSUE TITLE
Spanish language

### ISSUE THREAD

**Issue by Dreadchild** [ignacionelson/ProjectSend#8]
how can I change the language or translate it?

**Comment by ignacionelson** [comment]
Guys, sorry for the extremely late response. while it might not be of use for you now, it can remain in case someone finds this issue.

All the translations are available for download at
https://www.transifex.com/projects/p/projectsend/

I will make sure to include them on every release from now on.

**Comment by ignacionelson** [comment]
Most languages are now included with the system, so only the config file needs to be changed.

Here's a small tutorial on how to use translations that are NOT included, and also how to apply them (works for included ones too).
http://www.projectsend.org/how-to-use-translation-files/

**Comment by olimax** [comment]
No language files other than English seem to be included in the system as far as I can see.
I went to the Transifex, as directed, but can't figure out how to download any of them
Am I missing something?

**Comment by Gerard64** [comment]
Same here can't download language files on https://www.transifex.com/projects/p/projectsend/
Where can we download language files?

**Comment by cwt3c** [comment]
I had to register an account and join the project. Otherwise it‘s not possible to download the files :/

**Comment by ignacionelson** [comment]
Oh :(
I will try to add a list of languages with downloads on the website!
