### ISSUE TITLE
Decode html_entities

### ISSUE THREAD

**Issue by JackLeEmmerdeur** [ignacionelson/ProjectSend#81]
Hi Mr.Nelson.
Just wanna thank you and say how in awe of your web 2.0 skills I am. For a near one man show (guessing by number of commits of other contributors, not to diminish their efforts), this webapp is astonishingly complete, userfriendly and useful. If one doesn't have a meaningful usage for the ever cost-consuming webspace, just install this on your (SSL enabled) vhost and be at least a little safer to pass sensitive information to buddies.

If a few features get added and issues fixed it would be top-notch stuff in my opinion. My few observations after a days use:

1. Possibly the easiest of my issues: In line 132 of file templates/default/template.php shouldn't it be html_entity_decode($file['description'], ENT_COMPAT, 'UTF-8') instead of htmlentities($file['description'])? At least special chars will be displayed correct in the descriptions in the customer-file-list with me. I guess the same has to be done in line 117 with htmlentities($file['name']).

2. (Already [issued](https://github.com/ignacionelson/ProjectSend/issues/39)) Make the table prefixes count after the installation. With my installation the table prefixes within the DB remained at "tbl_". Albeit I can't remember for sure if I maybe edited the TABLES_PREFIX-constant of includes/sys.config.php before installation (as I entered my db-info there before, I guess I did the same with the table-prefix-constant). Other issuers mentioned a file where the default prefix was hardcoded inside a SQL-query. The issue was definitly a showstopper with me.

3. Best of all would be a page in the installer to set all constants before the actual install-procedure.

4. (Already [issued](https://github.com/ignacionelson/ProjectSend/issues/77)) Multiple group-assignments

5. Markdown in the description would it make all the more feature complete.

ASAP I'll submit a pull request I hope, if I am able to integrate some of that.

Good luck with the project.

**Comment by lenamtl** [comment]
Hi,
There is also issue with Latin special characters that are not stored correctly in DB, so I guess when this will get fix this will fix other similar issue. I need to fix it as I'm planning to use it for french users.

Most of the items are already known issues. 
I will make a todo list, so stay tuned
