### ISSUE TITLE
Symlink for uploads folder

### ISSUE THREAD

**Issue by stffndtz** [ignacionelson/ProjectSend#83]
We just updated our installation of projectsend, and I found it a pretty good idea to move the uploads to a shared folder with a symlink pointing to it.

But as it turns out, this is not working out of the box. Has anyone ever tried this before? Any help is highly appreciated!

**Comment by lenamtl** [comment]
Hi,
Check to see if this post can help:
https://github.com/ignacionelson/ProjectSend/issues/43

**Comment by stffndtz** [comment]
Hi, that's exactly what I am looking for - the search unfortunately didn't bring that up. You can mark this issue as a duplicate of #43.

Thanks!
