### ISSUE TITLE
Custom TABLES_PREFIX not working

### ISSUE THREAD

**Issue by ESPONI** [ignacionelson/ProjectSend#84]
Changing define('TABLES_PREFIX', 'tbl_'); to any other, for example: define('TABLES_PREFIX', 'XX_');
During installation the tables are created as 'tbl_' and then the site is not working until you change the preset to define('TABLES_PREFIX', 'tbl_'); again.

Best regards!

**Comment by lenamtl** [comment]
Yes, thanks,  this is a known issue.

**Comment by ESPONI** [comment]
Ahh! thanks I did not read old issues, my bad ,)

**Comment by lenamtl** [comment]
Well it's need to be fixe, it is on the todo list :)
