### ISSUE TITLE
Suggestion: Save uploaded files in a folder which name is the user name

### ISSUE THREAD

**Issue by ESPONI** [ignacionelson/ProjectSend#85]
All files in the same directory could be a little complex for some uses.
Thanks!

PS: Awesome code

**Comment by lenamtl** [comment]
Hi there are several request for subdir, we will take all suggestion and see what can be done.
But we need to fix the actual code first.

**Comment by ESPONI** [comment]
We are very interested and we can make a Donation because it will be used in our company.
Thanks & Let me know ;)
