### ISSUE TITLE
Only admin can delete files

### ISSUE THREAD

**Issue by fuez96** [ignacionelson/ProjectSend#89]
Hi!
I use version r582.
Logged in as an admin I can delete the files of users and my own files.
Logged in as upload I can't delete files, I select them as deleted, but after the page is loaded the file still apears.

In the other issues I read, that a file must be assigned to a user or group.
So I created an autoclick button for "select all users" when page is loaded.
But even if I assign a file I can't delete it.

Any ideas?

**Comment by lenamtl** [comment]
Hi,
I don't remember if Upload can delete file....
We have to check into the code

**Comment by lenamtl** [comment]
Ok I have checked the code and Admin and Account Manager can delete file.
Uploader and Client cannot delete file.

**Comment by shoulders** [comment]
I am not quite sure why this has been closed. I can see that the code has been investigated and there is not a bug.

This is really is a required option to have. Can this be changed into a feature request so clients/uploaders can delete their files.

This feature would be settable in the admin options to allow clients to either be able to delete their files or not.

A client might upload a document and then update it and want my company to use the new one and not the first document and if the client can delete files it would make things easier and no confusion.

thanks

**Comment by lenamtl** [comment]
Hi, 
This should be a setting so admin decide who can delete file,
 I add enhancement label and as I have already suggest it long time ago.
I will close this one and let #44 open
