### ISSUE TITLE
tables prefix and loop install

### ISSUE THREAD

**Issue by ClmH** [ignacionelson/ProjectSend#90]
Hi,

When I installed ProjectSend r582 on various servers, I always got stuck in a loop during install :
- the config file was properly filled
- the install screen too
- at the end of the install, the success message offer a link to log in, but it was sending me back to the install screen
- if trying to go through the install process again, I got an error about duplicate entry.

Today I tried r583 : same problem.
But looking at the database, the tables had been created with the default tbl_ prefix, even though I set i to psend_ in the config file.
So as the install is creating the tables with one prefix and ProjectSend is looking for another one, the install screen is shown again.

The workaround is to let the prefix set to tbl_, but it could be nice to have the possibility to set it to something else.

Anyway, I'm finally able to try ProjectSend !

**Comment by lenamtl** [comment]
Hi, this is a known issue see #39
