### ISSUE TITLE
encoding issue whith accentuated characters on page my_files

### ISSUE THREAD

**Issue by ClmH** [ignacionelson/ProjectSend#91]
Hi,

When I upload a file as a user, the special characters in the description are not displayed on the page my_files. Instead, It shows the HTML code for the character.
For example :
`Test d&#039;accents : &agrave;&ccedil;&oelig;&eacute;&ocirc;&Agrave;`
But editing with edit-file.php still shows the characters properly :
`Test d'accents : àçœéôÀ`

**Comment by lenamtl** [comment]
Hi, this is a known issue.

I'm working on a fork that will handle french and latin characters correctly even in the DB.
The problem is that **&agrave; **is saved instead of **à** in the DB in some place it decode correctly other not...

See bug #35 for temporary solution.
