### ISSUE TITLE
Can't enter title for file during upload process & thumbnails

### ISSUE THREAD

**Issue by RKO1337** [ignacionelson/ProjectSend#95]
Hello,

i have installed Projectsend r582 on a CentOS 6 machine using Apache and using PHP 5.3.3.
I have the same issue as it's described here [https://github.com/ignacionelson/ProjectSend/issues/68](url).

I tried different files (Empty .txt document smal jpg pictures), but i can't enter a title for my file and because of this the upload doesn't succeed.

Other forms like adding a client are working fine.

In the thread above is described that i need to set folder permissions, which folders permissions should i change and to which user/group?

I have searched through the logs in /var/log/httpd but at the time when i try to upload a file nothing is listed in the logs. 

Thanks,
Jan

**Comment by lenamtl** [comment]
Do a test with regular file not too big and not empty.
Start with chmod 777 to see if that worked, if it is not this is not the culprit, 
If it does work then tried more secure till it's stop to work.

**Comment by RKO1337** [comment]
Thank you very much it worked! 
I still do have two more problems, probably again because of wrong permissions, i don't know.

I can't see thumbmails of my uploaded my files its set to the default size, and i can't see my logo.
I attatched screenshots of my problems. 

Thanks,
Jan 
![thumbmail](https://cloud.githubusercontent.com/assets/18141698/14110295/19528e26-f5c6-11e5-825b-0d609267dea8.JPG)
![logo](https://cloud.githubusercontent.com/assets/18141698/14110298/1c47f94a-f5c6-11e5-9bfc-beb00cf31a92.JPG)

**Comment by lenamtl** [comment]
To fix this go into Admin options, there is a setting for thumbnails, just tried the other value.

**Comment by RKO1337** [comment]
I changed the value to 777 to the logo und thumbs folder and to the files in these folders in /var/www/html/projectsend/img/custom, still can't see the logo or thumbnails

![Uploading thumbs.JPG…]()

**Comment by lenamtl** [comment]
first have you change the settings for thumbnails in Admin configuration of Projectsend

**Comment by RKO1337** [comment]
Thanks, I ticked the box but I still can't see my logo or thumbnails.

**Comment by lenamtl** [comment]
Ok then keep it ticked
Now check the chmod of children folder of /img/custom

**Comment by RKO1337** [comment]
I set the chmod of img/custom/logo and img/custom/thumbs and kept "Use file's absolute path" ticked.
![custom chmod](https://cloud.githubusercontent.com/assets/18141698/14167675/21bba28e-f71d-11e5-9d39-6f6670c0e895.JPG)
Still no change to my logo/thumbnails..

**Comment by lenamtl** [comment]
check if you have any error using Chrome dev tool.
Make sure that files are in the folder.
Try to upload a new file to see if the thumbnail is created

**Comment by RKO1337** [comment]
Okay i tried uploading new files and there is no thumnail created. In my thumbs folder are also no files created for my new uploaded files. 
When i open the failed to load image icon of the thumbnail the URL shows that source of the thumbnail is in "upload/files/thumb_2.JPG&w=100&q=90", shouldn't it be /img/custom/thumbs/filesname.jpg
![chromedev](https://cloud.githubusercontent.com/assets/18141698/14200651/986b407c-f7ec-11e5-8a85-cf37e0dea97d.JPG)

**Comment by lenamtl** [comment]
You check the old reposity issues for some old solutions, the code have change a lot but some issues are still the same
https://code.google.com/archive/p/clients-oriented-ftp/issues/474
change the permissions of folders includes - timthumb - cache - timthumb.php - index.html and timthumb_cache lastcleantime.touch from 777 to 755

**Comment by RKO1337** [comment]
Thanks, i changed the permissions to 755 can't see any thumbnails.
So i searched in the error log. now there are some errors listed. 
These errors i get with chmod 775 on my index.html 
![error log timthumb_php](https://cloud.githubusercontent.com/assets/18141698/14244360/f5eac6ee-fa5a-11e5-8d6e-03e8ea685590.JPG)
So i checked the timthump.php 
![timthumb 197](https://cloud.githubusercontent.com/assets/18141698/14244376/0c77f45e-fa5b-11e5-9dd3-bc55e0715029.JPG)
So no permissions on the index.html with 755, i set it 777 and this error doesn't appear anymore in my error log.
This is in line 469 of my timthumb.php
![timthumb 469](https://cloud.githubusercontent.com/assets/18141698/14244437/686d3c24-fa5b-11e5-9814-f71693655107.JPG)
This error istn't influenced by the chmod of index.html (tried 755 and 777). I also changed the value of the timthumb.php to 777, no changes. 

I don't get the meaning of line 469, any ideas?
