### ISSUE TITLE
Unable to Hide/Show in manage files

### ISSUE THREAD

**Issue by AlanReiblein** [ignacionelson/ProjectSend#96]
version R582
Unable to Hide or Show files in Manage Files for individual clients.
Can Hide/Show for all clients.

I looked in manage-files.php and do not understand why $selected_files is used line 190 when in the code above work has been done (177-180) to collect 'id' and 'filename' from the database into $all_files.

Surely to select set the hide flag for the file for the client  it has to be the file id related to the client.

**Comment by lenamtl** [comment]
Hi,
I'll suggest you to update to the R583 because security issue has been fixed.

**Comment by AlanReiblein** [comment]
Where do I find that download (or the collection of files/modules to convert r582 to r583)
The website only has r582
Not got upto speed since moving from the google system to github

**Comment by lenamtl** [comment]
On the main Github project page 
https://github.com/ignacionelson/ProjectSend 
click on **dowload zip** button 

I recommend to make a complete backup of your existing installation file and folder, prior any update.
The best is to create a new project then add your previous custom code to it.

**Comment by AlanReiblein** [comment]
I downloaded that.
I have a test site for testing updates.
Thanks

**Comment by AlanReiblein** [comment]
The hide/show/unassign functions does not work in r583 either.

**Comment by AlanReiblein** [comment]
Sorry the hide./functions do work. Forgot to change the system directory in options in the database so it translated back to the previous version.

**Comment by lenamtl** [comment]
Ok, so does everything is fine now?

**Comment by AlanReiblein** [comment]
Yes, for this thread.

Thanks
