### ISSUE TITLE
Duplicate entry error during installation

### ISSUE THREAD

**Issue by nclm** [ignacionelson/ProjectSend#99]
Hi,
I get this error when installing, just after entering my info and clicking ‘Install’:

> There seems to be an error. Please try again.
> Duplicate entry '1' for key 'PRIMARY'

Does someone know what is happening?
Thanks!

**Comment by lenamtl** [comment]
Are you trying to reinstall over an existing installation?
Are you trying to install online or locally?
This mean the database have already the table and primary key....

**Comment by nclm** [comment]
Thanks for your answer!
I found the issue. I had manually changed the `TABLES_PREFIX` value in `sys.config.php`, but the installer was still creating `tbl_` tables. So instead of the log-in form, I was still offered the install form, getting this error from the second time and so on.

**Comment by nclm** [comment]
So should this be a bug: _“Installer doesn’t use the defined value of TABLES_PREFIX”_?

**Comment by lenamtl** [comment]
This is a known issue, this will be fixed soon.

**Comment by nclm** [comment]
Ok, great, thanks!
